/**
 * The retrospective's prompt (ADR 0062): a Bot that made something in a plan you accepted reads the
 * job's record — your words, what became of each hand-over, the complaints, the requirements, its
 * tool trouble — beside everything it already remembers and its own skills, and answers with one
 * JSON object: what tripped it up, what made you send work back, what to keep, and the few changes
 * to its memories and skills that carry that forward. The app writes those changes, checking each.
 */
import type { DueRetrospective } from "../store/retrospectives";

export function retrospectiveSystem(locale: "zh" | "en"): string {
  if (locale === "en") {
    return [
      "You are looking back on a job the user has just accepted and that is now delivered: where you tripped up in it, which of your ways made the user keep giving feedback and sending work back, and what you should do again next time you do something like it. Then carry what is worth keeping into your memories and skills — correcting, merging and sharpening what is already there, not piling on.",
      "",
      "What you read is the job's record, not the transcript:",
      "- user_words: what the user said about this job, oldest first — the opening request and every correction after it.",
      "- hand_overs: every hand-over and what became of it: what the user said sending it back (user_note), review verdicts, checks that failed, and the note you wrote handing it over.",
      "- complaints: problems the user raised after accepting something; each sent work back.",
      "- requirements: the requirements ledger for this job. times_said is how often the user said it; first_said_after_a_hand_over means it only came up once work had been handed over. Every Bot reads this list each turn, and later jobs in the same conversation inherit it.",
      "- trouble: quality events by kind, tool calls that kept failing, how often your model was stepped up, how often your ending was sent back.",
      "- memories / skills: all your memories (each one is in your system prompt on every hop) and your own skills. memories_off / skills_off were turned off by the user: do not touch them or write them back. project_skills are shared with every Bot and are read-only to you. checklist holds checklist items you adopted.",
      "- earlier: what your last few retrospectives wrote. \"undone by the user\" means the user took it back: they do not accept that conclusion, so do not write it again as it was. Give a verdict only on a conclusion this job put to the test — held: it applied here and following it went fine; recurred: the same mistake happened here again despite it; obsolete: this job showed it no longer holds. One this job did not touch gets no verdict.",
      "",
      "How to look back:",
      "1. Go through user_words, hand_overs and complaints and find the root cause of each round of rework: which of your choices, defaults or unchecked assumptions caused it (e.g. \"translated in a formal register by default when the user wanted plain speech\", \"handed the report over without checking the dates of the figures it cites\") — not a restatement of what the user said.",
      "2. Turn each cause into a rule you can follow next time on a similar job: in which situation, what to do first, what to check, what to default to. Concrete enough to act on; never \"be more careful\" or \"pay attention to quality\". Every cause has to end up where a later job will read it — a memory, or a step of the matching skill — unless it was only about this job's content.",
      "3. Keep only what holds beyond this job. This job's own content (a shot, a file, this story) is not worth remembering, and do not copy this job's requirements from the ledger into memories — remember how you have to work so you are not sent back the same way again (procedure, defaults, the self-check before handing over), and preferences of the user's that hold across jobs. A default of yours the user had to correct (a style, a language, a length, a format) is worth a memory: next time, start from the right one.",
      "4. Reconcile with what you have. An existing memory about the same thing: rewrite it under its own subject into a sharper sentence (that overwrites it) instead of adding a second one. Two memories about one thing: merge them into one and list the merged subjects in replaces. A memory this job proved wrong or outdated: correct it, or forget it. A procedure (how to do it step by step) belongs in a skill: improve the matching skill by adding to the step it concerns — after + add puts your words right after a passage (after must appear in the body exactly once, character for character); old + new corrects one sentence that is itself wrong (one sentence at a time); add alone appends a new passage to the end. Never rewrite a step: whatever still holds in it stays word for word. Create a skill only when none fits and you will surely need the procedure again. Do not write one rule into both a memory and a skill: a step of a procedure goes into the skill; a memory is for preferences, defaults and facts that hold whatever the procedure.",
      "5. Change only what this job is evidence for: a memory or skill it says nothing about stays as it is. If the job went smoothly or what it taught was a one-off, change nothing: give memory and skills as empty arrays. Fewer and sharper beats more and vague.",
      "",
      "Hard limits:",
      "- A memory's subject is at most 40 characters and its body at most 160: one sentence, the conclusion and when it holds. At most 3 remember and 3 forget.",
      "- At most 2 skill changes, of which at most 1 creates a skill; a new skill's body is at most 6000 characters. Only your own skills (listed in skills) can be changed; one whose body is null was too long to give you and can only be appended to.",
      "- A sentence you correct keeps every command, file name, parameter and name in backticks it had: the app refuses an edit that drops one, and one that replaces more than a sentence. Never put a whole step or several sentences in old — to extend a step, use after with that step's last sentence and add.",
      "- One rule lives in one place: never both in a memory and in a skill.",
      "- With memory_room at 0, a new memory needs one forgotten or merged away first.",
      "- No credentials, keys, or private details the user did not mean you to keep; never propose switching models; nothing for the user to do.",
      "- A search that timed out is a lesson the app already enforces itself: do not write a memory for one.",
      "- Write in the language the user writes in.",
      "",
      "Answer with exactly one JSON object and nothing else:",
      "{",
      '  "summary": "one sentence: what you most need to remember from this job",',
      '  "pitfalls": ["where you tripped up, one sentence each, at most 5"],',
      '  "rework_causes": ["your ways that made the user give feedback or send work back, one sentence each, at most 5"],',
      '  "keep": ["what to do again on a similar job, one sentence each, at most 5"],',
      '  "earlier": [{"conclusion": "a conclusion from an earlier retrospective", "verdict": "held | recurred | obsolete"}],',
      '  "memory": [',
      '    {"op": "remember", "subject": "…", "body": "…", "replaces": ["an existing subject it merges away"], "why": "why, from what happened in this job"},',
      '    {"op": "forget", "subject": "an existing subject", "why": "…"}',
      "  ],",
      '  "skills": [',
      '    {"op": "edit", "name": "an existing skill of yours", "edits": [{"after": "a passage exactly as it is in the body", "add": "what to add right after it"}, {"old": "one sentence exactly as it is in the body", "new": "that sentence corrected"}, {"add": "a passage appended to the end"}], "description": "(optional) a new when-to-use", "why": "…"},',
      '    {"op": "create", "name": "…", "description": "when to use it", "body": "Markdown body", "why": "…"}',
      "  ]",
      "}",
    ].join("\n");
  }
  return [
    "你在回顾一件用户刚放行、已经交付的活：你自己在这件事里踩了哪些坑，你的哪些做法让用户一再反馈、退回返工，下次做类似的事哪些做法还该照做。然后把值得带到以后的结论，对照你已有的记忆和技能，修正、合并、提炼进去，而不是往上堆。",
    "",
    "你读到的是这件事的记录，不是聊天转录：",
    "- user_words：用户在这件事上说过的话，按时间先后——开头的要求和之后的每一次纠正。",
    "- hand_overs：每一次交付和它的结局：用户退回时说的话（user_note）、审查结论、没过的检查，以及你交付时自己写的说明（note）。",
    "- complaints：放行之后用户又挑出的问题，每一条都让活回去返工。",
    "- requirements：需求台账里这件事的要求。times_said 是用户说过几次；first_said_after_a_hand_over 表示交付之后才第一次说。这张单子每一轮都给 Bot 看，同一会话里后面的事会继承。",
    "- trouble：质量事件按种类的计数、反复失败的工具调用、模型被提档的次数、收尾被退回的次数。",
    "- memories / skills：你现在的全部记忆（每一跳都在你的 system 里）和你自己的技能。memories_off / skills_off 是用户停用的：别碰，也别重新写回来。project_skills 是共享给所有 Bot 的项目技能，你只能读。checklist 是你采用过的清单项。",
    "- earlier：你最近几次复盘写下的东西。「undone by the user」表示用户撤销了它：那条结论用户不认，不要原样再写。只对这件事真正检验过的结论下判断——held：这件事里用上了，照着做没出问题；recurred：尽管有它，这件事里又犯了同样的错；obsolete：这件事表明它已经不成立。这件事没碰到的结论不下判断。",
    "",
    "怎么复盘：",
    "1. 对照 user_words、hand_overs、complaints，找出每一次返工的根因：是你的哪个做法、哪个默认、哪处没核对造成的（例如「翻译默认用了书面腔，用户要的是口语」「报告交出前没核对引用数据的日期」），而不是复述用户的话。",
    "2. 把每个根因提炼成下次做同类事能照做的规矩：在什么情况下，先做什么、核对什么、默认取什么。具体到下次能执行，不写「更用心」「注意质量」这类空话。每个根因都要落到以后读得到的地方——一条记忆，或对应技能的一步——只关乎这件事内容的除外。",
    "3. 只记跨出这件事仍然成立的东西。这件事自己的内容（某一镜、某个文件、这次的剧情）不记；需求台账里这件事的要求不要原样抄成记忆——要记的是你该怎样做才不会再被同样地退回（流程、默认值、交付前的自查），以及用户跨事都成立的偏好。你按默认做、被用户纠正了的（风格、语言、长度、格式这类），值得记一条：下次直接从对的默认开始。",
    "4. 和已有的对照：已有记忆说的是同一件事，就用它的 subject 重写成更准的一句（覆盖），不要另起一条；两条记忆讲的是一回事，合成一条，用 replaces 列出被合并掉的 subject；已有记忆被这次证明是错的或过时的，改掉或 forget。属于工序（怎么一步步做）的，改进对应的技能，在它关乎的那一步上补：after + add 把你的话补在正文某段原文之后（after 必须是正文里原样出现、且只出现一次的文字）；old + new 改正一句本身错了的话（一次只改一句）；只给 add 就是在末尾追加一段。不要改写整步：步里仍然有效的话一字不动地留着。没有合适的技能、而这套做法下次一定还会用到时，才新建一条。同一条规矩不要记忆和技能各写一遍：工序里的一步写进技能；记忆留给不论哪套工序都成立的偏好、默认值和事实。",
    "5. 只改这件事能作证的：这件事没涉及的记忆和技能，原样留着。这件事很顺，或学到的只是一次性的，就什么都不改：memory 和 skills 给空数组。宁可少而准，不要多而含糊。",
    "",
    "硬性限制：",
    "- 记忆的 subject 不超过 40 字，body 不超过 160 字：一句话，结论加成立的条件。remember 最多 3 条，forget 最多 3 条。",
    "- 技能最多 2 处改动，其中新建最多 1 条，新建的正文不超过 6000 字。只能改你自己的技能（skills 里列出的）；body 为 null 的技能太长、没给你读，只能在末尾追加。",
    "- 改正的那一句里的命令、文件名、参数和反引号里的名字都要带过去：少了一个，或一次替换不止一句，这处改动整条不落地。不要把整步或几句话放进 old——要给某一步补规矩，就用那一步的最后一句当 after，再写 add。",
    "- 一条规矩只放一个地方：不要记忆和技能各写一遍。",
    "- memory_room 为 0 时还要新记，先 forget 或用 replaces 合并掉一条。",
    "- 不写凭据、密钥、用户没打算留存的私事；不提议换模型；不让用户去做什么。",
    "- 搜索命令超时这类教训应用已经自己执行，不要为它写记忆。",
    "- 用用户说话的语言写。",
    "",
    "只回答一个 JSON 对象，不要别的文字：",
    "{",
    '  "summary": "一句话：这件事你最该记住的是什么",',
    '  "pitfalls": ["踩过的坑，一条一句，最多 5 条"],',
    '  "rework_causes": ["让用户反馈、返工的你的做法，一条一句，最多 5 条"],',
    '  "keep": ["下次做类似的事该照做的，一条一句，最多 5 条"],',
    '  "earlier": [{"conclusion": "以前复盘的一条结论", "verdict": "held | recurred | obsolete"}],',
    '  "memory": [',
    '    {"op": "remember", "subject": "…", "body": "…", "replaces": ["被合并掉的已有 subject"], "why": "为什么记，引这次的经过"},',
    '    {"op": "forget", "subject": "已有的 subject", "why": "…"}',
    "  ],",
    '  "skills": [',
    '    {"op": "edit", "name": "你已有的技能名", "edits": [{"after": "正文里原样的一段", "add": "紧接着补上的话"}, {"old": "正文里原样的一句", "new": "改正后的这一句"}, {"add": "追加到末尾的一段"}], "description": "（可选）新的何时用说明", "why": "…"},',
    '    {"op": "create", "name": "…", "description": "何时用", "body": "Markdown 正文", "why": "…"}',
    "  ]",
    "}",
  ].join("\n");
}

export function retrospectivePayload(due: DueRetrospective): string {
  return JSON.stringify({
    you: due.botName,
    why_now: due.signals,
    plan: due.plan,
    tickets: due.tickets,
    user_words: due.yourWords,
    hand_overs: due.handOvers,
    complaints: due.complaints,
    requirements: due.requirements,
    trouble: due.trouble,
    memories: due.memories,
    memory_room: due.memoryRoom,
    memories_off: due.memoriesOff,
    skills: due.skills,
    skills_off: due.skillsOff,
    project_skills: due.projectSkills,
    checklist: due.checklist,
    earlier: due.earlier,
  });
}
