import type { Locale } from "@real-bot/protocol";

/** Locked in 设置里「壳不是囚笼」写哪一句. Do not paraphrase. */
export const JAIL_COPY = {
  zh: "工作区壳把当前目录放在工作区并在启动前检查看得见的路径，不是操作系统囚笼。",
  en: "The workspace shell puts the current directory in the workspace and checks paths visible in the command before start; it is not an operating-system jail.",
} as const;

type CopyShape<T> = T extends (...args: infer A) => string
  ? (...args: A) => string
  : T extends object
    ? { [K in keyof T]: CopyShape<T[K]> }
    : string;

const zh = {
  routines: {
    title: "日程", add: "新建日程", edit: "编辑日程", empty: "这个 Bot 还没有日程。",
    owner: "归属 Bot", name: "标题", instruction: "任务指令", frequency: "重复", daily: "每天", weekly: "每周",
    time: "时间（24 小时制）", weekdays: "星期", days: { mon: "周一", tue: "周二", wed: "周三", thu: "周四", fri: "周五", sat: "周六", sun: "周日" },
    daysShort: { mon: "一", tue: "二", wed: "三", thu: "四", fri: "五", sat: "六", sun: "日" },
    workdays: "工作日", weekend: "周末", allDays: "全选",
    zone: "按执行 Mac 的本地时区运行，不按此浏览器的时区换算。",
    availability: "执行 Mac 需醒着且运行时可用；恢复时只补最近一次，不逐次补跑。归档 Bot 不执行日程。",
    enabled: "启用", active: "已启用", paused: "已暂停", pause: "暂停", resume: "恢复", save: "保存日程", cancel: "取消", busy: "正在保存…",
    remove: "删除日程", deleteBody: "删除后不会再触发此日程；已开始的任务不会因此停止。", confirm: "确认删除",
    nameRequired: "请填写标题。", timeInvalid: "请输入有效的 HH:MM 时间（00:00–23:59）。", daysRequired: "每周日程至少选择一天。",
    failed: "未能保存日程，请重试。", invalid: "日程字段无效，请检查标题、时间和星期。", missing: "此日程已被删除。", conflict: "日程已在别处更新。你的草稿未覆盖它；载入最新版本后再编辑。",
    reload: "载入最新版本", disconnected: "连接已变化，未确认保存结果。重连后请核对日程，不会自动重试。",
    unknown: "原请求结果未知，可能已保存。不会自动重试。",
    pending: "原请求仍待确认，未发送修改后的草稿。这不是版本冲突。",
    retry: "重试原请求", retryHint: "重试使用原请求的内容和编号，不会发送后来修改的草稿。",
    retired: "原请求已结束待确认状态。重试未发送后来修改的草稿；请先核对列表，重新打开日程后再保存保留的草稿。",
  },
  calendar: {
    title: "日程图",
    open: "日程图",
    empty: "名册上还没有日程。",
    phoneReadOnly: "这里可以看。改时间请到桌面拖动，或打开 Bot 的日程。",
    projectionHint: "格子是规则展开，不是每次运行的记录。标出的应跑点只在这台 Mac 上可信。",
    lastFiredHostOnly: "应跑点标记只在执行 Mac 上显示。格子上的钟点就是那台 Mac 的本地时间。",
    detail: "日程详情",
    lastFired: "这是最近一次应跑点。",
    noInstruction: "没有任务指令。",
    filter: "名册",
    filterAll: "全部",
    filterSearch: "搜索名字或职责",
    filterNoMatch: "没有匹配的 Bot。",
    filterShow: "显示",
    filterHide: "隐藏",
    filterReset: "重置",
    agendaEmpty: "这一段没有日程。",
  },
  common: {
    you: "你",
    close: "关闭",
    back: "返回",
    copyImage: "复制图片",
    copyImageFailed: "没能复制图片",
    updateReady: "有新版本",
    updateReload: "刷新",
  },
  disconnected: {
    message: "连不上运行时",
    host: "执行主机不可达",
    connecting: "正在连接运行时…",
    connectingHost: "正在连接执行主机…",
    retry: "重试",
    hostHint: "任务仍只在已唤醒的 Mac 上执行。不会排队离线命令。",
  },
  remote: {
    pairTitle: "配对访问设备",
    pairLead: "用 Mac 上显示的配对内容完成本设备登记。新设备必须人在 Mac 旁确认。",
    pairHint: "只粘贴 Mac 上给的配对内容。不要把它当成网址打开，也不要写进查询串或日志。",
    pairPaste: "配对内容",
    pairSubmit: "提交并等待 Mac 确认",
    pairWaiting: "已发给这台 Mac，等待本地确认…",
    pairExpired: "配对窗口已过期。请在 Mac 上重新打开配对。",
    pairRejected: "配对被拒绝或取消。",
    pairInvalid: "配对内容无效。",
    pairUrl: "配对内容不能是网址或查询串。",
    fingerprint: "主机签名指纹",
    experimental: "实验性远控。公网配对默认关闭；S-rev、G-uv 与真机 L1 尚未通过。",
    uvNeeded: "高危动作需要本设备 WebAuthn 用户验证，没有点击确认替代。",
    uvFailed: "WebAuthn 登记失败。普通聊天仍可用，但不能做高危动作。",
    uvRegister: "登记本设备用户验证",
    draftConfirm: "重连后仍有未发送草稿。确认后才发送，不会自动重放。",
    draftSend: "确认发送草稿",
    draftDiscard: "丢弃草稿",
    statusOff: "远控关闭",
    statusUnavailable: "原生凭据不可用",
    statusGated: "远控激活仍关闭",
    statusConnecting: "正在连接中继",
    statusOnline: "远控在线",
    statusDisconnected: "远控已断开",
    statusMismatch: "远控信任不匹配",
    devices: (n: number) => `已配对设备 ${n}`,
    noOfflineQueue: "没有离线命令队列。结果未知时查询同一请求回执，不换新编号重发。",
    maintenance: "维护",
    maintenanceLead: "状态、脱敏诊断和受控重启只走已加密会话。超时或掉线不会自动强制。",
    version: (v: string) => `版本 ${v}`,
    modeWindow: "窗监督",
    modeStandalone: "独立运行时",
    modeNone: "无监督者",
    restartAvailable: "可由当时监督者拉起",
    restartUnavailable: "重启不可用：窗不在且未独立。不会安装后台任务。",
    drainRunning: "运行中",
    drainWaiting: (n: number) => `正在排空，剩余 ${n} 个活轮`,
    drainDrained: "已排空",
    drainForced: "已强制中断",
    refreshStatus: "刷新状态",
    downloadDiagnostics: "下载脱敏诊断",
    drainRestart: "排空后重启",
    forceRestart: "强制中断并重启",
    forceWarn: "强制会中断活轮且不重放工具。必须新的用户验证，不能点确认代替。",
    forceConfirm: "确认强制重启",
    stopRuntime: "停止运行时",
    stopWarn: "停止会写入闩并退出。监督者不会再拉起，直到本机清除停止闩。",
    stopConfirm: "确认停止",
    revokeOther: "吊销其它设备",
    revokeConfirm: (name: string) => `确认吊销 ${name}`,
    noOtherDevices: "没有可吊销的其它设备。",
    reconnectHint: "重连只查询状态和同一请求回执，不会再触发重启。",
    errorDraining: "运行时正在排空，新请求被拒绝。",
    errorUnavailable: "当前没有可用的监督者，不能远程重启。",
    errorCancelled: "排空等待已取消。没有自动强制。",
    errorUv: "需要新鲜的 WebAuthn 用户验证。",
    errorUnknown: "结果未知。请查询同一回执，不要换新编号。",
    push: "待办推送",
    pushDesc: "仅泛化提醒「Real Bot 有待处理事项」。点击打开信使回到会话列表，不会批准或执行命令。拒绝或过期不影响待办。iOS 需 16.4+ 主屏幕；真机主屏幕门尚未通过。",
    pushDenied: "系统已拒绝通知。待办仍标在对应会话上。",
    pushUnsupported: "此浏览器不支持 Web Push。",
    pushFailed: "未能更新推送订阅。",
    hostPair: "配对新设备",
    hostPairPaste: "在设备上打开中继地址，把这段粘进配对页。它带一次性密钥，十分钟后失效，别写进日志或聊天记录。",
    hostPairFingerprint: "核对设备上显示的主机指纹，对得上再继续。",
    hostPairEmpty: "还没有设备配对到这台 Mac。",
    connectedDevices: "已连接设备",
    connectedDevicesEmpty: "还没有已连接设备。",
    lastActive: (value: string) => `最近活跃于 ${value}`,
    lastActiveUnknown: "最近活跃时间未知",
    removeDevice: "移除设备",
    removeDeviceConfirm: (name: string) => `确认移除 ${name}`,
    deviceActionFailed: "设备操作失败，请重试。",
    hostPairRetry: "重新开一个窗口",
    hostPairWaiting: "等待设备提交…",
    hostPairArrived: (name: string) => `${name} 请求配对。`,
    hostPairCompare: "这串要和设备上显示的一致。",
    hostPairApprove: "批准这台设备",
    hostPairDone: "已配对。设备现在可以连上这台 Mac。",
    hostPairExpired: "配对窗口已过期，重新开一个。",
    hostPairFailed: "开配对窗口失败。",
  },
  sidebar: {
    roster: "名册",
    pinned: "置顶",
    pinnedEmpty: "暂无置顶会话",
    pin: "置顶",
    unpin: "取消置顶",
    expand: "展开",
    collapse: "收起",
    search: "搜索会话、消息、文件、日程",
    searchShort: "搜索",
    searchClear: "清除搜索",
    emptySearch: "没有命中。",
    searchKindBot: "Bot",
    searchKindSession: "会话",
    searchKindMessage: "消息",
    searchKindRoutine: "日程",
    routineUnavailable: "日程或所属 Bot 已不可用，无法打开。历史日程仍会保留。",
    searchKindFile: "文件",
    groups: "群",
    youBot: "你 ↔ Bot",
    botBot: "Bot ↔ Bot",
    botBotSource: (title: string) => `来自 ${title}`,
    botBotSourceRoot: (immediate: string, root: string) => `来自 ${immediate}（源头：${root}）`,
    botBotSourceUnknown: "来源未知",
    botBotSourceMissing: "来源已不在",
    botBotMore: (n: number) => `还有 ${n} 个`,
    settings: "设置",
    notifications: "通知",
    addBot: "新建 Bot",
    addGroup: "新建群",
    createMenu: "新建",
    botName: "名字",
    botDuties: "职责",
    botBoundaries: "边界",
    botAvatar: "头像",
    botAvatarRefresh: "换一个",
    botAvatarStyle: "风格",
    botAvatarCustom: "上传图片",
    botAvatarCustomHint: "PNG、JPEG 或 WebP，最大 8 MB。",
    botAvatarInvalidType: "请选 PNG、JPEG 或 WebP 图片。",
    botAvatarTooLarge: "图片太大了。",
    botAvatarDecodeFailed: "没能读这张图片。",
    botModel: "模型",
    botModelDefault: "自动",
    botModelInvalid: "挑名单里的一个模型。",
    botThinking: "思考等级",
    botModelAutoHint: "自动：每条消息由应用挑模型，思考等级跟着那个模型走。挑一个模型就要同时定下思考等级。",
    botThinkingHint: "只列这个模型支持的档。换模型时会落到新模型的默认档。",
    botThinkingInvalid: "挑这个模型支持的思考等级。",
    thinkingLevels: { none: "不思考", low: "低", medium: "中", high: "高", xhigh: "极高", max: "最大", minimal: "最低" },
    autoSaving: "保存中…",
    autoSaved: "已自动保存",
    autoSaveHint: "改动自动保存",
    skills: "技能",
    skillsEmpty: "还没有技能。",
    skillAdd: "添加技能",
    skillName: "名称",
    skillDescription: "何时用",
    skillBody: "怎么干",
    skillUses: "依赖的 MCP",
    skillUsesPlaceholder: "服务器名，逗号分隔；可留空",
    skillUsesHint: "写正文里要调的 MCP 服务器名。本轮没连上的会在技能目录里标出来，Bot 就不会硬套正文。",
    skillEnabled: "启用",
    skillNameEmpty: "填写一个名称。",
    skillDescriptionEmpty: "填写何时用。",
    skillBodyEmpty: "填写怎么干。",
    skillNameConflict: "这个名称已经有了。",
    skillDelete: "删除技能",
    skillDeleteBody: "删除后，这个 Bot 下一跳就看不见这条技能。",
    skillConfirmDelete: "确认删除",
    skillEdit: "编辑技能",
    skillSave: "保存技能",
    skillCancel: "取消",
    memories: "记忆",
    memoriesEmpty: "还没有记忆。Bot 自己记下跨会话要用的事，你可以改或删。",
    memoryHint: "Bot 自己记下跨会话要记住的事，每一跳都会读到。改错了或过期了，改一下或停用。",
    memorySubject: "关于",
    memoryBody: "记住了什么",
    memoryEnabled: "启用",
    memoryEdit: "编辑记忆",
    memorySave: "保存",
    memoryCancel: "取消",
    memoryDelete: "删除记忆",
    memoryDeleteBody: "删除后，这个 Bot 下一跳就看不见这条记忆。",
    memoryConfirmDelete: "确认删除",
    memorySubjectEmpty: "填写这条记忆是关于什么的。",
    memoryBodyEmpty: "填写记住了什么。",
    memorySubjectConflict: "关于这件事已经有一条记忆了。",
    memoryFormedIn: (where: string) => `记于 ${where}`,
    learningNoneYet: "还没有后续同类任务",
    learningLater: (later: number, shorter: number) => `之后 ${later} 次同类任务，${shorter} 次更短`,
    memoryOriginMissing: "来源已不在",
    memoryEditedByYou: "你改过",
    memoryJump: "跳到记下它的那条消息",
    memoryShowAll: (n: number) => `显示全部 ${n} 条`,
    memoryCollapse: "收起",
    memoryAgeToday: "今天",
    memoryAgeThisWeek: "本周",
    memoryAgeWeeks: (n: number) => `${n} 周前`,
    memoryAgeMonths: (n: number) => `${n} 个月前`,
    groupName: "群名",
    groupMembers: "成员",
    groupMembersPlaceholder: "挑两个或更多 Bot",
    groupMemberSearch: "接着搜",
    groupMemberNoMatch: "没有匹配的 Bot。",
    groupMemberNone: "名册里还没有 Bot。",
    groupMemberRemove: "移出",
    create: "保存",
    nameEmpty: "填写一个名字。",
    dutiesEmpty: "填写职责。",
    boundariesEmpty: "填写边界。",
    nameConflict: "这个名字已经有了。",
    groupNameEmpty: "填写一个群名。",
    membersTooFew: "至少挑两个 Bot。",
    saveFailed: "没能保存。",
    profile: "人设",
    viewInfo: "查看信息",
    clearHistory: "清除历史",
    archive: "归档",
    unarchive: "取消归档",
    restore: "恢复",
    archiveBody: "从名册移入已归档。会话还在，历史消息保留。",
    restoreBody: "把这个 Bot 放回名册。",
    delete: "删除",
    deleteBody: "删除后，这个 Bot 从名册去掉。会话还在，标题会变成「已删除」。工作区文件不动。",
    confirmDelete: "确认删除",
    cancel: "取消",
    statusRunning: "思考中",
    statusReplying: "回复中",
    statusWaitingApproval: "待审批",
    statusWaitingAsk: "待回复",
    statusFailed: "未完成",
    statusInterrupted: "已中断",
    statusIdle: "空闲",
    unread: "未读",
    noMessages: "还没有消息",
    archivedSessions: "已归档会话",
    archivedEmpty: "没有已归档的会话",
    backToSessions: "返回会话列表",
    resize: "拖动调整会话列表宽度",
    mainNavigation: "主导航",
    sessions: "会话",
    workspace: "工作区",
    tools: "更多",
    workspaceUnset: "先在设置里选择工作区目录。",
    updateAvailable: "有新版本",
  },
  settings: {
    title: "设置",
    tabGeneral: "通用",
    tabPreferences: "基础偏好",
    tabNotifications: "通知",
    tabModels: "模型服务",
    tabMcp: "MCP 扩展",
    tabAbout: "关于",
    sectionWorkspace: "工作区目录",
    workspaceSubtitle: "Bot 的文件读写与命令执行限制在此目录下",
    workspaceConfigured: "已配置",
    workspaceUnsetNotice: "未配置",
    workspaceSecurityBoundary: "工作区安全边界",
    sectionPreferences: "基础偏好",
    preferencesSubtitle: "个性化外观、显示语言与系统启动行为",
    themeDesc: "界面外观配色偏好",
    languageDesc: "界面所使用的显示语言",
    launchDesc: "系统登录时在后台自动启动 Real Bot",
    aboutSubtitle: "本机单人 Agent 协作工作区应用",
    remoteSection: "远控（实验性）",
    remoteSubtitle: "浏览器配对身份只存在本机 IndexedDB。聊天、快照、草稿、命令和文件不持久化。",
    sectionEndpoint: "端点与鉴权",
    sectionModels: "模型配置",
    sectionMcpServers: "已配置服务器",
    sectionMcpAdd: "添加 MCP 服务器",
    wizardHint: "向导就是设置的空态：工作区路径、至少一个端点的 URL 和密钥齐了即完成。每个端点有自己的模型名单。不抢主转录。",
    wizardIncomplete: "工作区路径、端点和密钥还没齐。",
    providerName: "名称",
    providerAdd: "添加端点",
    providerEdit: "编辑端点",
    providerEmpty: "还没有模型端点。",
    providerDelete: "删除",
    providerDeleteBody: "删除后，钉了这个端点的 Bot 会改回空钉。若删的是默认端点，默认会换成剩下的第一个。",
    providerConfirmDelete: "确认删除",
    providerCancel: "取消",
    providerDefault: "默认",
    providerSetDefault: "设为默认",
    providerModelCount: (count: number) => (count === 1 ? "1 个模型" : `${count} 个模型`),
    providersHint: "先选这个端点平时用哪个模型。连接和名单分开改。",
    providerConnection: "连接",
    providerModels: "名单",
    providerDefaultModel: (name: string) => `默认模型 ${name}`,
    providerPickDefault: "设为这个端点的默认模型",
    providerNoDefault: "还没选默认模型。先启用一个，再点那一行。",
    providerNameEmpty: "填写一个名称。",
    workspace: "工作区",
    workspaceChoose: "选择文件夹",
    workspaceChange: "更换文件夹",
    workspaceUnsetValue: "尚未选择",
    workspacePickerUnavailable: "请在桌面应用里选择文件夹；浏览器开发态打不开系统对话框。",
    workspaceHostOnly: "工作区根目录只在本机窗口里改，远控不能改。",
    workspaceBrowseRemote: "在执行 Mac 上逐级浏览目录。改根仍须人在 Mac 旁确认。",
    workspaceAuthorizeMac: "在 Mac 上授权一次文件访问后再试。",
    workspaceUseFolder: "使用此目录",
    workspaceUp: "上级",
    workspaceConfirmRoot: "更换工作区根目录需要在 Mac 上确认。",
    fileLimitRemote: "远程附件和工作区下载上限 50 MiB。本机窗口不受此限制。",
    fileLimitHit: "这个文件超过 50 MiB 远程上限。",
    copyRelpath: "复制相对路径",
    downloadFile: "下载",
    endpoint: "端点",
    endpointKey: "端点密钥",
    keySet: "已配置",
    keyUnset: "未配置",
    language: "语言",
    localeZh: "中文",
    localeEn: "English",
    theme: "外观",
    themeSystem: "跟随系统",
    themeLight: "亮色",
    themeDark: "暗色",
    launch: "登录启动",
    independentRuntime: "独立运行时",
    independentRuntimeDesc: "退出桌面后仍由 LaunchAgent 保活本机运行时。默认关；未通过原生封闭门时保持禁用。",
    independentRuntimeGated: "原生运行时未封闭（G-pack 未通过），不能安装独立作业。默认仍由窗口监督。",
    independentRuntimeDev: "开发态不会安装 LaunchAgent。",
    independentRuntimeBrowser: "请在桌面应用里开关此项；浏览器不能安装本机作业。",
    independentRuntimeConfirmEnable: "确认开启独立运行时",
    independentRuntimeConfirmEnableBody:
      "会先排空当前活轮，再把运行时交给用户域 LaunchAgent。失败会明确停机，不会偷偷改回窗口拉起。退出桌面不再停止任务。",
    independentRuntimeConfirmDisable: "确认关闭独立运行时",
    independentRuntimeConfirmDisableBody:
      "会先恢复窗口监督，再卸下 LaunchAgent。桌面未打开时关掉会停止远控，直到你在 Mac 上打开 Real Bot。",
    independentRuntimeWaiting: "正在等待当前活轮结束…",
    independentRuntimeForce: "强制中断并交接",
    independentRuntimeCancel: "取消",
    independentRuntimeFailed: "独立运行时未能启动，请在 Mac 上打开 Real Bot 或重试。",
    independentRuntimeConfirm: "确认",
    save: "保存",
    workspaceEmpty: "选择一个本机目录。",
    workspaceInvalid: "需要本机绝对路径；不能是文件。目录不存在时会自动创建。",
    endpointEmpty: "填写端点 URL。",
    endpointInvalid: "端点必须是 http 或 https 的 URL。",
    keyEmpty: "粘贴端点密钥。",
    models: "可用模型",
    modelsEmpty: "至少填一个模型名。",
    modelsFetch: "获取模型",
    modelsFetching: "获取中...",
    modelsFetchFailed: "未能获取模型列表，可手动添加模型名。",
    modelsRefetch: "重新获取",
    modelsCounts: (enabled: number, available: number) => `已启用 ${enabled} · 可用 ${available}`,
    modelsAutoFetchHint: "填好端点 URL 和密钥后会自动获取模型列表。",
    modelsFetchingHint: "正在从端点获取模型列表…",
    modelsEmptyHint: "还没有模型。获取不到时可以手动添加模型名。",
    modelsFilterAll: "全部",
    modelsFilterEnabled: "已启用",
    modelsEnabledEmpty: "还没有启用的模型，切到「全部」勾选。",
    modelsAddManual: "手动添加模型名",
    modelsAddManualPlaceholder: "端点认的模型名",
    modelsAddConfirm: "添加",
    modelCustomBadge: "手动添加",
    modelAttrsToggle: (name: string) => `${name} 的决策属性`,
    modelPriceTitle: "只给应用挑模型用，不进花费展示。",
    modelStrengthsAdd: "自定义",
    modelStrengthsAddPlaceholder: "例如 vision",
    modelStrengthRemove: (tag: string) => `移除 ${tag}`,
    modelsSelectTitle: "选择要启用的模型",
    modelsSearchPlaceholder: "搜索模型...",
    modelsSelectAll: "全选",
    modelsDeselectAll: "全不选",
    modelsManualToggle: "直接编辑文本",
    modelsListToggle: "返回列表选择",
    modelsAddCustom: "添加自定义模型",
    defaultModel: "默认模型",
    defaultModelEmpty: "挑一个默认模型。",
    defaultModelInvalid: "默认模型必须在可用名单里。",
    modelAttrsEmptyFilter: "没有匹配的模型。",
    modelAttrsDefaultBadge: "默认",
    modelPrice: "价格",
    modelPriceHint: "可选，如 1.5",
    modelThinking: "思考等级",
    modelThinkingAdd: "自定义",
    modelThinkingAddPlaceholder: "例如 xhigh",
    modelStrengths: "擅长领域",
    saveFailed: "没能保存。",
    mcp: "MCP",
    mcpEmpty: "还没有 MCP 服务器。",
    mcpEdit: "编辑 MCP 服务器",
    mcpSearch: "搜索名称、传输或连接地址",
    mcpClearSearch: "清除搜索",
    mcpNoResults: "没有匹配的 MCP 服务器。",
    mcpName: "名",
    mcpTransport: "传输",
    mcpTransportStdio: "stdio",
    mcpTransportHttp: "HTTP",
    mcpCommand: "command",
    mcpArgs: "args",
    mcpUrl: "URL",
    mcpHeaders: "headers",
    mcpAuth: "Authorization",
    mcpAuthHint: "Bearer token。只写进钥匙串，不进列表。",
    mcpEnabled: "启用",
    mcpAdd: "添加",
    mcpConfirmAdd: "确认添加",
    mcpConfirmEdit: "确认改连接",
    mcpCancel: "取消",
    mcpDelete: "删除",
    mcpNameEmpty: "填写一个名。",
    mcpCommandEmpty: "填写 command。",
    mcpUrlEmpty: "填写 MCP URL。",
    mcpUrlInvalid: "URL 必须是 http 或 https。",
    mcpMustConfirm: "新增和改 command / args / URL / headers 必须确认，没有 Always allow。",
    mcpUsageNote: "用法备注",
    mcpUsageNotePlaceholder: "这台用来做什么、什么时候用、什么时候不要用",
    mcpUsageNoteHint:
      "写给所有 Bot 看，每一跳都排在服务器自带说明前面。名称和备注改完即写入、不用确认，改连接也不会丢；留空就只用服务器自带的说明。",
    sectionAbout: "关于",
    version: (version: string) => `版本 ${version}`,
    checkUpdates: "检查更新",
    checkingUpdates: "检查中...",
    upToDate: "已是最新版本。",
    updateAvailable: (version: string) => `有新版本 ${version} 可用。`,
    updateDownload: "下载更新",
    updateInstall: "下载并安装",
    updateInstallHint: "在应用内下载，装好自动重启，不用再过一遍安装器。",
    updateDownloading: "正在下载",
    updateVerifying: "正在校验安装包",
    updateInstalling: "正在替换应用",
    updateRestarting: "装好了，正在重启",
    updateInstallCancel: "取消",
    updateInstallRetry: "重试",
    updateInstallFailedDownload: "没能下载这个版本。",
    updateInstallFailedVerify: "下载到的安装包不是这个版本，已经丢掉。",
    updateInstallFailedInstall: "没能替换当前应用，原来这份没有动。",
    updateInstallFailedReadOnly: "没有权限替换当前这份应用，用浏览器下载后自己覆盖。",
    updateInstallFailedNotInstalled: "当前是从源码跑的，没有可替换的应用。",
    updateInstallFailedOther: "更新没装上，原来这份没有动。",
    updateNotes: "查看发布说明",
    updateChanges: "这一版改了什么",
    updateIgnore: "忽略此版本",
    updateFailed: "没能检查更新。",
  },
  top: {
    groupSettings: "群组设置",
    botSettings: "Bot 设置",
    pickSession: "选择一个会话",
    emptyRoster: "名册是空的。点名册那一行的 + 建 Bot。",
    members: "在场",
    presenceOpen: "可打开（只读）",
    profile: "人设",
    archived: "已归档",
    deleted: "已删除",
    pin: "置顶",
    pinned: "已置顶",
    unpin: "取消置顶",
    moreActions: "更多会话操作",
  },
  pane: {
    /** The word for one content area inside the desktop window. Not 窗口, which is the Tauri window. */
    title: "窗格",
    splitRight: "向右分割",
    splitDown: "向下分割",
    close: "关闭窗格",
    closeTab: "关闭标签页",
    float: "浮动这个窗格",
    dock: "停靠回布局",
    equalise: "平分",
    reset: "重置布局",
    resize: "调整窗格大小",
    junction: "调整交叉点",
    empty: "这个窗格还没有内容",
    emptyHint: "打开一条会话、一个终端、工作区或日程图。",
    tabsIn: "{name} 的标签页",
    newTab: "新建标签页",
    panes: "窗格",
    tooSmall: "窗口太窄，放不下再分一块。",
  },
  terminal: {
    title: "终端",
    open: "打开终端",
    newSession: "新建",
    close: "关闭这条",
    /** Takes a session out of one pane. The process keeps running; this is not how you stop it. */
    hide: "从这个窗格移走",
    hideHint: "会话继续跑，可以再打开",
    end: "结束会话",
    endConfirm: "结束后里面跑着的进程会一起停。",
    stop: "停止",
    empty: "还没有终端会话。",
    emptyHint: "新建一条，在这台机器上跑你自己的命令。",
    needsWorkspace: "先在设置里选择工作区目录。",
    unavailable: "终端不可用：原生助手没有就位。",
    exited: "已结束",
    exitedWith: "已结束 · 退出码 {code}",
    interrupted: "已中断",
    dropped: "输出过快，已丢弃 {bytes} 字节",
    survivesWindow: "关窗不停，退出才停",
    keys: "控制键",
  },
  stream: {
    empty: "还没有消息。",
    messageIndex: "消息位置",
    messageIndexEmpty: "（无文字）",
    loadEarlier: "载入更早的消息",
    loadingEarlier: "正在载入…",
    loadingHistory: "正在载入这段对话…",
    mentionUnresolved: "这个 @ 没有匹配到群成员",
    streaming: "正在写",
    replying: "回复中",
    continueInterrupt: "继续",
    continueInterruptHint: "从中断处继续，不重试断掉的那一下",
    continueUnreachableHint: "从断开处继续",
    ask: "提问",
    reply: "回复",
    approval: "批准",
    allowOnce: "允许一次",
    alwaysAllow: "Always allow",
    deny: "拒绝",
    allowed: "已允许",
    denied: "已拒绝",
    voided: "已作废",
    endpointKey: "端点密钥",
    endpointKeyHintAdd: "允许一次前必须粘贴密钥。不会写进转录。",
    endpointKeyHintEdit: "该端点还没有密钥则必须贴；已有密钥可留空保留。不会写进转录。",
    endpointKeyEmpty: "填写端点密钥。",
    mcpAuth: "Authorization",
    mcpAuthHintAdd: "允许一次前必须粘贴 Authorization（可含 Bearer）。不会写进转录。",
    mcpAuthHintEdit: "已有 Authorization 可留空保留；要换就重贴。不会写进转录。",
    mcpAuthEmpty: "填写 Authorization。",
    artifactPreview: "产物预览",
    artifactLoading: "正在打开文件…",
    artifactMissing: "文件不在了",
    artifactOpenSystem: "用系统打开",
    artifactReveal: "在 Finder 显示",
    artifactDirectory: "文件夹",
    artifactOpenUnavailable: "开发态浏览器里请下载；系统打开只在 App 窗里。",
    artifactResize: "拖动调整预览宽度",
    artifactTree: "引用的文件",
    artifactTreeLoading: "正在加载文件列表…",
    artifactTreeFailed: "文件列表加载失败。",
    artifactTreeEmpty: "暂无引用的文件。",
    artifactBundle: "工作区文件",
    artifactBundleCount: (count: number) => `${count} 个文件`,
    artifactWrap: "换行",
    artifactSource: "源码",
    artifactRendered: "预览",
    artifactFind: "查找",
    artifactFindNext: "下一个",
    artifactFindPrev: "上一个",
    artifactMatchCase: "区分大小写",
    artifactRegexp: "正则",
    artifactByWord: "整词",
    artifactNoMatch: "无匹配",
    workspaceExplorer: "工作区",
    workspaceTruncated: "这一层文件太多，只列出前一部分。",
    workspaceEmpty: "这个文件夹是空的。",
    workspacePickFile: "从左侧打开一个文件。",
    artifactSave: "保存",
    artifactSaving: "保存中",
    artifactSaveFailed: "没能保存。",
    artifactSaveConflict: "文件已被修改，未覆盖；请先复制你的编辑，再重新打开文件。",
    artifactDirtyTitle: "有未保存的更改",
    artifactDirtyBody: "切换文件或关闭预览会丢掉还没保存的修改。",
    artifactDiscard: "丢弃",
    artifactTreeResize: "拖动调整文件树宽度",
  },
  composer: {
    idle: "没有进行中的轮。",
    fork: "另开一轮",
    send: "发送",
    stop: "Stop",
    stopGeneration: "停止回复",
    waitingHint: "回复结束后可发送 · Shift+Enter 换行",
    attach: "添加附件",
    attachLimit: "远程附件上限 50 MiB。",
    removeAttachment: "移除附件",
    removeMention: "移除提及",
    redirect: (name: string) => `发送会改道眼前这轮（${name}）。已做完的不回滚。`,
    forkLive: (name: string) => `发送会另开一轮；${name} 当前轮继续。`,
  },
  chat: {
    botBadge: "BOT",
    today: "今天",
    yesterday: "昨天",
    copyMessage: "复制内容",
    copyMessageId: "复制消息 ID",
    copied: "已复制",
    copyCode: "复制代码",
    commandActivity: "命令执行",
    commandFailed: "失败",
    replyMessage: "回复",
    cancelReply: "取消回复",
    replyToYou: "回复你",
    replyTo: (name: string) => `回复 ${name}`,
    replyToDeleted: "回复已删除的 Bot",
    replyTime: (time: string) => `耗时 ${time}`,
    replyPrompt: "发消息给",
    openAssociatedFileTree: "打开关联的文件树",
    noAssociatedFiles: "无关联文件",
    showTrace: "看这件事",
    thinking: "思考与生成中",
    scrollToBottom: "回到底部",
    lockedNotice: "此会话为只读（参与的 Bot 已归档或删除）",
    groupLockedNotice: "此群聊已归档，处于只读状态",
    botBotLockedNotice: "Bot↔Bot 私聊只读：你不是参与者，只能看",
    botDmOpened: "开了私聊",
    sendHint: "Enter ↵ 发送 · Shift+Enter 换行",
    sendHintShortcut: "发送（Enter）",
    mentionTooltip: "提及 Bot (@)",
    suggestNext: "建议下一步",
    forkTooltip: "开启后发送将分叉新轮次，不改道进行中的任务",
    forkBadge: "分叉",
    emptySessionPrompt1: "你可以帮我做什么？",
    emptySessionPrompt2: "查看当前工作区有哪些文件",
    emptySessionPrompt3: "开始一个新任务",
    membersCount: (count: number) => `${count} 位成员`,
    online: "空闲",
    segmentPart: (index: number) => `第 ${index} 段`,
    segmentCount: (count: number) => `${count} 段输出`,
    messageCount: (count: number) => `${count} 条消息`,
  },
  thread: {
    title: "线程",
    none: "点一条带回复的消息。",
    reply: "回复",
  },
  routes: {
    title: "模型选择记录",
    topAction: "模型选择记录",
    subtitle: (session: string, count: number) => `${session} · ${count} 轮`,
    subtitleFiltered: (session: string, shown: number, total: number) =>
      `${session} · ${shown} / ${total} 轮`,
    none: "还没有模型选择记录。",
    loading: "正在读取…",
    hint: "开轮时给这条消息挑了哪个模型和思考等级，这轮怎么结束，以及你后来对模型说过什么。",
    filterSearchPlaceholder: "搜索 Bot、模型、原因、复盘或反馈…",
    filterSearchAria: "搜索模型选择记录",
    filterClearSearch: "清除搜索",
    filterClearAll: "清空筛选",
    filterFacetClear: "清除",
    facetOutcome: "结果",
    facetBot: "Bot",
    facetModel: "模型",
    facetKind: "类别",
    facetEndpoint: "端点",
    filterFeedback: "有反馈",
    filterBlamed: "归咎模型",
    filterRetired: "已退出",
    filterNoMatch: "没有匹配的记录",
    filterNoMatchHint: "没有符合当前筛选的模型选择记录。",
    endpoint: "端点",
    jump: "跳到触发消息",
    thinkingPrefix: "思考",
    kindLabel: "消息类别",
    thinking: { none: "无", low: "低", medium: "中", high: "高", xhigh: "极高", max: "最大", minimal: "最低" },
    pickReason: "为什么选它",
    reviewTitle: "复盘",
    reviewRounds: (rounds: number) => `改了 ${rounds} 轮`,
    execution: (hops: number, errors: number) => `${hops} 跳 · ${errors} 次工具错误`,
    effectFollowed: "已照做",
    effectCleaner: "纠正变少",
    effectRetired: "已退出：照做两次仍无改善",
    effectUnused: "未用于选路",
    learnedMemory: (label: string) => `记下了：${label}`,
    learnedSkill: (label: string) => `改了技能：${label}`,
    learnedNone: "没有可留的结论",
    fault: {
      model: "模型的问题",
      task: "事情本身难",
      prompt: "需求没说清",
      none: "没有不满"
    },
    direction: {
      stronger: "该更强",
      lighter: "该更轻",
      faster: "该更快",
      cheaper: "该更便宜",
      same: "不用动"
    },
    feedbackTitle: "模型反馈",
    feedbackCount: (count: number) => `${count} 条模型反馈`,
    outcome: {
      live: "进行中",
      completed: "完成",
      failed: "补全失败",
      stopped: "被 Stop",
      redirected: "改道",
      interrupted: "中断"
    },
    signature: {
      coding: "写代码",
      writing: "写作",
      reasoning: "推理",
      simple: "简单",
      general: "通用"
    },
    failReason: {
      unreachable: "连不上端点",
      first_byte: "等不到第一条回复",
      stalled: "回复中途没有下文了",
      busy: "端点忙",
      refused: "端点拒绝了这次补全",
      endpoint_error: "端点出错",
      incomplete: "回复不完整",
      no_model: "没有可用的模型",
      stuck: "卡住了，很久没有任何进展",
      crashed: "运行时出错"
    }
  },
  trace: {
    outputFull: "全屏",
    outputExitFull: "退出全屏",
    zoomIn: "放大",
    zoomOut: "缩小",
    zoomFit: "适应宽度",
    title: "这件事",
    topAction: "经过",
    none: "还没有可以看的事。",
    loading: "正在读取…",
    failed: "读不出来。",
    retry: "重试",
    open: "进行中",
    closed: "已结束",
    filter: "只看还在进行的，和交出了产物的",
    passed: (count: number) => `${count} 人旁观`,
    wokenBy: (name: string) => `由${name}的上一轮叫醒`,
    sessionGroup: (name: string) => `群 · ${name}`,
    sessionDirect: (name: string) => `与${name}的私聊`,
    sessionUnknown: "另一个会话",
    waitingApproval: "在等批准",
    waitingAsk: "在等回答",
    jump: "跳到这一轮",
    output: "产物",
    outputOf: (name: string) => `${name}交出`,
    outputMissing: "这个文件不在了。",
    outputPlain: "这种文件在流程图里看不了内容。",
    outputOpen: "用系统打开",
    outputClose: "收起",
    resize: "调整窗口大小",
    status: {
      running: "进行中",
      waiting_approval: "在等批准",
      waiting_ask: "在等回答",
      completed: "完成",
      redirected: "改道",
      interrupted: "中断",
      stopped: "停下"
    }
  },
  detail: {
    titleGroup: "群组设置",
    titleBot: "Bot 设置",
    backToSections: "返回",
    botTabBasics: "基础信息",
    botTabSkills: "技能",
    botTabRoutines: "日程",
    botTabMemory: "记忆",
    botTabActions: "操作",
    botBasics: "Bot 基础信息",
    sessionActions: "会话操作",
    dangerZone: "危险区域",
    backToGroup: "返回群组设置",
    backToBot: "返回 Bot 设置",
    judgements: "判断日志",
    none: "还没有判断。",
    pullIn: "拉入",
    remove: "移出",
    members: "成员",
    saveFailed: "没能保存。",
    clearHistory: "清空历史",
    clearHistoryBody: "清空后，本会话的消息、轮次和判断都去掉。会话还在。进行中的轮会 Stop。",
    confirmClearHistory: "确认清空",
    deleteGroup: "删除群聊",
    deleteGroupBody: "删除后，这个群和里面的消息、轮次都去掉。名册上的 Bot 还在。",
    confirmDeleteGroup: "确认删除",
    cancel: "取消",
  },
  onboarding: {
    welcome: "欢迎使用 Real Bot",
    subtitle: "本机 macOS 单人 Agent 协作空间。初次使用，请先完成工作区与模型服务的基础设置，即可开始与 Bot 协作。",
    step1Title: "工作区目录",
    step2Title: "模型端点与密钥",
    step3Title: "模型选择与默认",
    stepWorkspace: "1. 配置文件工作区",
    workspaceDesc: "Bot 的文件读写和命令执行都限制在这个目录里。点选本机文件夹，不能手填路径；不存在时保存会自动创建，也可一键使用推荐目录 ~/real-bot-workspace。",
    useDefaultWorkspace: "使用推荐目录 (~/real-bot-workspace)",
    stepProvider: "2. 配置 AI 模型服务",
    providerDesc: "连接一个 OpenAI 兼容端点。之后可在设置里再添加更多端点。",
    stepModelsDesc: "勾选当前要启用的模型名单，并指定用于日常任务补全的默认模型。",
    presetCustom: "自定义",
    presetOpenAI: "OpenAI",
    presetDeepSeek: "DeepSeek",
    presetOpenRouter: "OpenRouter",
    presetOllama: "Ollama (本地)",
    nextStep: "下一步",
    prevStep: "上一步",
    step1Next: "下一步：配置模型服务",
    step2Next: "下一步：选择模型",
    submit: "完成配置，开始使用",
    skip: "稍后在设置中配置，直接进入应用",
    reopenGuide: "基础设置未完成，点击打开引导页",
  },
  notifications: {
    title: "通知",
    tabActionable: "待处理",
    tabUnread: "未读",
    tabAll: "全部",
    markAllRead: "全部标为已读",
    acknowledged: "我知道了",
    viewApproval: "查看批准",
    viewAsk: "查看问题",
    viewFailure: "查看原因",
    viewReply: "查看回复",
    needsApproval: "等你批准",
    needsAsk: "等你回答",
    readPrefix: "已读 · ",
    readNeedsApproval: "已读 · 等你批准",
    readNeedsAsk: "已读 · 等你回答",
    workResults: "工作结果",
    needsYou: "等你处理",
    newReply: "有新回复",
    newRoutineResult: "有新结果",
    turnInterrupted: "本轮未完成",
    executionFailed: "执行失败",
    emptyActionable: "暂时没有需要你处理的事项",
    emptyUnread: "都看过了",
    emptyAll: "暂无通知",
    connecting: "连接执行 Mac 后读取通知",
    hostUnreachable: "执行主机不可达",
    retry: "重试",
    targetMissing: "原内容已不存在",
    targetProcessed: "这项请求已处理",
    retentionNotice: "较早通知已整理，可到会话查看",
    sectionCategories: "通知类别",
    categoriesSubtitle: "控制哪些事件会触发系统通知；会话列表仍标出待处理状态",
    catApproval: "待我批准",
    catAsk: "待我回答",
    catFailure: "任务失败",
    catInterrupted: "任务中断",
    catReply: "面向你的回复",
    catRoutineResult: "日程结果",
    quietHours: "免打扰",
    quietHoursSubtitle: "在指定时间段内抑制系统通知，会话列表照常标出待处理状态",
    quietHoursEnabled: "开启免打扰",
    quietHoursStart: "开始时间",
    quietHoursEnd: "结束时间",
    quietHoursTimeZone: "时区",
    quietHoursEqualTimes: "开始时间与结束时间不能相同",
    sessionMute: "静音普通回复",
    deviceNotifications: "本设备系统通知",
    deviceSubtitle: "管理当前设备接收系统通知与推送的偏好",
    deviceEnable: "开启这台设备的系统通知",
    deviceEnabled: "已开启",
    deviceDisabled: "已关闭",
    deviceSound: "声音",
    devicePreview: "内容预览",
    previewGeneric: "仅通用提示",
    previewExcerpt: "普通回复摘要",
    deviceBadge: "应用图标角标",
    sendTest: "发送测试通知",
    testSubmitting: "正在发送测试…",
    testSent: "系统已接受测试通知",
    testQueued: "测试通知已入队，等待本机投递槽；系统尚未展示",
    testRemoteQueued: "测试通知已入队，等待执行 Mac 向推送服务投递；手机接收尚未确认",
    testRemoteAccepted: "推送服务已接受测试通知；请查看手机系统通知",
    testRemoteTimeout: "执行 Mac 连接推送服务超时，已安排重试；请检查 Mac 的网络与代理",
    testDeliveryGated: "本机系统通知未合格，不能发送测试",
    nativeTestDisabled: "本机系统横幅未合格，测试通知不可用",
    permissionDenied: "系统通知已被阻止。待处理状态仍标在对应会话上。",
    iosInstallRequired: "添加到主屏幕后，从该图标打开并开启通知",
    needsRepair: "需要重新开启此设备通知",
    repairButton: "重新开启",
    browserAllowedUnregistered: "浏览器已允许，尚未连接执行 Mac 完成登记",
    pushUpgrading: "推送升级中",
    pushUnsupported: "不支持此推送服务",
    remoteGated: "远控激活仍关闭",
    unconfirmedClose: "关闭尚未确认，仍可能收到通知",
    localOnlyClose: "此浏览器已停止订阅，主机停用尚未确认",
    hostOnlyClose: "执行 Mac 已停止新推送；浏览器订阅清理未完成",
    upgradeRequired: "更新执行 Mac 后使用通知设置",
    tabTakeoverNotice: "此设备已在另一标签页连接",
    tabTakeoverButton: "接管连接",
    tabTakeoverTimeout: "接管超时，请关闭旧标签页",
    askEnded: "此问题已结束，答案尚未发送",
    askEndedReadOnly: "此问题已结束",
  },
};

const en: CopyShape<typeof zh> = {
  routines: {
    title: "Routines", add: "Add routine", edit: "Edit routine", empty: "This Bot has no routines yet.",
    owner: "Owning Bot", name: "Title", instruction: "Task instruction", frequency: "Repeat", daily: "Daily", weekly: "Weekly",
    time: "Time (24-hour)", weekdays: "Weekdays", days: { mon: "Mon", tue: "Tue", wed: "Wed", thu: "Thu", fri: "Fri", sat: "Sat", sun: "Sun" },
    daysShort: { mon: "Mo", tue: "Tu", wed: "We", thu: "Th", fri: "Fr", sat: "Sa", sun: "Su" },
    workdays: "Workdays", weekend: "Weekend", allDays: "All",
    zone: "Runs in the execution Mac’s local time zone, not this browser’s time zone.",
    availability: "The Mac must be awake with the runtime available. On recovery, only the latest missed occurrence is caught up. Archived Bots do not run routines.",
    enabled: "Enabled", active: "Enabled", paused: "Paused", pause: "Pause", resume: "Resume", save: "Save routine", cancel: "Cancel", busy: "Saving…",
    remove: "Delete routine", deleteBody: "This routine will no longer trigger. Deleting it does not stop work already started.", confirm: "Confirm delete",
    nameRequired: "Enter a title.", timeInvalid: "Enter a valid HH:MM time (00:00–23:59).", daysRequired: "Choose at least one weekday.",
    failed: "Could not save the routine. Please retry.", invalid: "Invalid routine fields. Check the title, time and weekdays.", missing: "This routine has been deleted.", conflict: "This routine changed elsewhere. Your draft has not overwritten it; load the latest version before editing again.",
    reload: "Load latest version", disconnected: "The connection changed; the save result is unconfirmed. Check routines after reconnecting. Nothing is retried automatically.",
    unknown: "The original request result is unknown; it may already be saved. Nothing is retried automatically.",
    pending: "The original request is still pending. Your edited draft was not sent. This is not a revision conflict.",
    retry: "Retry original request", retryHint: "Retry uses the original request’s content and ID, not your later draft edits.",
    retired: "The original request is no longer pending. Retry did not send later draft edits; check the list and reopen the routine before saving a retained draft.",
  },
  calendar: {
    title: "Routine calendar",
    open: "Routine calendar",
    empty: "No routines on the roster yet.",
    phoneReadOnly: "You can look here. To change a time, drag it on the desktop, or open the Bot’s routines.",
    projectionHint: "A block is the rule unfolded, not a record of each run. A marked due time is only trustworthy on this Mac.",
    lastFiredHostOnly: "Due marks show only on the execution Mac. The clock on a block is that Mac’s local time.",
    detail: "Routine",
    lastFired: "This is the latest time it was due.",
    noInstruction: "No task instruction.",
    filter: "Roster",
    filterAll: "All",
    filterSearch: "Search name or duties",
    filterNoMatch: "No matching Bots.",
    filterShow: "Show",
    filterHide: "Hide",
    filterReset: "Show all",
    agendaEmpty: "Nothing in this range.",
  },
  common: {
    you: "You",
    close: "Close",
    back: "Back",
    copyImage: "Copy image",
    copyImageFailed: "Couldn’t copy the image",
    updateReady: "A new version is ready",
    updateReload: "Reload",
  },
  disconnected: {
    message: "Can't reach the runtime",
    host: "Execution host unreachable",
    connecting: "Connecting to the runtime…",
    connectingHost: "Connecting to the execution host…",
    retry: "Try again",
    hostHint: "Work still runs only on the awake Mac. Commands are not queued offline.",
  },
  remote: {
    pairTitle: "Pair this device",
    pairLead: "Use the pairing payload shown on the Mac to enroll this device. A person must confirm the new device at the Mac.",
    pairHint: "Paste only the pairing content from the Mac. Do not open it as a URL or put it in a query string or log.",
    pairPaste: "Pairing payload",
    pairSubmit: "Submit and wait for Mac confirmation",
    pairWaiting: "Sent to the Mac; waiting for local confirmation…",
    pairExpired: "The pairing window expired. Open a new pair on the Mac.",
    pairRejected: "Pairing was rejected or cancelled.",
    pairInvalid: "That pairing payload is invalid.",
    pairUrl: "Pairing payload cannot be a URL or query string.",
    fingerprint: "Host signing fingerprint",
    experimental: "Experimental remote access. Public pairing stays default-off; S-rev, G-uv and physical L1 have not passed.",
    uvNeeded: "High-risk actions need WebAuthn user verification on this device. There is no click-to-confirm fallback.",
    uvFailed: "WebAuthn registration failed. Ordinary chat still works; high-risk actions stay disabled.",
    uvRegister: "Register user verification on this device",
    draftConfirm: "An unsent draft survived reconnect. Confirm before sending; nothing is replayed automatically.",
    draftSend: "Confirm send draft",
    draftDiscard: "Discard draft",
    statusOff: "Remote is off",
    statusUnavailable: "Native credentials unavailable",
    statusGated: "Remote activation remains gated",
    statusConnecting: "Connecting to the relay",
    statusOnline: "Remote online",
    statusDisconnected: "Remote disconnected",
    statusMismatch: "Remote trust mismatch",
    devices: (n: number) => `${n} paired devices`,
    noOfflineQueue: "There is no offline command queue. Unknown results look up the same request receipt instead of sending a new id.",
    maintenance: "Maintenance",
    maintenanceLead: "Status, redacted diagnostics and controlled restart stay on the encrypted session. Timeouts and disconnects never auto-force.",
    version: (v: string) => `Version ${v}`,
    modeWindow: "Window supervised",
    modeStandalone: "Independent runtime",
    modeNone: "No supervisor",
    restartAvailable: "The current supervisor can relaunch",
    restartUnavailable: "Restart is unavailable: the window is gone and independent mode is off. No background job is installed.",
    drainRunning: "Running",
    drainWaiting: (n: number) => `Draining; ${n} live turns remaining`,
    drainDrained: "Drained",
    drainForced: "Force-interrupted",
    refreshStatus: "Refresh status",
    downloadDiagnostics: "Download redacted diagnostics",
    drainRestart: "Drain then restart",
    forceRestart: "Force-interrupt and restart",
    forceWarn: "Force interrupts live turns and does not replay tools. A fresh user verification is required; click-to-confirm is not enough.",
    forceConfirm: "Confirm force restart",
    stopRuntime: "Stop runtime",
    stopWarn: "Stop writes the latch then exits. The supervisor will not relaunch until the stop latch is cleared on the Mac.",
    stopConfirm: "Confirm stop",
    revokeOther: "Revoke other devices",
    revokeConfirm: (name: string) => `Confirm revoke ${name}`,
    noOtherDevices: "No other devices to revoke.",
    reconnectHint: "Reconnect only queries status and the same request receipt. It does not start another restart.",
    errorDraining: "The runtime is draining; new requests are rejected.",
    errorUnavailable: "No supervisor is available for a remote restart.",
    errorCancelled: "The drain wait was cancelled. Nothing was auto-forced.",
    errorUv: "Fresh WebAuthn user verification is required.",
    errorUnknown: "The result is unknown. Look up the same receipt instead of minting a new id.",
    push: "Pending-item push",
    pushDesc: "Generic reminders only: “Real Bot has pending items”. A click opens the messenger on the chat list; it never approves or sends commands. Deny or expiry does not drop pending items. iOS needs 16.4+ home screen; the physical G-push gate has not passed.",
    pushDenied: "Notifications are blocked. Pending state stays on the conversation.",
    pushUnsupported: "This browser does not support Web Push.",
    pushFailed: "Could not update the push subscription.",
    hostPair: "Pair a device",
    hostPairPaste: "Open the relay address on the device and paste this into its pairing screen. It carries a one-time secret, expires in ten minutes, and does not belong in logs or chats.",
    hostPairFingerprint: "Check the host fingerprint the device shows against this one.",
    hostPairEmpty: "No device is paired with this Mac yet.",
    connectedDevices: "Connected devices",
    connectedDevicesEmpty: "No connected devices yet.",
    lastActive: (value: string) => `Last active ${value}`,
    lastActiveUnknown: "Last active time unknown",
    removeDevice: "Remove device",
    removeDeviceConfirm: (name: string) => `Confirm remove ${name}`,
    deviceActionFailed: "The device action failed. Try again.",
    hostPairRetry: "Open a new window",
    hostPairWaiting: "Waiting for the device to submit…",
    hostPairArrived: (name: string) => `${name} is asking to pair.`,
    hostPairCompare: "This has to match what the device is showing.",
    hostPairApprove: "Approve this device",
    hostPairDone: "Paired. The device can reach this Mac now.",
    hostPairExpired: "The pairing window expired; open a new one.",
    hostPairFailed: "Could not open a pairing window.",
  },
  sidebar: {
    roster: "Roster",
    pinned: "Pinned",
    pinnedEmpty: "No pinned chats",
    pin: "Pin",
    unpin: "Unpin",
    expand: "Expand",
    collapse: "Collapse",
    search: "Search sessions, messages, files, routines",
    searchShort: "Search",
    searchClear: "Clear search",
    emptySearch: "No hits.",
    searchKindBot: "Bot",
    searchKindSession: "Session",
    searchKindMessage: "Message",
    searchKindRoutine: "Routine",
    routineUnavailable: "The routine or its Bot is no longer available to open. Historical routines are retained.",
    searchKindFile: "File",
    groups: "Groups",
    youBot: "You ↔ Bot",
    botBot: "Bot ↔ Bot",
    botBotSource: (title: string) => `From ${title}`,
    botBotSourceRoot: (immediate: string, root: string) => `From ${immediate} (root: ${root})`,
    botBotSourceUnknown: "Source unknown",
    botBotSourceMissing: "Source is gone",
    botBotMore: (n: number) => `${n} more`,
    settings: "Settings",
    notifications: "Notifications",
    addBot: "New bot",
    addGroup: "New group",
    createMenu: "New",
    botName: "Name",
    botDuties: "Duties",
    botBoundaries: "Boundaries",
    botAvatar: "Avatar",
    botAvatarRefresh: "Randomize",
    botAvatarStyle: "Style",
    botAvatarCustom: "Upload image",
    botAvatarCustomHint: "PNG, JPEG, or WebP, up to 8 MB.",
    botAvatarInvalidType: "Pick a PNG, JPEG, or WebP image.",
    botAvatarTooLarge: "That image is too large.",
    botAvatarDecodeFailed: "Couldn’t read that image.",
    botModel: "Model",
    botModelDefault: "Automatic",
    botModelInvalid: "Pick a model from the list.",
    botThinking: "Thinking level",
    botModelAutoHint: "Automatic: the app picks a model per message and the thinking level that goes with it. Picking a model means picking its thinking level too.",
    botThinkingHint: "Only the levels this model supports. Changing the model moves the pin to the new model's default.",
    botThinkingInvalid: "Pick a thinking level this model supports.",
    thinkingLevels: { none: "None", low: "Low", medium: "Medium", high: "High", xhigh: "Extra high", max: "Max", minimal: "Minimal" },
    autoSaving: "Saving…",
    autoSaved: "Saved automatically",
    autoSaveHint: "Changes save automatically",
    skills: "Skills",
    skillsEmpty: "No skills yet.",
    skillAdd: "Add skill",
    skillName: "Name",
    skillDescription: "When to use",
    skillBody: "How to do it",
    skillUses: "Uses MCP",
    skillUsesPlaceholder: "Server names, comma-separated; optional",
    skillUsesHint: "Name the MCP servers the body calls. Servers not connected this turn are marked in the skill catalog so the Bot does not force the body.",
    skillEnabled: "Enabled",
    skillNameEmpty: "Enter a name.",
    skillDescriptionEmpty: "Enter when to use it.",
    skillBodyEmpty: "Enter how to do it.",
    skillNameConflict: "That name is already used.",
    skillDelete: "Delete skill",
    skillDeleteBody: "After this, the Bot will not see the skill on the next hop.",
    skillConfirmDelete: "Confirm delete",
    skillEdit: "Edit skill",
    skillSave: "Save skill",
    skillCancel: "Cancel",
    memories: "Memory",
    memoriesEmpty: "No memories yet. The Bot writes down what it needs across sessions; you can edit or delete.",
    memoryHint: "The Bot records what to remember across sessions and reads these on every hop. Correct or disable one that is wrong or out of date.",
    memorySubject: "About",
    memoryBody: "What it remembers",
    memoryEnabled: "Enabled",
    memoryEdit: "Edit memory",
    memorySave: "Save",
    memoryCancel: "Cancel",
    memoryDelete: "Delete memory",
    memoryDeleteBody: "After this, the Bot will not see this memory on its next hop.",
    memoryConfirmDelete: "Confirm delete",
    memorySubjectEmpty: "Enter what this memory is about.",
    memoryBodyEmpty: "Enter what it remembers.",
    memorySubjectConflict: "There is already a memory about that.",
    memoryFormedIn: (where: string) => `Formed in ${where}`,
    learningNoneYet: "No later task of this kind yet",
    learningLater: (later: number, shorter: number) =>
      `${later} later ${later === 1 ? "task" : "tasks"} of this kind, ${shorter} shorter`,
    memoryOriginMissing: "Source is gone",
    memoryEditedByYou: "Edited by you",
    memoryJump: "Jump to the message it came from",
    memoryShowAll: (n: number) => `Show all ${n}`,
    memoryCollapse: "Collapse",
    memoryAgeToday: "Today",
    memoryAgeThisWeek: "This week",
    memoryAgeWeeks: (n: number) => `${n}w ago`,
    memoryAgeMonths: (n: number) => `${n}mo ago`,
    groupName: "Group name",
    groupMembers: "Members",
    groupMembersPlaceholder: "Pick two or more bots",
    groupMemberSearch: "Keep searching",
    groupMemberNoMatch: "No bot matches.",
    groupMemberNone: "No bots in the roster yet.",
    groupMemberRemove: "Remove",
    create: "Save",
    nameEmpty: "Enter a name.",
    dutiesEmpty: "Enter duties.",
    boundariesEmpty: "Enter boundaries.",
    nameConflict: "That name is already used.",
    groupNameEmpty: "Enter a group name.",
    membersTooFew: "Pick at least two bots.",
    saveFailed: "Couldn’t save.",
    profile: "Profile",
    viewInfo: "View info",
    clearHistory: "Clear history",
    archive: "Archive",
    unarchive: "Unarchive",
    restore: "Restore",
    archiveBody: "Move the bot into Archived. Sessions stay; history is kept.",
    restoreBody: "Put this bot back on the roster.",
    delete: "Delete",
    deleteBody: "This removes the bot from the roster. Sessions stay, titled Deleted. Workspace files are not touched.",
    confirmDelete: "Confirm delete",
    cancel: "Cancel",
    statusRunning: "Thinking",
    statusReplying: "Replying",
    statusWaitingApproval: "Approval",
    statusWaitingAsk: "Waiting input",
    statusFailed: "Didn't finish",
    statusInterrupted: "Interrupted",
    statusIdle: "Idle",
    unread: "Unread",
    noMessages: "No messages",
    archivedSessions: "Archived sessions",
    archivedEmpty: "No archived sessions",
    backToSessions: "Back to sessions",
    resize: "Drag to resize the session list",
    mainNavigation: "Main navigation",
    sessions: "Chats",
    workspace: "Workspace",
    tools: "More",
    workspaceUnset: "Choose a workspace folder in Settings first.",
    updateAvailable: "Update available",
  },
  settings: {
    title: "Settings",
    tabGeneral: "General",
    tabPreferences: "Preferences",
    tabNotifications: "Notifications",
    tabModels: "Models",
    tabMcp: "MCP Servers",
    tabAbout: "About",
    sectionWorkspace: "Workspace Directory",
    workspaceSubtitle: "Root folder where bot file operations and commands run",
    workspaceConfigured: "Configured",
    workspaceUnsetNotice: "Unset",
    workspaceSecurityBoundary: "Workspace Security Boundary",
    sectionPreferences: "Preferences",
    preferencesSubtitle: "Personalize appearance, language, and launch behavior",
    themeDesc: "Color theme for the interface",
    languageDesc: "Display language for the interface",
    launchDesc: "Start Real Bot automatically when logging into macOS",
    aboutSubtitle: "Local macOS single-user agent workspace",
    remoteSection: "Remote (experimental)",
    remoteSubtitle: "Browser pairing identity lives in IndexedDB only. Chat, snapshots, drafts, commands and files are not persisted.",
    sectionEndpoint: "Endpoint & Auth",
    sectionModels: "Model Configuration",
    sectionMcpServers: "Configured Servers",
    sectionMcpAdd: "Add MCP Server",
    wizardHint:
      "Setup is the empty settings state: workspace path, plus at least one endpoint URL and key. Each endpoint has its own model list. It does not steal the transcript.",
    wizardIncomplete: "Workspace path, endpoint, and key are not all set.",
    providerName: "Name",
    providerAdd: "Add endpoint",
    providerEdit: "Edit endpoint",
    providerEmpty: "No model endpoints yet.",
    providerDelete: "Delete",
    providerDeleteBody:
      "Bots pinned to this endpoint revert to an empty pin. If this is the default, the first remaining endpoint becomes default.",
    providerConfirmDelete: "Confirm delete",
    providerCancel: "Cancel",
    providerDefault: "Default",
    providerSetDefault: "Set as default",
    providerModelCount: (count: number) => (count === 1 ? "1 model" : `${count} models`),
    providersHint: "Pick the model this endpoint uses day to day. Connection and the model list are edited apart.",
    providerConnection: "Connection",
    providerModels: "Models",
    providerDefaultModel: (name: string) => `Default model ${name}`,
    providerPickDefault: "Make this the endpoint's default model",
    providerNoDefault: "No default yet. Enable a model, then click its row.",
    providerNameEmpty: "Enter a name.",
    workspace: "Workspace",
    workspaceChoose: "Choose folder",
    workspaceChange: "Change folder",
    workspaceUnsetValue: "No folder selected",
    workspacePickerUnavailable: "Choose a folder in the desktop app; the browser dev server cannot open the system dialog.",
    workspaceHostOnly: "The workspace root is set on the Mac window, not over remote.",
    workspaceBrowseRemote: "Browse directories on the execution Mac. Changing the root still needs a person at the Mac.",
    workspaceAuthorizeMac: "Authorize file access once on the Mac, then retry.",
    workspaceUseFolder: "Use this folder",
    workspaceUp: "Up",
    workspaceConfirmRoot: "Changing the workspace root requires confirmation on the Mac.",
    fileLimitRemote: "Remote attachments and workspace downloads are capped at 50 MiB. The local window is not.",
    fileLimitHit: "This file exceeds the 50 MiB remote cap.",
    copyRelpath: "Copy relative path",
    downloadFile: "Download",
    endpoint: "Endpoint",
    endpointKey: "Endpoint key",
    keySet: "Configured",
    keyUnset: "Not configured",
    language: "Language",
    localeZh: "中文",
    localeEn: "English",
    theme: "Appearance",
    themeSystem: "System",
    themeLight: "Light",
    themeDark: "Dark",
    launch: "Launch at login",
    independentRuntime: "Independent runtime",
    independentRuntimeDesc: "Keep the local runtime alive with a LaunchAgent after quitting the window. Off by default; stays disabled until the sealed-native gate passes.",
    independentRuntimeGated: "The native runtime is unsealed (G-pack not passed), so an independent job cannot be installed. The window still supervises by default.",
    independentRuntimeDev: "Development mode never installs a LaunchAgent.",
    independentRuntimeBrowser: "Turn this on in the desktop app; the browser cannot install a local job.",
    independentRuntimeConfirmEnable: "Enable independent runtime",
    independentRuntimeConfirmEnableBody:
      "Live turns drain first, then the runtime is handed to a user-domain LaunchAgent. Failure stays Down; the window does not silently resume spawning. Quitting the desktop no longer stops work.",
    independentRuntimeConfirmDisable: "Disable independent runtime",
    independentRuntimeConfirmDisableBody:
      "Window supervision is restored first, then the LaunchAgent is unloaded. Turning this off without the desktop open stops remote work until you open Real Bot on the Mac.",
    independentRuntimeWaiting: "Waiting for live turns to finish…",
    independentRuntimeForce: "Force interrupt and hand off",
    independentRuntimeCancel: "Cancel",
    independentRuntimeFailed: "The independent runtime did not start. Open Real Bot on the Mac or retry.",
    independentRuntimeConfirm: "Confirm",
    save: "Save",
    workspaceEmpty: "Choose a local folder.",
    workspaceInvalid: "Use an absolute local path; it cannot be a file. Missing folders are created.",
    endpointEmpty: "Enter the endpoint URL.",
    endpointInvalid: "The endpoint must be an http or https URL.",
    keyEmpty: "Paste the endpoint key.",
    models: "Available models",
    modelsEmpty: "Enter at least one model name.",
    modelsFetch: "Fetch models",
    modelsFetching: "Fetching...",
    modelsFetchFailed: "Couldn't fetch models; you can add names by hand.",
    modelsRefetch: "Refetch",
    modelsCounts: (enabled: number, available: number) => `${enabled} enabled · ${available} available`,
    modelsAutoFetchHint: "The model list is fetched automatically once the endpoint URL and key are filled in.",
    modelsFetchingHint: "Fetching the model list from the endpoint…",
    modelsEmptyHint: "No models yet. If fetching fails you can add model names by hand.",
    modelsFilterAll: "All",
    modelsFilterEnabled: "Enabled",
    modelsEnabledEmpty: "Nothing enabled yet; switch to All and tick some.",
    modelsAddManual: "Add a model name by hand",
    modelsAddManualPlaceholder: "A name the endpoint accepts",
    modelsAddConfirm: "Add",
    modelCustomBadge: "Added by hand",
    modelAttrsToggle: (name: string) => `Routing attributes for ${name}`,
    modelPriceTitle: "Only used when the app picks a model; not shown in spend.",
    modelStrengthsAdd: "Custom",
    modelStrengthsAddPlaceholder: "e.g. vision",
    modelStrengthRemove: (tag: string) => `Remove ${tag}`,
    modelsSelectTitle: "Select models to use",
    modelsSearchPlaceholder: "Search models...",
    modelsSelectAll: "Select all",
    modelsDeselectAll: "Deselect all",
    modelsManualToggle: "Edit text directly",
    modelsListToggle: "Back to list",
    modelsAddCustom: "Add custom model",
    defaultModel: "Default model",
    defaultModelEmpty: "Pick a default model.",
    defaultModelInvalid: "The default model must be on the available list.",
    modelAttrsEmptyFilter: "No matching models.",
    modelAttrsDefaultBadge: "Default",
    modelPrice: "Price",
    modelPriceHint: "Optional, e.g. 1.5",
    modelThinking: "Thinking levels",
    modelThinkingAdd: "Custom",
    modelThinkingAddPlaceholder: "e.g. xhigh",
    modelStrengths: "Strengths",
    saveFailed: "Couldn’t save.",
    mcp: "MCP",
    mcpEmpty: "No MCP servers yet.",
    mcpEdit: "Edit MCP server",
    mcpSearch: "Search names, transports or connections",
    mcpClearSearch: "Clear search",
    mcpNoResults: "No matching MCP servers.",
    mcpName: "Name",
    mcpTransport: "Transport",
    mcpTransportStdio: "stdio",
    mcpTransportHttp: "HTTP",
    mcpCommand: "command",
    mcpArgs: "args",
    mcpUrl: "URL",
    mcpHeaders: "headers",
    mcpAuth: "Authorization",
    mcpAuthHint: "Bearer token. Written only to the keychain, never listed.",
    mcpEnabled: "Enabled",
    mcpAdd: "Add",
    mcpConfirmAdd: "Confirm add",
    mcpConfirmEdit: "Confirm connection",
    mcpCancel: "Cancel",
    mcpDelete: "Delete",
    mcpNameEmpty: "Enter a name.",
    mcpCommandEmpty: "Enter a command.",
    mcpUrlEmpty: "Enter the MCP URL.",
    mcpUrlInvalid: "The URL must be http or https.",
    mcpMustConfirm: "Adding and changing command / args / URL / headers must be confirmed. There is no Always allow.",
    mcpUsageNote: "Usage note",
    mcpUsageNotePlaceholder: "What this server is for, when to use it, when not to",
    mcpUsageNoteHint:
      "Shown to every Bot on every hop, above the server's own instructions. The name and note save as you edit, with no confirmation, and survive connection changes; leave the note empty to rely on the server's own text.",
    sectionAbout: "About",
    version: (version: string) => `Version ${version}`,
    checkUpdates: "Check for updates",
    checkingUpdates: "Checking...",
    upToDate: "You’re on the latest version.",
    updateAvailable: (version: string) => `Version ${version} is available.`,
    updateDownload: "Download update",
    updateInstall: "Download and install",
    updateInstallHint: "Downloads in the app and restarts itself once it is in place — no installer to walk through.",
    updateDownloading: "Downloading",
    updateVerifying: "Checking the download",
    updateInstalling: "Replacing the app",
    updateRestarting: "Installed — restarting",
    updateInstallCancel: "Cancel",
    updateInstallRetry: "Try again",
    updateInstallFailedDownload: "Couldn’t download this version.",
    updateInstallFailedVerify: "The download wasn’t this version, so it was thrown away.",
    updateInstallFailedInstall: "Couldn’t replace the app. The installed copy is untouched.",
    updateInstallFailedReadOnly: "This copy can’t be replaced from here. Download it in the browser and replace it yourself.",
    updateInstallFailedNotInstalled: "This build runs from source, so there is no app to replace.",
    updateInstallFailedOther: "The update didn’t install. The installed copy is untouched.",
    updateNotes: "Release notes",
    updateChanges: "What changed in this version",
    updateIgnore: "Skip this version",
    updateFailed: "Couldn’t check for updates.",
  },
  top: {
    groupSettings: "Group settings",
    botSettings: "Bot settings",
    pickSession: "Pick a session",
    emptyRoster: "The roster is empty. Use + on the roster row to create a bot.",
    members: "Here",
    presenceOpen: "open, read-only",
    profile: "Profile",
    archived: "Archived",
    deleted: "Deleted",
    pin: "Pin",
    pinned: "Pinned",
    unpin: "Unpin",
    moreActions: "More conversation actions",
  },
  pane: {
    title: "Pane",
    splitRight: "Split right",
    splitDown: "Split down",
    close: "Close pane",
    closeTab: "Close tab",
    float: "Float this pane",
    dock: "Dock back into the layout",
    equalise: "Even out",
    reset: "Reset layout",
    resize: "Resize pane",
    junction: "Move junction",
    empty: "Nothing open in this pane",
    emptyHint: "Open a conversation, a terminal, the workspace or the calendar.",
    tabsIn: "Tabs in {name}",
    newTab: "New tab",
    panes: "Panes",
    tooSmall: "The window is too narrow to divide again.",
  },
  terminal: {
    title: "Terminal",
    open: "Open terminal",
    newSession: "New",
    close: "Close this one",
    hide: "Remove from this pane",
    hideHint: "The session keeps running; you can open it again",
    end: "End session",
    endConfirm: "Ending it stops whatever is running inside.",
    stop: "Stop",
    empty: "No terminal sessions yet.",
    emptyHint: "Open one and run your own commands on this machine.",
    needsWorkspace: "Choose a workspace folder in settings first.",
    unavailable: "Terminals are unavailable: the native helper is not in place.",
    exited: "Finished",
    exitedWith: "Finished · exit {code}",
    interrupted: "Interrupted",
    dropped: "Output outran the reader; {bytes} bytes dropped",
    survivesWindow: "Keeps running when the window closes; Quit ends it",
    keys: "Control keys",
  },
  stream: {
    empty: "No messages yet.",
    messageIndex: "Message index",
    messageIndexEmpty: "(no text)",
    loadEarlier: "Load earlier messages",
    loadingEarlier: "Loading…",
    loadingHistory: "Loading this conversation…",
    mentionUnresolved: "This @ matches no member here",
    streaming: "streaming",
    replying: "replying",
    continueInterrupt: "Continue",
    continueInterruptHint: "Continue from the interruption without retrying the cut action",
    continueUnreachableHint: "Continue from where the connection was lost",
    ask: "ask",
    reply: "Reply",
    approval: "approval",
    allowOnce: "Allow once",
    alwaysAllow: "Always allow",
    deny: "Deny",
    allowed: "Allowed",
    denied: "Denied",
    voided: "Voided",
    endpointKey: "Endpoint key",
    endpointKeyHintAdd: "Paste the key before Allow once. It is not written into the transcript.",
    endpointKeyHintEdit: "Required if this endpoint has no key yet; leave blank to keep the current key. It is not written into the transcript.",
    endpointKeyEmpty: "Paste the endpoint key.",
    mcpAuth: "Authorization",
    mcpAuthHintAdd: "Paste Authorization (Bearer allowed) before Allow once. It is not written into the transcript.",
    mcpAuthHintEdit: "Leave blank to keep the current Authorization; paste a new value to rotate it. It is not written into the transcript.",
    mcpAuthEmpty: "Paste Authorization.",
    artifactPreview: "Artifact preview",
    artifactLoading: "Opening file…",
    artifactMissing: "File is gone",
    artifactOpenSystem: "Open with system",
    artifactReveal: "Show in Finder",
    artifactDirectory: "Folder",
    artifactOpenUnavailable: "In the browser, download instead. Open with system is only in the app window.",
    artifactResize: "Drag to resize preview",
    artifactTree: "Cited files",
    artifactTreeLoading: "Loading files…",
    artifactTreeFailed: "Could not load files.",
    artifactTreeEmpty: "No cited files yet.",
    artifactBundle: "Workspace files",
    artifactBundleCount: (count: number) => (count === 1 ? "1 file" : `${count} files`),
    artifactWrap: "Wrap",
    artifactSource: "Source",
    artifactRendered: "Preview",
    artifactFind: "Find",
    artifactFindNext: "Next",
    artifactFindPrev: "Previous",
    artifactMatchCase: "Match case",
    artifactRegexp: "Regexp",
    artifactByWord: "Whole word",
    artifactNoMatch: "No matches",
    workspaceExplorer: "Workspace",
    workspaceTruncated: "This folder has too many entries; only the first part is listed.",
    workspaceEmpty: "This folder is empty.",
    workspacePickFile: "Open a file from the left.",
    artifactSave: "Save",
    artifactSaving: "Saving",
    artifactSaveFailed: "Couldn’t save.",
    artifactSaveConflict: "The file changed and was not overwritten. Copy your edits, then reopen the file.",
    artifactDirtyTitle: "Unsaved changes",
    artifactDirtyBody: "Switching files or closing the preview discards unsaved edits.",
    artifactDiscard: "Discard",
    artifactTreeResize: "Drag to resize the file tree",
  },
  composer: {
    idle: "No live turn.",
    fork: "Fork a turn",
    send: "Send",
    stop: "Stop",
    stopGeneration: "Stop reply",
    waitingHint: "Send after the reply ends · Shift+Enter for newline",
    attach: "Add attachment",
    attachLimit: "Remote attachments are limited to 50 MiB.",
    removeAttachment: "Remove attachment",
    removeMention: "Remove mention",
    redirect: (name: string) => `Send redirects the live turn (${name}). Done work is not rolled back.`,
    forkLive: (name: string) => `Send forks a new turn; ${name}'s current turn keeps running.`,
  },
  chat: {
    botBadge: "BOT",
    today: "Today",
    yesterday: "Yesterday",
    copyMessage: "Copy message",
    copyMessageId: "Copy message ID",
    copied: "Copied",
    copyCode: "Copy code",
    commandActivity: "Commands",
    commandFailed: "failed",
    replyMessage: "Reply",
    cancelReply: "Cancel reply",
    replyToYou: "Replying to you",
    replyTo: (name: string) => `Replying to ${name}`,
    replyToDeleted: "Replying to a deleted Bot",
    replyTime: (time: string) => `${time}`,
    replyPrompt: "Message",
    openAssociatedFileTree: "Open associated file tree",
    noAssociatedFiles: "No associated files",
    showTrace: "Show this job",
    thinking: "Thinking & generating",
    scrollToBottom: "Scroll to bottom",
    lockedNotice: "This session is read-only (participating bots are archived or deleted)",
    groupLockedNotice: "This group is archived and is read-only",
    botBotLockedNotice: "This Bot↔Bot direct is read-only: you are not a participant",
    botDmOpened: "Opened directs",
    sendHint: "Enter to send · Shift+Enter for newline",
    sendHintShortcut: "Send (Enter)",
    mentionTooltip: "Mention a bot (@)",
    suggestNext: "Suggested next",
    forkTooltip: "When enabled, send will fork a new turn without redirecting live work",
    forkBadge: "Fork",
    emptySessionPrompt1: "What can you help me with?",
    emptySessionPrompt2: "List files in the workspace",
    emptySessionPrompt3: "Start a new task",
    membersCount: (count: number) => `${count} members`,
    online: "Idle",
    segmentPart: (index: number) => `Part ${index}`,
    segmentCount: (count: number) => `${count} outputs`,
    messageCount: (count: number) => `${count} messages`,
  },
  thread: {
    title: "Thread",
    none: "Open a message that has replies.",
    reply: "Reply",
  },
  routes: {
    title: "Model choice log",
    topAction: "Model log",
    subtitle: (session: string, count: number) =>
      `${session} · ${count} ${count === 1 ? "turn" : "turns"}`,
    subtitleFiltered: (session: string, shown: number, total: number) =>
      `${session} · ${shown} of ${total} ${total === 1 ? "turn" : "turns"}`,
    none: "No model choices yet.",
    loading: "Loading…",
    hint: "Which model and thinking level each turn started on, how the turn ended, and what you said about the model afterwards.",
    filterSearchPlaceholder: "Search bot, model, reason, review, or notes…",
    filterSearchAria: "Search model choice log",
    filterClearSearch: "Clear search",
    filterClearAll: "Clear filters",
    filterFacetClear: "Clear",
    facetOutcome: "Outcome",
    facetBot: "Bot",
    facetModel: "Model",
    facetKind: "Kind",
    facetEndpoint: "Endpoint",
    filterFeedback: "Feedback",
    filterBlamed: "Model blamed",
    filterRetired: "Retired",
    filterNoMatch: "No matching turns",
    filterNoMatchHint: "No turns match the current filters or search.",
    endpoint: "Endpoint",
    jump: "Jump to the triggering message",
    thinkingPrefix: "Thinking",
    kindLabel: "Message kind",
    thinking: { none: "None", low: "Low", medium: "Medium", high: "High", xhigh: "Extra high", max: "Max", minimal: "Minimal" },
    pickReason: "Why this one",
    reviewTitle: "Review",
    reviewRounds: (rounds: number) => `${rounds} ${rounds === 1 ? "round" : "rounds"} of corrections`,
    execution: (hops: number, errors: number) =>
      `${hops} ${hops === 1 ? "hop" : "hops"} · ${errors} tool ${errors === 1 ? "error" : "errors"}`,
    effectFollowed: "Followed",
    effectCleaner: "Fewer corrections",
    effectRetired: "Retired: followed twice without improving",
    effectUnused: "Not used for routing",
    learnedMemory: (label: string) => `Remembered: ${label}`,
    learnedSkill: (label: string) => `Updated skill: ${label}`,
    learnedNone: "Nothing worth keeping",
    fault: {
      model: "The model",
      task: "The job itself",
      prompt: "The request",
      none: "No complaint"
    },
    direction: {
      stronger: "go stronger",
      lighter: "go lighter",
      faster: "go faster",
      cheaper: "go cheaper",
      same: "leave it"
    },
    feedbackTitle: "Model feedback",
    feedbackCount: (count: number) => `${count} model ${count === 1 ? "note" : "notes"}`,
    outcome: {
      live: "Still running",
      completed: "Completed",
      failed: "Completion failed",
      stopped: "Stopped",
      redirected: "Redirected",
      interrupted: "Interrupted"
    },
    signature: {
      coding: "Coding",
      writing: "Writing",
      reasoning: "Reasoning",
      simple: "Simple",
      general: "General"
    },
    failReason: {
      unreachable: "Couldn’t reach the endpoint",
      first_byte: "No first reply arrived",
      stalled: "The reply stalled mid-stream",
      busy: "Endpoint is busy",
      refused: "Endpoint refused this completion",
      endpoint_error: "Endpoint error",
      incomplete: "Incomplete reply",
      no_model: "No model is configured",
      stuck: "It stopped making progress",
      crashed: "The runtime errored"
    }
  },
  trace: {
    outputFull: "Full screen",
    outputExitFull: "Leave full screen",
    zoomIn: "Zoom in",
    zoomOut: "Zoom out",
    zoomFit: "Fit width",
    title: "This job",
    topAction: "Trace",
    none: "Nothing to show yet.",
    loading: "Loading…",
    failed: "Couldn’t load this.",
    retry: "Retry",
    open: "In progress",
    closed: "Closed",
    filter: "Only what’s still going, and what handed a file over",
    passed: (count: number) => `${count} watched`,
    wokenBy: (name: string) => `Woken by ${name}`,
    sessionGroup: (name: string) => `Group · ${name}`,
    sessionDirect: (name: string) => `Direct with ${name}`,
    sessionUnknown: "Another conversation",
    waitingApproval: "Waiting for approval",
    waitingAsk: "Waiting for an answer",
    jump: "Jump to this turn",
    output: "Handed over",
    outputOf: (name: string) => `From ${name}`,
    outputMissing: "This file is gone.",
    outputPlain: "This file has nothing to show here.",
    outputOpen: "Open with the system",
    outputClose: "Put away",
    resize: "Resize window",
    status: {
      running: "In progress",
      waiting_approval: "Waiting for approval",
      waiting_ask: "Waiting for an answer",
      completed: "Done",
      redirected: "Redirected",
      interrupted: "Interrupted",
      stopped: "Stopped"
    }
  },
  detail: {
    titleGroup: "Group settings",
    titleBot: "Bot settings",
    backToSections: "Back",
    botTabBasics: "Basics",
    botTabSkills: "Skills",
    botTabRoutines: "Routines",
    botTabMemory: "Memory",
    botTabActions: "Actions",
    botBasics: "Bot basics",
    sessionActions: "Actions",
    dangerZone: "Danger Zone",
    backToGroup: "Back to group settings",
    backToBot: "Back to bot settings",
    judgements: "Judgement log",
    none: "No judgements yet.",
    pullIn: "Pull in",
    remove: "Remove",
    members: "Members",
    saveFailed: "Couldn’t save.",
    clearHistory: "Clear history",
    clearHistoryBody: "This removes the session’s messages, turns, and judgements. The session stays. Live turns are stopped.",
    confirmClearHistory: "Confirm clear",
    deleteGroup: "Delete group",
    deleteGroupBody: "This removes the group and its messages and turns. Bots on the roster stay.",
    confirmDeleteGroup: "Confirm delete",
    cancel: "Cancel",
  },
  onboarding: {
    welcome: "Welcome to Real Bot",
    subtitle: "Your local macOS single-user agent workspace. Please complete the workspace and model provider setup to start collaborating with bots.",
    step1Title: "Workspace",
    step2Title: "Endpoint & Auth",
    step3Title: "Models",
    stepWorkspace: "1. Configure Workspace Directory",
    workspaceDesc: "Bot file and shell access stay inside this folder. Pick a local folder; the path cannot be typed. Missing folders are created when you save; you can also use the recommended ~/real-bot-workspace.",
    useDefaultWorkspace: "Use recommended (~/real-bot-workspace)",
    stepProvider: "2. Configure AI Model Provider",
    providerDesc: "Connect an OpenAI-compatible endpoint. You can add more endpoints later in Settings.",
    stepModelsDesc: "Select the models you wish to enable, and set the default model for agent turns.",
    presetCustom: "Custom",
    presetOpenAI: "OpenAI",
    presetDeepSeek: "DeepSeek",
    presetOpenRouter: "OpenRouter",
    presetOllama: "Ollama (Local)",
    nextStep: "Next",
    prevStep: "Back",
    step1Next: "Next: Model Provider",
    step2Next: "Next: Select Models",
    submit: "Save & Get Started",
    skip: "Skip for now, enter app",
    reopenGuide: "Setup incomplete, click to open setup guide",
  },
  notifications: {
    title: "Notifications",
    tabActionable: "Actionable",
    tabUnread: "Unread",
    tabAll: "All",
    markAllRead: "Mark all as read",
    acknowledged: "Got it",
    viewApproval: "View approval",
    viewAsk: "View question",
    viewFailure: "View reason",
    viewReply: "View reply",
    needsApproval: "Needs your approval",
    needsAsk: "Waiting for your answer",
    readPrefix: "Read · ",
    readNeedsApproval: "Read · Needs your approval",
    readNeedsAsk: "Read · Waiting for your answer",
    workResults: "Work results",
    needsYou: "Needs your attention",
    newReply: "New reply",
    newRoutineResult: "New routine result",
    turnInterrupted: "Turn interrupted",
    executionFailed: "Execution failed",
    emptyActionable: "No items need your attention right now",
    emptyUnread: "All caught up",
    emptyAll: "No notifications",
    connecting: "Connect to execution Mac to load notifications",
    hostUnreachable: "Execution host unreachable",
    retry: "Retry",
    targetMissing: "Original content no longer exists",
    targetProcessed: "This request has already been processed",
    retentionNotice: "Earlier notifications have been cleaned up; check session for details",
    sectionCategories: "Notification Categories",
    categoriesSubtitle: "Choose which events trigger system notifications; the chat list still shows pending state",
    catApproval: "Approvals",
    catAsk: "Questions",
    catFailure: "Failures",
    catInterrupted: "Interrupted turns",
    catReply: "Replies to you",
    catRoutineResult: "Routine results",
    quietHours: "Quiet Hours",
    quietHoursSubtitle: "Suppress system notifications during scheduled hours; the chat list still shows pending state",
    quietHoursEnabled: "Enable quiet hours",
    quietHoursStart: "Start time",
    quietHoursEnd: "End time",
    quietHoursTimeZone: "Time zone",
    quietHoursEqualTimes: "Start and end times cannot be equal",
    sessionMute: "Mute regular replies",
    deviceNotifications: "Device System Notifications",
    deviceSubtitle: "Manage system notification and push preferences for this device",
    deviceEnable: "Enable system notifications for this device",
    deviceEnabled: "Enabled",
    deviceDisabled: "Disabled",
    deviceSound: "Sound",
    devicePreview: "Preview content",
    previewGeneric: "Generic prompt only",
    previewExcerpt: "Excerpt for regular replies",
    deviceBadge: "App icon badge",
    sendTest: "Send test notification",
    testSubmitting: "Sending test…",
    testSent: "System accepted the test notification",
    testQueued: "Test notification queued for the local delivery slot; the system has not presented it",
    testRemoteQueued: "Test notification queued for the execution Mac to send to the push service; phone receipt is unconfirmed",
    testRemoteAccepted: "Push service accepted the test notification; check your phone's system notifications",
    testRemoteTimeout: "The execution Mac timed out connecting to the push service. A retry is scheduled; check the Mac's network and proxy settings",
    testDeliveryGated: "Native system notifications are unqualified; a test cannot be sent",
    nativeTestDisabled: "Native banners are unqualified; test notifications stay unavailable",
    permissionDenied: "System notifications blocked. Pending state stays on the conversation.",
    iosInstallRequired: "Add to Home Screen, open from that icon, and enable notifications",
    needsRepair: "Need to re-enable notifications for this device",
    repairButton: "Re-enable",
    browserAllowedUnregistered: "Browser allowed; not yet registered with execution Mac",
    pushUpgrading: "Push notifications upgrading",
    pushUnsupported: "Push service not supported",
    remoteGated: "Remote activation remains off",
    unconfirmedClose: "Disable unconfirmed; notifications may still arrive",
    localOnlyClose: "Browser unsubscribed; host disable unconfirmed",
    hostOnlyClose: "Execution Mac stopped new pushes; browser subscription cleanup incomplete",
    upgradeRequired: "Update execution Mac to use notification settings",
    tabTakeoverNotice: "This device is already connected in another tab",
    tabTakeoverButton: "Take over connection",
    tabTakeoverTimeout: "Takeover timed out; please close the other tab",
    askEnded: "This question has ended; answer was not sent",
    askEndedReadOnly: "This question has ended",
  },
};

export const COPY = { zh, en };

export type Copy = CopyShape<typeof zh>;

export function copyFor(locale: Locale): Copy {
  return locale === "en" ? en : zh;
}

/** Known thinking-level labels, falling back to the endpoint's own token. */
export function thinkingLevelLabel(
  labels: Record<string, string> | undefined,
  level: string,
): string {
  return labels?.[level] ?? level;
}
