import type { Locale } from "@real-bot/protocol";

/** Locked in 设置里「壳不是囚笼」写哪一句. Do not paraphrase. */
export const JAIL_COPY = {
  zh: "工作区壳把当前目录放在工作区并在启动前检查看得见的路径，不是操作系统囚笼。",
  en: "The workspace shell puts the current directory in the workspace and checks paths visible in the command before start; it is not an operating-system jail.",
} as const;

type CopyShape<T> = T extends (...args: infer A) => string
  ? (...args: A) => string
  : T extends object
    ? { [K in keyof T]: CopyShape<T[K]> }
    : string;

const zh = {
  common: {
    you: "你",
    close: "关闭",
  },
  disconnected: {
    message: "连不上运行时",
  },
  sidebar: {
    roster: "名册",
    pinned: "置顶",
    pinnedEmpty: "暂无置顶会话",
    pin: "置顶",
    unpin: "取消置顶",
    expand: "展开",
    collapse: "收起",
    search: "搜索会话、消息、文件、日程",
    emptySearch: "没有命中。",
    searchKindBot: "Bot",
    searchKindSession: "会话",
    searchKindMessage: "消息",
    searchKindRoutine: "日程",
    searchKindFile: "文件",
    groups: "群",
    youBot: "你 ↔ Bot",
    botBot: "Bot ↔ Bot",
    settings: "设置",
    addBot: "新建 Bot",
    addGroup: "新建群",
    botName: "名字",
    botDuties: "职责",
    botBoundaries: "边界",
    botAvatar: "头像",
    botAvatarRefresh: "换一个",
    botAvatarStyle: "风格",
    botAvatarCustom: "上传图片",
    botAvatarCustomHint: "PNG、JPEG 或 WebP，最大 8 MB。",
    botAvatarInvalidType: "请选 PNG、JPEG 或 WebP 图片。",
    botAvatarTooLarge: "图片太大了。",
    botAvatarDecodeFailed: "没能读这张图片。",
    botModel: "模型",
    botModelDefault: "用默认模型",
    botModelInvalid: "挑名单里的一个模型。",
    botThinking: "思考等级",
    botThinkingAuto: "自动",
    botThinkingHint: "自动：每条消息由应用挑。钉一档就固定用它；模型不支持时仍由应用挑。",
    botThinkingInvalid: "挑这个模型支持的思考等级。",
    thinkingLevels: { none: "不思考", low: "低", medium: "中", high: "高" },
    autoSaving: "保存中…",
    autoSaved: "已自动保存",
    autoSaveHint: "改动自动保存",
    skills: "技能",
    skillsEmpty: "还没有技能。",
    skillAdd: "添加技能",
    skillName: "名称",
    skillDescription: "何时用",
    skillBody: "怎么干",
    skillUses: "依赖的 MCP",
    skillUsesPlaceholder: "服务器名，逗号分隔；可留空",
    skillUsesHint: "写正文里要调的 MCP 服务器名。本轮没连上的会在技能目录里标出来，Bot 就不会硬套正文。",
    skillEnabled: "启用",
    skillNameEmpty: "填写一个名称。",
    skillDescriptionEmpty: "填写何时用。",
    skillBodyEmpty: "填写怎么干。",
    skillNameConflict: "这个名称已经有了。",
    skillDelete: "删除技能",
    skillDeleteBody: "删除后，这个 Bot 下一跳就看不见这条技能。",
    skillConfirmDelete: "确认删除",
    skillEdit: "编辑技能",
    skillSave: "保存技能",
    skillCancel: "取消",
    groupName: "群名",
    groupMembers: "成员",
    create: "保存",
    nameEmpty: "填写一个名字。",
    dutiesEmpty: "填写职责。",
    boundariesEmpty: "填写边界。",
    nameConflict: "这个名字已经有了。",
    groupNameEmpty: "填写一个群名。",
    membersTooFew: "至少挑两个 Bot。",
    saveFailed: "没能保存。",
    profile: "人设",
    viewInfo: "查看信息",
    clearHistory: "清除历史",
    archive: "归档",
    unarchive: "取消归档",
    restore: "恢复",
    delete: "删除",
    deleteBody: "删除后，这个 Bot 从名册去掉。会话还在，标题会变成「已删除」。工作区文件不动。",
    confirmDelete: "确认删除",
    cancel: "取消",
    statusRunning: "思考中",
    statusReplying: "回复中",
    statusWaitingApproval: "待审批",
    statusWaitingAsk: "待回复",
    statusIdle: "空闲",
    unread: "未读",
    noMessages: "还没有消息",
    archivedSessions: "已归档会话",
    archivedEmpty: "没有已归档的会话",
    backToSessions: "返回会话列表",
    resize: "拖动调整会话列表宽度",
    workspace: "工作区",
    workspaceUnset: "先在设置里填工作区路径。",
    updateAvailable: "有新版本",
  },
  settings: {
    title: "设置",
    tabGeneral: "通用",
    tabModels: "模型服务",
    tabMcp: "MCP 扩展",
    sectionWorkspace: "工作区目录",
    sectionPreferences: "基础偏好",
    sectionEndpoint: "端点与鉴权",
    sectionModels: "模型配置",
    sectionMcpServers: "已配置服务器",
    sectionMcpAdd: "添加 MCP 服务器",
    wizardHint: "向导就是设置的空态：工作区路径、至少一个端点的 URL 和密钥齐了即完成。每个端点有自己的模型名单。不抢主转录。",
    wizardIncomplete: "工作区路径、端点和密钥还没齐。",
    providerName: "名称",
    providerAdd: "添加端点",
    providerEdit: "编辑端点",
    providerEmpty: "还没有模型端点。",
    providerDelete: "删除",
    providerDeleteBody: "删除后，钉了这个端点的 Bot 会改回空钉。若删的是默认端点，默认会换成剩下的第一个。",
    providerConfirmDelete: "确认删除",
    providerCancel: "取消",
    providerDefault: "默认",
    providerSetDefault: "设为默认",
    providerSave: "保存这个端点",
    providerModelCount: (count: number) => (count === 1 ? "1 个模型" : `${count} 个模型`),
    providersHint: "可以添加多个 OpenAI 兼容端点。Bot 可指定其中一个的模型；空则用默认端点的默认模型。",
    providerNameEmpty: "填写一个名称。",
    workspace: "工作区",
    endpoint: "端点",
    endpointKey: "端点密钥",
    keySet: "已配置",
    keyUnset: "未配置",
    language: "语言",
    localeZh: "中文",
    localeEn: "English",
    theme: "外观",
    themeSystem: "跟随系统",
    themeLight: "亮色",
    themeDark: "暗色",
    launch: "登录启动",
    save: "保存",
    workspaceEmpty: "填写一个本机目录。",
    workspaceInvalid: "需要本机绝对路径；不能是文件。目录不存在时会自动创建。",
    endpointEmpty: "填写端点 URL。",
    endpointInvalid: "端点必须是 http 或 https 的 URL。",
    keyEmpty: "粘贴端点密钥。",
    models: "可用模型",
    modelsEmpty: "至少填一个模型名。",
    modelsFetch: "获取模型",
    modelsFetching: "获取中...",
    modelsFetchFailed: "未能获取模型列表，可手动添加模型名。",
    modelsRefetch: "重新获取",
    modelsCounts: (enabled: number, available: number) => `已启用 ${enabled} · 可用 ${available}`,
    modelsAutoFetchHint: "填好端点 URL 和密钥后会自动获取模型列表。",
    modelsFetchingHint: "正在从端点获取模型列表…",
    modelsEmptyHint: "还没有模型。获取不到时可以手动添加模型名。",
    modelsFilterAll: "全部",
    modelsFilterEnabled: "已启用",
    modelsEnabledEmpty: "还没有启用的模型，切到「全部」勾选。",
    modelsAddManual: "手动添加模型名",
    modelsAddManualPlaceholder: "端点认的模型名",
    modelsAddConfirm: "添加",
    modelCustomBadge: "手动添加",
    modelAttrsToggle: (name: string) => `${name} 的决策属性`,
    modelPriceTitle: "只给应用挑模型用，不进花费展示。",
    modelStrengthsAdd: "自定义",
    modelStrengthsAddPlaceholder: "例如 vision",
    modelStrengthRemove: (tag: string) => `移除 ${tag}`,
    modelsSelectTitle: "选择要启用的模型",
    modelsSearchPlaceholder: "搜索模型...",
    modelsSelectAll: "全选",
    modelsDeselectAll: "全不选",
    modelsManualToggle: "直接编辑文本",
    modelsListToggle: "返回列表选择",
    modelsAddCustom: "添加自定义模型",
    defaultModel: "默认模型",
    defaultModelEmpty: "挑一个默认模型。",
    defaultModelInvalid: "默认模型必须在可用名单里。",
    modelAttrsEmptyFilter: "没有匹配的模型。",
    modelAttrsDefaultBadge: "默认",
    modelPrice: "价格",
    modelPriceHint: "可选，如 1.5",
    modelThinking: "思考等级",
    modelStrengths: "擅长领域",
    saveFailed: "没能保存。",
    mcp: "MCP",
    mcpEmpty: "还没有 MCP 服务器。",
    mcpEdit: "编辑 MCP 服务器",
    mcpSearch: "搜索名称、传输或连接地址",
    mcpClearSearch: "清除搜索",
    mcpNoResults: "没有匹配的 MCP 服务器。",
    mcpName: "名",
    mcpTransport: "传输",
    mcpTransportStdio: "stdio",
    mcpTransportHttp: "HTTP",
    mcpCommand: "command",
    mcpArgs: "args",
    mcpUrl: "URL",
    mcpHeaders: "headers",
    mcpAuth: "Authorization",
    mcpAuthHint: "Bearer token。只写进钥匙串，不进列表。",
    mcpEnabled: "启用",
    mcpAdd: "添加",
    mcpConfirmAdd: "确认添加",
    mcpSave: "保存这台",
    mcpConfirmEdit: "确认改连接",
    mcpCancel: "取消",
    mcpDelete: "删除",
    mcpNameEmpty: "填写一个名。",
    mcpCommandEmpty: "填写 command。",
    mcpUrlEmpty: "填写 MCP URL。",
    mcpUrlInvalid: "URL 必须是 http 或 https。",
    mcpMustConfirm: "新增和改 command / args / URL / headers 必须确认，没有 Always allow。",
    mcpUsageNote: "用法备注",
    mcpUsageNotePlaceholder: "这台用来做什么、什么时候用、什么时候不要用",
    mcpUsageNoteHint:
      "写给所有 Bot 看，每一跳都排在服务器自带说明前面。改它不用确认，改连接也不会丢；留空就只用服务器自带的说明。",
    sectionAbout: "关于",
    version: (version: string) => `版本 ${version}`,
    checkUpdates: "检查更新",
    checkingUpdates: "检查中...",
    upToDate: "已是最新版本。",
    updateAvailable: (version: string) => `有新版本 ${version} 可用。`,
    updateDownload: "下载更新",
    updateNotes: "查看发布说明",
    updateIgnore: "忽略此版本",
    updateFailed: "没能检查更新。",
  },
  top: {
    groupSettings: "群组设置",
    botSettings: "Bot 设置",
    pickSession: "选择一个会话",
    emptyRoster: "名册是空的。点名册那一行的 + 建 Bot。",
    members: "在场",
    presenceOpen: "可打开",
    profile: "人设",
    archived: "已归档",
    deleted: "已删除",
    pin: "置顶",
    pinned: "已置顶",
    unpin: "取消置顶",
  },
  stream: {
    empty: "还没有消息。",
    mentionUnresolved: "这个 @ 没有匹配到群成员",
    streaming: "正在写",
    replying: "回复中",
    continueInterrupt: "继续",
    continueInterruptHint: "从中断处继续，不重试断掉的那一下",
    ask: "提问",
    reply: "回复",
    approval: "批准",
    allowOnce: "允许一次",
    alwaysAllow: "Always allow",
    deny: "拒绝",
    allowed: "已允许",
    denied: "已拒绝",
    voided: "已作废",
    endpointKey: "端点密钥",
    endpointKeyHintAdd: "允许一次前必须粘贴密钥。不会写进转录。",
    endpointKeyHintEdit: "该端点还没有密钥则必须贴；已有密钥可留空保留。不会写进转录。",
    endpointKeyEmpty: "填写端点密钥。",
    mcpAuth: "Authorization",
    mcpAuthHintAdd: "允许一次前必须粘贴 Authorization（可含 Bearer）。不会写进转录。",
    mcpAuthHintEdit: "已有 Authorization 可留空保留；要换就重贴。不会写进转录。",
    mcpAuthEmpty: "填写 Authorization。",
    artifactPreview: "产物预览",
    artifactMissing: "文件不在了",
    artifactOpenSystem: "用系统打开",
    artifactReveal: "在 Finder 显示",
    artifactDirectory: "文件夹",
    artifactOpenUnavailable: "开发态浏览器里请下载；系统打开只在 App 窗里。",
    artifactResize: "拖动调整预览宽度",
    artifactTree: "引用的文件",
    artifactBundle: "工作区文件",
    artifactBundleCount: (count: number) => `${count} 个文件`,
    artifactWrap: "换行",
    artifactSource: "源码",
    artifactRendered: "预览",
    artifactFind: "查找",
    artifactFindNext: "下一个",
    artifactFindPrev: "上一个",
    artifactMatchCase: "区分大小写",
    artifactRegexp: "正则",
    artifactByWord: "整词",
    artifactNoMatch: "无匹配",
    workspaceExplorer: "工作区",
    workspaceTruncated: "这一层文件太多，只列出前一部分。",
    workspaceEmpty: "这个文件夹是空的。",
    workspacePickFile: "从左侧打开一个文件。",
    artifactSave: "保存",
    artifactSaving: "保存中",
    artifactSaveFailed: "没能保存。",
    artifactDirtyTitle: "有未保存的更改",
    artifactDirtyBody: "切换文件或关闭预览会丢掉还没保存的修改。",
    artifactDiscard: "丢弃",
    artifactTreeResize: "拖动调整文件树宽度",
  },
  composer: {
    idle: "没有进行中的轮。",
    fork: "另开一轮",
    send: "发送",
    stop: "Stop",
    stopGeneration: "停止回复",
    waitingHint: "回复结束后可发送 · Shift+Enter 换行",
    attach: "添加附件",
    removeAttachment: "移除附件",
    removeMention: "移除提及",
    redirect: (name: string) => `发送会改道眼前这轮（${name}）。已做完的不回滚。`,
    forkLive: (name: string) => `发送会另开一轮；${name} 当前轮继续。`,
  },
  chat: {
    botBadge: "BOT",
    today: "今天",
    yesterday: "昨天",
    copyMessage: "复制内容",
    copied: "已复制",
    copyCode: "复制代码",
    replyMessage: "回复",
    cancelReply: "取消回复",
    replyToYou: "回复你",
    replyTo: (name: string) => `回复 ${name}`,
    replyToDeleted: "回复已删除的 Bot",
    replyTime: (time: string) => `耗时 ${time}`,
    replyPrompt: "发消息给",
    thinking: "思考与生成中",
    scrollToBottom: "回到底部",
    lockedNotice: "此会话为只读（参与的 Bot 已归档或删除）",
    groupLockedNotice: "此群聊已归档，处于只读状态",
    sendHint: "Enter ↵ 发送 · Shift+Enter 换行",
    sendHintShortcut: "发送（Enter）",
    mentionTooltip: "提及 Bot (@)",
    forkTooltip: "开启后发送将分叉新轮次，不改道进行中的任务",
    forkBadge: "分叉",
    emptySessionPrompt1: "你可以帮我做什么？",
    emptySessionPrompt2: "查看当前工作区有哪些文件",
    emptySessionPrompt3: "开始一个新任务",
    membersCount: (count: number) => `${count} 位成员`,
    online: "空闲",
    segmentPart: (index: number) => `第 ${index} 段`,
    segmentCount: (count: number) => `${count} 段输出`,
    messageCount: (count: number) => `${count} 条消息`,
  },
  thread: {
    title: "线程",
    none: "点一条带回复的消息。",
    reply: "回复",
  },
  detail: {
    titleGroup: "群组设置",
    titleBot: "Bot 设置",
    backToGroup: "返回群组设置",
    backToBot: "返回 Bot 设置",
    judgements: "判断日志",
    none: "还没有判断。",
    saveName: "保存",
    pullIn: "拉入",
    remove: "移出",
    members: "成员",
    saveFailed: "没能保存。",
    clearHistory: "清空历史",
    clearHistoryBody: "清空后，本会话的消息、轮次和判断都去掉。会话还在。进行中的轮会 Stop。",
    confirmClearHistory: "确认清空",
    deleteGroup: "删除群聊",
    deleteGroupBody: "删除后，这个群和里面的消息、轮次都去掉。名册上的 Bot 还在。",
    confirmDeleteGroup: "确认删除",
    cancel: "取消",
  },
  onboarding: {
    welcome: "欢迎使用 Real Bot",
    subtitle: "本机 macOS 单人 Agent 协作空间。初次使用，请先完成工作区与模型服务的基础设置，即可开始与 Bot 协作。",
    step1Title: "工作区目录",
    step2Title: "模型端点与密钥",
    step3Title: "模型选择与默认",
    stepWorkspace: "1. 配置文件工作区",
    workspaceDesc: "Bot 的文件读写和命令执行都限制在这个目录里。不存在时保存会自动创建，推荐用 ~/real-bot-workspace。",
    workspacePlaceholder: "/Users/.../workspace 或 ~/real-bot-workspace",
    useDefaultWorkspace: "使用推荐目录 (~/real-bot-workspace)",
    stepProvider: "2. 配置 AI 模型服务",
    providerDesc: "连接一个 OpenAI 兼容端点。之后可在设置里再添加更多端点。",
    stepModelsDesc: "勾选当前要启用的模型名单，并指定用于日常任务补全的默认模型。",
    presetCustom: "自定义",
    presetOpenAI: "OpenAI",
    presetDeepSeek: "DeepSeek",
    presetOpenRouter: "OpenRouter",
    presetOllama: "Ollama (本地)",
    nextStep: "下一步",
    prevStep: "上一步",
    step1Next: "下一步：配置模型服务",
    step2Next: "下一步：选择模型",
    submit: "完成配置，开始使用",
    skip: "稍后在设置中配置，直接进入应用",
    reopenGuide: "基础设置未完成，点击打开引导页",
  },
};

const en: CopyShape<typeof zh> = {
  common: {
    you: "You",
    close: "Close",
  },
  disconnected: {
    message: "Can't reach the runtime",
  },
  sidebar: {
    roster: "Roster",
    pinned: "Pinned",
    pinnedEmpty: "No pinned chats",
    pin: "Pin",
    unpin: "Unpin",
    expand: "Expand",
    collapse: "Collapse",
    search: "Search sessions, messages, files, routines",
    emptySearch: "No hits.",
    searchKindBot: "Bot",
    searchKindSession: "Session",
    searchKindMessage: "Message",
    searchKindRoutine: "Routine",
    searchKindFile: "File",
    groups: "Groups",
    youBot: "You ↔ Bot",
    botBot: "Bot ↔ Bot",
    settings: "Settings",
    addBot: "New bot",
    addGroup: "New group",
    botName: "Name",
    botDuties: "Duties",
    botBoundaries: "Boundaries",
    botAvatar: "Avatar",
    botAvatarRefresh: "Randomize",
    botAvatarStyle: "Style",
    botAvatarCustom: "Upload image",
    botAvatarCustomHint: "PNG, JPEG, or WebP, up to 8 MB.",
    botAvatarInvalidType: "Pick a PNG, JPEG, or WebP image.",
    botAvatarTooLarge: "That image is too large.",
    botAvatarDecodeFailed: "Couldn’t read that image.",
    botModel: "Model",
    botModelDefault: "Use the default model",
    botModelInvalid: "Pick a model from the list.",
    botThinking: "Thinking level",
    botThinkingAuto: "Auto",
    botThinkingHint: "Auto lets the app pick per message. A pinned level is used whenever the model supports it; otherwise the app picks.",
    botThinkingInvalid: "Pick a thinking level this model supports.",
    thinkingLevels: { none: "None", low: "Low", medium: "Medium", high: "High" },
    autoSaving: "Saving…",
    autoSaved: "Saved automatically",
    autoSaveHint: "Changes save automatically",
    skills: "Skills",
    skillsEmpty: "No skills yet.",
    skillAdd: "Add skill",
    skillName: "Name",
    skillDescription: "When to use",
    skillBody: "How to do it",
    skillUses: "Uses MCP",
    skillUsesPlaceholder: "Server names, comma-separated; optional",
    skillUsesHint: "Name the MCP servers the body calls. Servers not connected this turn are marked in the skill catalog so the Bot does not force the body.",
    skillEnabled: "Enabled",
    skillNameEmpty: "Enter a name.",
    skillDescriptionEmpty: "Enter when to use it.",
    skillBodyEmpty: "Enter how to do it.",
    skillNameConflict: "That name is already used.",
    skillDelete: "Delete skill",
    skillDeleteBody: "After this, the Bot will not see the skill on the next hop.",
    skillConfirmDelete: "Confirm delete",
    skillEdit: "Edit skill",
    skillSave: "Save skill",
    skillCancel: "Cancel",
    groupName: "Group name",
    groupMembers: "Members",
    create: "Save",
    nameEmpty: "Enter a name.",
    dutiesEmpty: "Enter duties.",
    boundariesEmpty: "Enter boundaries.",
    nameConflict: "That name is already used.",
    groupNameEmpty: "Enter a group name.",
    membersTooFew: "Pick at least two bots.",
    saveFailed: "Couldn’t save.",
    profile: "Profile",
    viewInfo: "View info",
    clearHistory: "Clear history",
    archive: "Archive",
    unarchive: "Unarchive",
    restore: "Restore",
    delete: "Delete",
    deleteBody: "This removes the bot from the roster. Sessions stay, titled Deleted. Workspace files are not touched.",
    confirmDelete: "Confirm delete",
    cancel: "Cancel",
    statusRunning: "Thinking",
    statusReplying: "Replying",
    statusWaitingApproval: "Approval",
    statusWaitingAsk: "Waiting input",
    statusIdle: "Idle",
    unread: "Unread",
    noMessages: "No messages",
    archivedSessions: "Archived sessions",
    archivedEmpty: "No archived sessions",
    backToSessions: "Back to sessions",
    resize: "Drag to resize the session list",
    workspace: "Workspace",
    workspaceUnset: "Set a workspace path in Settings first.",
    updateAvailable: "Update available",
  },
  settings: {
    title: "Settings",
    tabGeneral: "General",
    tabModels: "Models",
    tabMcp: "MCP Servers",
    sectionWorkspace: "Workspace Directory",
    sectionPreferences: "Preferences",
    sectionEndpoint: "Endpoint & Auth",
    sectionModels: "Model Configuration",
    sectionMcpServers: "Configured Servers",
    sectionMcpAdd: "Add MCP Server",
    wizardHint:
      "Setup is the empty settings state: workspace path, plus at least one endpoint URL and key. Each endpoint has its own model list. It does not steal the transcript.",
    wizardIncomplete: "Workspace path, endpoint, and key are not all set.",
    providerName: "Name",
    providerAdd: "Add endpoint",
    providerEdit: "Edit endpoint",
    providerEmpty: "No model endpoints yet.",
    providerDelete: "Delete",
    providerDeleteBody:
      "Bots pinned to this endpoint revert to an empty pin. If this is the default, the first remaining endpoint becomes default.",
    providerConfirmDelete: "Confirm delete",
    providerCancel: "Cancel",
    providerDefault: "Default",
    providerSetDefault: "Set as default",
    providerSave: "Save this endpoint",
    providerModelCount: (count: number) => (count === 1 ? "1 model" : `${count} models`),
    providersHint: "You can add multiple OpenAI-compatible endpoints. A bot may pick a model from one of them; blank uses the default endpoint's default model.",
    providerNameEmpty: "Enter a name.",
    workspace: "Workspace",
    endpoint: "Endpoint",
    endpointKey: "Endpoint key",
    keySet: "Configured",
    keyUnset: "Not configured",
    language: "Language",
    localeZh: "中文",
    localeEn: "English",
    theme: "Appearance",
    themeSystem: "System",
    themeLight: "Light",
    themeDark: "Dark",
    launch: "Launch at login",
    save: "Save",
    workspaceEmpty: "Enter a local directory.",
    workspaceInvalid: "Use an absolute local path; it cannot be a file. Missing folders are created.",
    endpointEmpty: "Enter the endpoint URL.",
    endpointInvalid: "The endpoint must be an http or https URL.",
    keyEmpty: "Paste the endpoint key.",
    models: "Available models",
    modelsEmpty: "Enter at least one model name.",
    modelsFetch: "Fetch models",
    modelsFetching: "Fetching...",
    modelsFetchFailed: "Couldn't fetch models; you can add names by hand.",
    modelsRefetch: "Refetch",
    modelsCounts: (enabled: number, available: number) => `${enabled} enabled · ${available} available`,
    modelsAutoFetchHint: "The model list is fetched automatically once the endpoint URL and key are filled in.",
    modelsFetchingHint: "Fetching the model list from the endpoint…",
    modelsEmptyHint: "No models yet. If fetching fails you can add model names by hand.",
    modelsFilterAll: "All",
    modelsFilterEnabled: "Enabled",
    modelsEnabledEmpty: "Nothing enabled yet; switch to All and tick some.",
    modelsAddManual: "Add a model name by hand",
    modelsAddManualPlaceholder: "A name the endpoint accepts",
    modelsAddConfirm: "Add",
    modelCustomBadge: "Added by hand",
    modelAttrsToggle: (name: string) => `Routing attributes for ${name}`,
    modelPriceTitle: "Only used when the app picks a model; not shown in spend.",
    modelStrengthsAdd: "Custom",
    modelStrengthsAddPlaceholder: "e.g. vision",
    modelStrengthRemove: (tag: string) => `Remove ${tag}`,
    modelsSelectTitle: "Select models to use",
    modelsSearchPlaceholder: "Search models...",
    modelsSelectAll: "Select all",
    modelsDeselectAll: "Deselect all",
    modelsManualToggle: "Edit text directly",
    modelsListToggle: "Back to list",
    modelsAddCustom: "Add custom model",
    defaultModel: "Default model",
    defaultModelEmpty: "Pick a default model.",
    defaultModelInvalid: "The default model must be on the available list.",
    modelAttrsEmptyFilter: "No matching models.",
    modelAttrsDefaultBadge: "Default",
    modelPrice: "Price",
    modelPriceHint: "Optional, e.g. 1.5",
    modelThinking: "Thinking levels",
    modelStrengths: "Strengths",
    saveFailed: "Couldn’t save.",
    mcp: "MCP",
    mcpEmpty: "No MCP servers yet.",
    mcpEdit: "Edit MCP server",
    mcpSearch: "Search names, transports or connections",
    mcpClearSearch: "Clear search",
    mcpNoResults: "No matching MCP servers.",
    mcpName: "Name",
    mcpTransport: "Transport",
    mcpTransportStdio: "stdio",
    mcpTransportHttp: "HTTP",
    mcpCommand: "command",
    mcpArgs: "args",
    mcpUrl: "URL",
    mcpHeaders: "headers",
    mcpAuth: "Authorization",
    mcpAuthHint: "Bearer token. Written only to the keychain, never listed.",
    mcpEnabled: "Enabled",
    mcpAdd: "Add",
    mcpConfirmAdd: "Confirm add",
    mcpSave: "Save this server",
    mcpConfirmEdit: "Confirm connection",
    mcpCancel: "Cancel",
    mcpDelete: "Delete",
    mcpNameEmpty: "Enter a name.",
    mcpCommandEmpty: "Enter a command.",
    mcpUrlEmpty: "Enter the MCP URL.",
    mcpUrlInvalid: "The URL must be http or https.",
    mcpMustConfirm: "Adding and changing command / args / URL / headers must be confirmed. There is no Always allow.",
    mcpUsageNote: "Usage note",
    mcpUsageNotePlaceholder: "What this server is for, when to use it, when not to",
    mcpUsageNoteHint:
      "Shown to every Bot on every hop, above the server's own instructions. Saving it needs no confirmation and it survives connection changes; leave it empty to rely on the server's own text.",
    sectionAbout: "About",
    version: (version: string) => `Version ${version}`,
    checkUpdates: "Check for updates",
    checkingUpdates: "Checking...",
    upToDate: "You’re on the latest version.",
    updateAvailable: (version: string) => `Version ${version} is available.`,
    updateDownload: "Download update",
    updateNotes: "Release notes",
    updateIgnore: "Skip this version",
    updateFailed: "Couldn’t check for updates.",
  },
  top: {
    groupSettings: "Group settings",
    botSettings: "Bot settings",
    pickSession: "Pick a session",
    emptyRoster: "The roster is empty. Use + on the roster row to create a bot.",
    members: "Here",
    presenceOpen: "you can open",
    profile: "Profile",
    archived: "Archived",
    deleted: "Deleted",
    pin: "Pin",
    pinned: "Pinned",
    unpin: "Unpin",
  },
  stream: {
    empty: "No messages yet.",
    mentionUnresolved: "This @ matches no member here",
    streaming: "streaming",
    replying: "replying",
    continueInterrupt: "Continue",
    continueInterruptHint: "Continue from the interruption without retrying the cut action",
    ask: "ask",
    reply: "Reply",
    approval: "approval",
    allowOnce: "Allow once",
    alwaysAllow: "Always allow",
    deny: "Deny",
    allowed: "Allowed",
    denied: "Denied",
    voided: "Voided",
    endpointKey: "Endpoint key",
    endpointKeyHintAdd: "Paste the key before Allow once. It is not written into the transcript.",
    endpointKeyHintEdit: "Required if this endpoint has no key yet; leave blank to keep the current key. It is not written into the transcript.",
    endpointKeyEmpty: "Paste the endpoint key.",
    mcpAuth: "Authorization",
    mcpAuthHintAdd: "Paste Authorization (Bearer allowed) before Allow once. It is not written into the transcript.",
    mcpAuthHintEdit: "Leave blank to keep the current Authorization; paste a new value to rotate it. It is not written into the transcript.",
    mcpAuthEmpty: "Paste Authorization.",
    artifactPreview: "Artifact preview",
    artifactMissing: "File is gone",
    artifactOpenSystem: "Open with system",
    artifactReveal: "Show in Finder",
    artifactDirectory: "Folder",
    artifactOpenUnavailable: "In the browser, download instead. Open with system is only in the app window.",
    artifactResize: "Drag to resize preview",
    artifactTree: "Cited files",
    artifactBundle: "Workspace files",
    artifactBundleCount: (count: number) => (count === 1 ? "1 file" : `${count} files`),
    artifactWrap: "Wrap",
    artifactSource: "Source",
    artifactRendered: "Preview",
    artifactFind: "Find",
    artifactFindNext: "Next",
    artifactFindPrev: "Previous",
    artifactMatchCase: "Match case",
    artifactRegexp: "Regexp",
    artifactByWord: "Whole word",
    artifactNoMatch: "No matches",
    workspaceExplorer: "Workspace",
    workspaceTruncated: "This folder has too many entries; only the first part is listed.",
    workspaceEmpty: "This folder is empty.",
    workspacePickFile: "Open a file from the left.",
    artifactSave: "Save",
    artifactSaving: "Saving",
    artifactSaveFailed: "Couldn’t save.",
    artifactDirtyTitle: "Unsaved changes",
    artifactDirtyBody: "Switching files or closing the preview discards unsaved edits.",
    artifactDiscard: "Discard",
    artifactTreeResize: "Drag to resize the file tree",
  },
  composer: {
    idle: "No live turn.",
    fork: "Fork a turn",
    send: "Send",
    stop: "Stop",
    stopGeneration: "Stop reply",
    waitingHint: "Send after the reply ends · Shift+Enter for newline",
    attach: "Add attachment",
    removeAttachment: "Remove attachment",
    removeMention: "Remove mention",
    redirect: (name: string) => `Send redirects the live turn (${name}). Done work is not rolled back.`,
    forkLive: (name: string) => `Send forks a new turn; ${name}'s current turn keeps running.`,
  },
  chat: {
    botBadge: "BOT",
    today: "Today",
    yesterday: "Yesterday",
    copyMessage: "Copy message",
    copied: "Copied",
    copyCode: "Copy code",
    replyMessage: "Reply",
    cancelReply: "Cancel reply",
    replyToYou: "Replying to you",
    replyTo: (name: string) => `Replying to ${name}`,
    replyToDeleted: "Replying to a deleted Bot",
    replyTime: (time: string) => `${time}`,
    replyPrompt: "Message",
    thinking: "Thinking & generating",
    scrollToBottom: "Scroll to bottom",
    lockedNotice: "This session is read-only (participating bots are archived or deleted)",
    groupLockedNotice: "This group is archived and is read-only",
    sendHint: "Enter to send · Shift+Enter for newline",
    sendHintShortcut: "Send (Enter)",
    mentionTooltip: "Mention a bot (@)",
    forkTooltip: "When enabled, send will fork a new turn without redirecting live work",
    forkBadge: "Fork",
    emptySessionPrompt1: "What can you help me with?",
    emptySessionPrompt2: "List files in the workspace",
    emptySessionPrompt3: "Start a new task",
    membersCount: (count: number) => `${count} members`,
    online: "Idle",
    segmentPart: (index: number) => `Part ${index}`,
    segmentCount: (count: number) => `${count} outputs`,
    messageCount: (count: number) => `${count} messages`,
  },
  thread: {
    title: "Thread",
    none: "Open a message that has replies.",
    reply: "Reply",
  },
  detail: {
    titleGroup: "Group settings",
    titleBot: "Bot settings",
    backToGroup: "Back to group settings",
    backToBot: "Back to bot settings",
    judgements: "Judgement log",
    none: "No judgements yet.",
    saveName: "Save",
    pullIn: "Pull in",
    remove: "Remove",
    members: "Members",
    saveFailed: "Couldn’t save.",
    clearHistory: "Clear history",
    clearHistoryBody: "This removes the session’s messages, turns, and judgements. The session stays. Live turns are stopped.",
    confirmClearHistory: "Confirm clear",
    deleteGroup: "Delete group",
    deleteGroupBody: "This removes the group and its messages and turns. Bots on the roster stay.",
    confirmDeleteGroup: "Confirm delete",
    cancel: "Cancel",
  },
  onboarding: {
    welcome: "Welcome to Real Bot",
    subtitle: "Your local macOS single-user agent workspace. Please complete the workspace and model provider setup to start collaborating with bots.",
    step1Title: "Workspace",
    step2Title: "Endpoint & Auth",
    step3Title: "Models",
    stepWorkspace: "1. Configure Workspace Directory",
    workspaceDesc: "Bot file and shell access stay inside this folder. Missing folders are created when you save; ~/real-bot-workspace is the recommended default.",
    workspacePlaceholder: "/Users/.../workspace or ~/real-bot-workspace",
    useDefaultWorkspace: "Use recommended (~/real-bot-workspace)",
    stepProvider: "2. Configure AI Model Provider",
    providerDesc: "Connect an OpenAI-compatible endpoint. You can add more endpoints later in Settings.",
    stepModelsDesc: "Select the models you wish to enable, and set the default model for agent turns.",
    presetCustom: "Custom",
    presetOpenAI: "OpenAI",
    presetDeepSeek: "DeepSeek",
    presetOpenRouter: "OpenRouter",
    presetOllama: "Ollama (Local)",
    nextStep: "Next",
    prevStep: "Back",
    step1Next: "Next: Model Provider",
    step2Next: "Next: Select Models",
    submit: "Save & Get Started",
    skip: "Skip for now, enter app",
    reopenGuide: "Setup incomplete, click to open setup guide",
  },
};

export const COPY = { zh, en };

export type Copy = CopyShape<typeof zh>;

export function copyFor(locale: Locale): Copy {
  return locale === "en" ? en : zh;
}
