import { describe, expect, test } from "bun:test";
import { isNoWorkCloser } from "./no-work";

describe("isNoWorkCloser", () => {
  test("drops the short no-work closers bots actually post", () => {
    expect(isNoWorkCloser("介绍已经发过，本轮没有新工作，到此结束。")).toBe(true);
    expect(isNoWorkCloser("介绍已发出，本轮没有新工作。")).toBe(true);
    expect(isNoWorkCloser("介绍已发出。")).toBe(true);
    expect(isNoWorkCloser("介绍已经发出。")).toBe(true);
    expect(isNoWorkCloser("介绍已经发出，并 @ 了同组的架构师和审查员，等他们各自发言。")).toBe(true);
    expect(isNoWorkCloser("<|eos|>")).toBe(true);
    expect(isNoWorkCloser("The introduction is already posted; no further message is needed.")).toBe(true);
    expect(isNoWorkCloser("The introduction is posted; this turn is complete.")).toBe(true);
    expect(isNoWorkCloser("本轮没有新工作")).toBe(true);
    expect(isNoWorkCloser("没有新信息时到此结束")).toBe(true);
    expect(isNoWorkCloser("No new work this turn.")).toBe(true);
    expect(isNoWorkCloser("Nothing else to add.")).toBe(true);
    expect(isNoWorkCloser("本次已完成自我介绍，无需再发消息。")).toBe(true);
    expect(isNoWorkCloser("已完成自我介绍，本轮结束。")).toBe(true);
    expect(isNoWorkCloser("设计已经写进 todo-design.md 并同步到群里，这一轮没有新的实现任务。")).toBe(true);
    expect(isNoWorkCloser("设计已经写进 `todo-design.md` 并同步到群里，这一轮没有新的实现任务。")).toBe(true);
    expect(isNoWorkCloser("设计已经写进工作区根目录 todo-design.md 并同步到群里，这一轮没有新的实现任务。")).toBe(true);
    expect(isNoWorkCloser("设计已写入 todo-design.md 并同步到群里，本轮无其他事项。")).toBe(true);
    expect(isNoWorkCloser("自我介绍已完成，无需再发消息。")).toBe(true);
    expect(isNoWorkCloser("本次自我介绍已完成。")).toBe(true);
    expect(isNoWorkCloser("已完成自我介绍。")).toBe(true);
    expect(isNoWorkCloser("自我介绍完毕，本轮结束。")).toBe(true);
    expect(isNoWorkCloser("无需再发消息。")).toBe(true);
    expect(isNoWorkCloser("这一轮没有新的实现任务。")).toBe(true);
    expect(isNoWorkCloser("本轮没有新任务。")).toBe(true);
    expect(isNoWorkCloser("Already answered in the session.")).toBe(true);
    expect(isNoWorkCloser("Already answered in this session.")).toBe(true);
    expect(isNoWorkCloser("Already answered.")).toBe(true);
    expect(isNoWorkCloser("Already replied in the session.")).toBe(true);
    expect(isNoWorkCloser("Already responded.")).toBe(true);
    expect(isNoWorkCloser("I have already answered in the session.")).toBe(true);
    expect(isNoWorkCloser("I already answered in the session.")).toBe(true);
    expect(isNoWorkCloser("The response has been sent.")).toBe(true);
    expect(isNoWorkCloser("Message sent.")).toBe(true);
    expect(isNoWorkCloser("已在会话中回复。")).toBe(true);
    expect(isNoWorkCloser("已经在会话中回复。")).toBe(true);
    expect(isNoWorkCloser("已在当前会话中回复。")).toBe(true);
    expect(isNoWorkCloser("已在会话中回答。")).toBe(true);
    expect(isNoWorkCloser("已向用户说明。")).toBe(true);
    expect(isNoWorkCloser("已回复。")).toBe(true);
    expect(isNoWorkCloser("已经回复。")).toBe(true);
    expect(isNoWorkCloser("已回答。")).toBe(true);
    expect(isNoWorkCloser("已解答。")).toBe(true);
    expect(isNoWorkCloser("消息已发送。")).toBe(true);
    expect(isNoWorkCloser("回答已发送。")).toBe(true);
    expect(isNoWorkCloser("回复已发送。")).toBe(true);
    expect(isNoWorkCloser("已发送。")).toBe(true);
    expect(isNoWorkCloser("  ")).toBe(true);
    expect(isNoWorkCloser("")).toBe(true);
  });

  test("keeps real replies, intros, and handoffs", () => {
    expect(isNoWorkCloser("已经把头像换成 pixel 风格，名字还是 Writer。")).toBe(false);
    expect(isNoWorkCloser("已在会话中回复：详情请查看 README.md")).toBe(false);
    expect(isNoWorkCloser("已向用户说明具体排查方案：1. 检查日志 2. 重启服务")).toBe(false);
    expect(isNoWorkCloser("handoff note")).toBe(false);
    expect(isNoWorkCloser("大家好，我是 Researcher。\n职责：收集与整理资料。")).toBe(false);
    expect(isNoWorkCloser("介绍已经发过，接下来我去查资料。")).toBe(false);
    expect(isNoWorkCloser("任务到此结束，报告已写好")).toBe(false);
    expect(isNoWorkCloser("I found nothing else in the notes.")).toBe(false);
    expect(isNoWorkCloser("wrote it")).toBe(false);
    expect(isNoWorkCloser("done")).toBe(false);
    expect(isNoWorkCloser("没有新工作要交给 Writer，但 brief.md 还缺一节。")).toBe(false);
    expect(isNoWorkCloser("I already sent the draft to Writer.")).toBe(false);
    expect(isNoWorkCloser("本轮没有新工作，请 @Writer 接手 brief.md")).toBe(false);
    expect(isNoWorkCloser("本轮没有新工作，要不要我去查资料？")).toBe(false);
    expect(isNoWorkCloser("请同组同事也各自介绍一下：\n@架构师\n@审查员")).toBe(false);
  });
});
