import type { CopyShape } from "./shape.ts";

/**
 * The other local agents Bots can run on (ADR 0079): Codex, Grok, OpenCode, DSH, Antigravity, ZCode
 * and your own ACP agents. Text names only; Claude keeps its own words in `claude-agent.ts`.
 */
export const zh = {
  help: (label: string) => `关于 ${label}`,
  hint: (label: string) => `让 Bot 由你本机装好并登录的 ${label} 来跑：在 Bot 面板的「运行方式」里逐个开启。Deskfolk 只启动它、问它自己的状态，不经手它的登录和凭据。用量记在它登录的账号上；应用自己的判断（读句、分类、要不要接话）照旧用端点。`,
  path: "位置",
  version: "版本",
  signIn: "登录",
  network: "网络",
  direct: "直连",
  models: "模型",
  command: "命令",
  args: "参数",
  noArgs: "无",
  proxySource: { env: "环境变量", system: "系统代理" } as Record<string, string>,
  source: { setting: "你填的路径", path: "PATH", known: "常见安装位置", login_shell: "登录 shell", custom: "你填的命令" } as Record<string, string>,
  notFound: (command: string) => `没找到 ${command}。装好后点「重新检测」，或在下面填它的完整路径。`,
  notFoundCustom: (command: string) => `没找到 ${command}。检查下面列表里填的命令路径。`,
  signedIn: (auth: string | null) => (auth ? `已登录 · ${auth}` : "已登录"),
  signedOut: "没登录，在终端运行",
  signedOutNoCommand: "没登录，按它自己的说明登录。",
  signInUnknown: "首轮时检查",
  modelsNone: "还没列出",
  modelsCount: (count: number, defaultModel: string | null) => (defaultModel ? `${count} 个，默认 ${defaultModel}` : `${count} 个`),
  noteAntigravity: "它用不了 Deskfolk 的工具，只能回话；要在工作区外动手时，这一轮会停下。",
  noteZcode: "通过 zcode-acp 桥接运行。",
  recheck: "重新检测",
  checking: "检测中…",
  pathPlaceholder: (command: string) => `${command} 的完整路径，留空则自动查找`,
  pathSave: "保存路径",
  pathInvalid: "填完整路径（以 / 或 ~/ 开头）。",
  failed: "没查到，再试一次",
  /** The account list of an agent that has config directories, each a directory it signs in from. */
  accounts: {
    heading: "账号",
    help: "关于账号",
    hint: (label: string, variable: string) => `每个账号一个 ${label} 配置目录（${variable}）。这台电脑上登录了不止一个账号时，把其他账号的目录加在这里，再在 Bot 面板里给每个 Bot 选它花哪个账号的额度；没选的 Bot 用默认账号。登录在终端里做，Deskfolk 只记目录。`,
    placeholder: (example: string) => `配置目录，例如 ${example}`,
    add: "添加",
    remove: "移除",
    none: "还没有别的账号。",
    inUse: "还有 Bot 在用这个账号：先在它的面板里换一个账号，再移除。",
    invalid: "填配置目录的完整路径（可以 ~/ 开头），不能是主目录本身。"
  },
  /** The card for your own ACP agents: any command that speaks the Agent Client Protocol on stdin and stdout. */
  custom: {
    title: "你自己的 ACP Agent",
    help: "关于你自己的 ACP Agent",
    hint: "任何能在标准输入输出上说 Agent Client Protocol 的命令都可以加在这里，加好后在 Bot 面板的「运行方式」里选它。命令填完整路径；参数每行写一个，空行不算。",
    empty: "还没有。",
    name: "名字",
    namePlaceholder: "名字，例如 my-agent",
    commandPlaceholder: "命令的完整路径，例如 /usr/local/bin/my-agent",
    argsPlaceholder: "参数，每行一个，例如\nacp\n--stdio",
    add: "添加",
    rename: "改名",
    save: "保存",
    cancel: "取消",
    remove: "移除",
    full: (max: number) => `最多 ${max} 个。`,
    inUse: "还有 Bot 在用它：先在它的面板里换一个运行方式，再移除。",
    invalid: "名字要 1 到 60 个字且不能重名，命令要填完整路径（以 / 或 ~/ 开头），参数最多 32 个。",
    failed: "没保存成功，再试一次"
  },
  unreachable: "没查到其他 Agent 的状态。电脑上的 Deskfolk 版本较旧时，先在电脑上更新，手机上才能看到和设置。",
  loading: "正在查…",
  loadFailed: "没查到，再试一次",
  retry: "再查一次",
  /** The sidebar strip: what is left of an agent's plan windows, or what it did today. */
  usage: {
    title: "Agent 用量",
    left: (percent: string) => `剩${percent}`,
    hours: (count: number) => `${count} 小时`,
    days: (count: number) => `${count} 天`,
    minutes: (count: number) => `${count} 分钟`,
    window: "额度",
    today: (turns: string, tokens: string) => `今天 ${turns} 轮 · ${tokens} token`,
    own: "默认账号"
  }
};

export const en: CopyShape<typeof zh> = {
  help: (label: string) => `About ${label}`,
  hint: (label: string) => `Let a Bot be run by the ${label} you installed and signed in to on this computer: turn it on per Bot under "Runs on" in the Bot panel. Deskfolk only starts it and asks it about itself; it never handles its sign-in or credentials. Usage counts against the account it is signed in with; the app's own judgements (reading lines, filing, who joins in) still run on your endpoints.`,
  path: "Location",
  version: "Version",
  signIn: "Sign-in",
  network: "Network",
  direct: "Direct",
  models: "Models",
  command: "Command",
  args: "Arguments",
  noArgs: "None",
  proxySource: { env: "environment", system: "system proxy" } as Record<string, string>,
  source: { setting: "the path you set", path: "PATH", known: "a usual install place", login_shell: "your login shell", custom: "the command you set" } as Record<string, string>,
  notFound: (command: string) => `${command} was not found. Install it and press Check again, or give its full path below.`,
  notFoundCustom: (command: string) => `${command} was not found. Check the command path in the list below.`,
  signedIn: (auth: string | null) => (auth ? `Signed in · ${auth}` : "Signed in"),
  signedOut: "Not signed in; run in a terminal:",
  signedOutNoCommand: "Not signed in; sign in the way it describes.",
  signInUnknown: "Checked on the first turn",
  modelsNone: "Not listed yet",
  modelsCount: (count: number, defaultModel: string | null) => (defaultModel ? `${count}, default ${defaultModel}` : `${count}`),
  noteAntigravity: "It cannot use Deskfolk's tools and can only reply; when it acts outside the workspace, the turn stops.",
  noteZcode: "It runs through the zcode-acp bridge.",
  recheck: "Check again",
  checking: "Checking…",
  pathPlaceholder: (command: string) => `Full path to ${command}; leave empty to look for it`,
  pathSave: "Save path",
  pathInvalid: "Give the full path (starting with / or ~/).",
  failed: "Could not check; try again",
  accounts: {
    heading: "Accounts",
    help: "About accounts",
    hint: (label: string, variable: string) => `Each account is a ${label} config directory (${variable}). When more than one account is signed in on this computer, add the others' directories here, then pick in each Bot's panel whose plan it spends; a Bot left alone uses the default account. Signing in happens in a terminal; Deskfolk keeps only the directory.`,
    placeholder: (example: string) => `Config directory, such as ${example}`,
    add: "Add",
    remove: "Remove",
    none: "No other accounts yet.",
    inUse: "A Bot still runs on this account: move it to another one in its panel first.",
    invalid: "Give the config directory's full path (~/ works), not your home folder itself."
  },
  custom: {
    title: "Your own ACP agents",
    help: "About your own ACP agents",
    hint: "Any command that speaks the Agent Client Protocol on its standard input and output can be added here; then pick it under \"Runs on\" in the Bot panel. Give the command's full path; write one argument per line, blank lines do not count.",
    empty: "None yet.",
    name: "Name",
    namePlaceholder: "Name, such as my-agent",
    commandPlaceholder: "Full path to the command, such as /usr/local/bin/my-agent",
    argsPlaceholder: "Arguments, one per line, such as\nacp\n--stdio",
    add: "Add",
    rename: "Rename",
    save: "Save",
    cancel: "Cancel",
    remove: "Remove",
    full: (max: number) => `At most ${max}.`,
    inUse: "A Bot still runs on it: move that Bot to another way of running in its panel first.",
    invalid: "A name is 1 to 60 characters and not used twice; the command is a full path (starting with / or ~/); at most 32 arguments.",
    failed: "Could not save; try again"
  },
  unreachable: "Could not read the other agents' status. If the computer runs an older Deskfolk, update it there first to see and set this up from here.",
  loading: "Checking…",
  loadFailed: "Could not check; try again",
  retry: "Check again",
  usage: {
    title: "Agent usage",
    left: (percent: string) => `${percent} left`,
    hours: (count: number) => `${count}-hour`,
    days: (count: number) => `${count}-day`,
    minutes: (count: number) => `${count}-minute`,
    window: "Limit",
    today: (turns: string, tokens: string) => `Today ${turns} turns · ${tokens} tokens`,
    own: "Default account"
  }
};
