import type { CopyShape } from "./shape.ts";

export const zh = {
  botBadge: "Bot",
  /** Over the app's own lines — a receipt for your stop, its answer about your stops, a restart notice — in place of a Bot's name. */
  appName: "Deskfolk",
  appBadge: "应用",
  appLineLabel: "来自 Deskfolk 应用的消息",
  today: "今天",
  yesterday: "昨天",
  copyMessage: "复制内容",
  /**
   * On a phone a long-press opens a message's menu, so the message itself never selects. This
   * page shows its text with nothing in the way of the phone's own selection.
   */
  selectText: "选择文本",
  selectTextHint: "长按文字开始选择，拖动两端调整范围。",
  copyMessageId: "复制消息 ID",
  copied: "已复制",
  copyCode: "复制代码",
  commandActivity: "命令执行",
  /** The folded line over a reply's commands, and how many of them failed. */
  commandCount: (count: number) => `${count} 条命令`,
  commandsFailed: (count: number) => `${count} 条失败`,
  /**
   * The line under a message while a Bot works on it: the step it is in, or the one it just
   * finished while it thinks. `doing` and `done` are followed by the step's subject, if any.
   */
  activity: {
    after: (done: string) => `思考中 · ${done}`,
    failed: "失败",
    showSteps: "查看这一轮做过的步骤",
    /** Over what a working Bot is doing right now, opened from the last line of its message. */
    nowTitle: (name: string, n: number) => (n > 1 ? `${name} 正在做的 ${n} 件事` : `${name} 正在做`),
    exit: (code: number) => `退出码 ${code}`,
    verbs: {
      read: { doing: "读取", done: "读了" },
      write: { doing: "写入", done: "写了" },
      delete: { doing: "删除", done: "删了" },
      list: { doing: "查看目录", done: "看了目录" },
      run: { doing: "运行", done: "跑完" },
      send: { doing: "发消息", done: "发了消息" },
      ask: { doing: "向你提问", done: "问了你" },
      checkBack: { doing: "约回看", done: "约了回看" },
      memory: { doing: "整理记忆", done: "整理了记忆" },
      skill: { doing: "查看技能", done: "看了技能" },
      editSkill: { doing: "修改技能", done: "改了技能" },
      roster: { doing: "查看名册", done: "看了名册" },
      createBot: { doing: "新建 Bot", done: "建了 Bot" },
      createGroup: { doing: "建群", done: "建了群" },
      openDirect: { doing: "开私聊", done: "开了私聊" },
      addMember: { doing: "拉进群", done: "拉进了群" },
      removeMember: { doing: "移出群", done: "移出了群" },
      profile: { doing: "修改人设", done: "改了人设" },
      routine: { doing: "整理日程", done: "整理了日程" },
      annotation: { doing: "处理批注", done: "处理了批注" },
      settings: { doing: "查看设置", done: "看了设置" },
      editSettings: { doing: "修改设置", done: "改了设置" },
      prompt: { doing: "查看提示词", done: "看了提示词" },
      editPrompt: { doing: "提出修改提示词", done: "提了提示词修改" },
      records: { doing: "查看本机记录", done: "查了本机记录" },
      call: { doing: "调用", done: "调用了" },
    },
  },
  replyMessage: "回复",
  cancelReply: "取消回复",
  /** Changing a line of yours after it went out (ADR 0063). */
  editMessage: "编辑",
  editThisLine: "编辑这句",
  edited: "已编辑",
  editedAt: (time: string) => `发出后改过 · ${time}`,
  editSave: "保存",
  editCancel: "取消",
  editSaving: "保存中…",
  editHint: "Enter 保存 · Shift+Enter 换行 · Esc 取消",
  editNotEditable: "这句不能再改了",
  editEmpty: "没有附件的话不能为空",
  editFailed: "没保存上，再试一次",
  earlierVersions: "之前的版本",
  hideEarlierVersions: "收起之前的版本",
  versionsLoading: "正在读取…",
  versionsFailed: "读不到之前的版本",
  /** A line of yours no Bot has read yet (ADR 0069): where it waits, and taking it back or having it read now. */
  queuedNextStep: "排队中 · 它下一步读到",
  queuedItsTurn: "排队中 · 轮到时读到",
  queuedHeld: "叫停中 · 解除后读到",
  insertNow: "直接插入",
  insertNowAgentTitle: "停下它正在做的这一步，马上读这句（正在跑的命令会被停掉）",
  insertNowLoopTitle: "打断它正在想的这一步，马上读这句（已经在跑的命令会跑完）",
  withdrawLine: "撤回",
  withdrawLineTitle: "Bot 还没读到这句：撤回后谁都不会再读，字放回输入框",
  lineWithdrawn: "你撤回了这句话",
  reEditLine: "重新编辑",
  lineAlreadyRead: "Bot 已经读到了，撤不回；还可以改这句",
  lineNotNow: "这会儿没有能打断的一步，它下一步就读到",
  lineActionFailed: "没成功，再试一次",
  replyToYou: "回复你",
  replyTo: (name: string) => `回复 ${name}`,
  replyToDeleted: "回复已删除的 Bot",
  replyTime: (time: string) => `耗时 ${time}`,
  replyPrompt: "发消息给",
  openAssociatedFileTree: "打开关联的文件树",
  noAssociatedFiles: "无关联文件",
  showTrace: "看这件事",
  scrollToBottom: "回到底部",
  lockedNotice: "此会话为只读（参与的 Bot 已归档或删除）",
  groupLockedNotice: "此群聊已归档，处于只读状态",
  botBotLockedNotice: "Bot↔Bot 私聊只读：你不是参与者，只能看",
  botDmOpened: "开了私聊",
  sendHint: "Enter ↵ 发送 · Shift+Enter 换行",
  sendHintShortcut: "发送（Enter）",
  mentionTooltip: "提及 Bot (@)",
  suggestNext: "建议下一步",
  forkTooltip: "开启后发送将分叉新轮次，不改道进行中的任务",
  forkBadge: "分叉",
  emptySessionPrompt1: "你可以帮我做什么？",
  emptySessionPrompt2: "查看当前工作区有哪些文件",
  emptySessionPrompt3: "开始一个新任务",
  membersCount: (count: number) => `${count} 位成员`,
  online: "空闲",
  segmentPart: (index: number) => `第 ${index} 段`,
  segmentCount: (count: number) => `${count} 段输出`,
  messageCount: (count: number) => `${count} 条消息`,
  annotationCards: (count: number) => `${count} 条批注`,
  annotationSource: (session: string) => `来自 ${session} 的那条消息`,
  annotationOpenFile: "在预览里打开",
};

export const en: CopyShape<typeof zh> = {
  botBadge: "Bot",
  appName: "Deskfolk",
  appBadge: "App",
  appLineLabel: "Message from the Deskfolk app",
  today: "Today",
  yesterday: "Yesterday",
  copyMessage: "Copy message",
  selectText: "Select text",
  selectTextHint: "Touch and hold to start selecting; drag either end to adjust.",
  copyMessageId: "Copy message ID",
  copied: "Copied",
  copyCode: "Copy code",
  commandActivity: "Commands",
  commandCount: (count: number) => (count === 1 ? "1 command" : `${count} commands`),
  commandsFailed: (count: number) => `${count} failed`,
  activity: {
    after: (done: string) => `Thinking · ${done}`,
    failed: "failed",
    showSteps: "Show the steps this turn has taken",
    nowTitle: (name: string, n: number) => (n > 1 ? `${name} · ${n} things going on` : `${name} · going on now`),
    exit: (code: number) => `exit ${code}`,
    verbs: {
      read: { doing: "Reading", done: "Read" },
      write: { doing: "Writing", done: "Wrote" },
      delete: { doing: "Deleting", done: "Deleted" },
      list: { doing: "Listing", done: "Listed" },
      run: { doing: "Running", done: "Ran" },
      send: { doing: "Sending a message", done: "Sent a message" },
      ask: { doing: "Asking you", done: "Asked you" },
      checkBack: { doing: "Booking a check-back", done: "Booked a check-back" },
      memory: { doing: "Updating memory", done: "Updated memory" },
      skill: { doing: "Reading skill", done: "Read skill" },
      editSkill: { doing: "Editing skill", done: "Edited skill" },
      roster: { doing: "Checking the roster", done: "Checked the roster" },
      createBot: { doing: "Creating Bot", done: "Created Bot" },
      createGroup: { doing: "Creating group", done: "Created group" },
      openDirect: { doing: "Opening a direct with", done: "Opened a direct with" },
      addMember: { doing: "Adding", done: "Added" },
      removeMember: { doing: "Removing", done: "Removed" },
      profile: { doing: "Editing profile", done: "Edited profile" },
      routine: { doing: "Updating routines", done: "Updated routines" },
      annotation: { doing: "Handling annotations", done: "Handled annotations" },
      settings: { doing: "Checking settings", done: "Checked settings" },
      editSettings: { doing: "Changing settings", done: "Changed settings" },
      prompt: { doing: "Reading prompts", done: "Read prompts" },
      editPrompt: { doing: "Proposing a prompt change", done: "Proposed a prompt change" },
      records: { doing: "Reading the records", done: "Read the records" },
      call: { doing: "Calling", done: "Called" },
    },
  },
  replyMessage: "Reply",
  cancelReply: "Cancel reply",
  editMessage: "Edit",
  editThisLine: "Edit this line",
  edited: "Edited",
  editedAt: (time: string) => `Changed after sending · ${time}`,
  editSave: "Save",
  editCancel: "Cancel",
  editSaving: "Saving…",
  editHint: "Enter to save · Shift+Enter for newline · Esc to cancel",
  editNotEditable: "This line can no longer be changed",
  editEmpty: "A line with no files needs words",
  editFailed: "Not saved — try again",
  earlierVersions: "Earlier versions",
  hideEarlierVersions: "Hide earlier versions",
  versionsLoading: "Loading…",
  versionsFailed: "Couldn't load earlier versions",
  queuedNextStep: "Queued · read at its next step",
  queuedItsTurn: "Queued · read when its turn comes",
  queuedHeld: "Held by a stop · read once it lifts",
  insertNow: "Insert now",
  insertNowAgentTitle: "Stop the step it is on and read this now (a running command is stopped)",
  insertNowLoopTitle: "Cut the step it is thinking through and read this now (a command already running finishes)",
  withdrawLine: "Take back",
  withdrawLineTitle: "No Bot has read this yet: take it back so none does, and put its words back in the box",
  lineWithdrawn: "You took this line back",
  reEditLine: "Edit again",
  lineAlreadyRead: "A Bot has read it already, so it can't be taken back; you can still change it",
  lineNotNow: "No step to cut right now; it reads this at its next step",
  lineActionFailed: "Didn't go through, try again",
  replyToYou: "Replying to you",
  replyTo: (name: string) => `Replying to ${name}`,
  replyToDeleted: "Replying to a deleted Bot",
  replyTime: (time: string) => `${time}`,
  replyPrompt: "Message",
  openAssociatedFileTree: "Open associated file tree",
  noAssociatedFiles: "No associated files",
  showTrace: "Show this job",
  scrollToBottom: "Scroll to bottom",
  lockedNotice: "This session is read-only (participating bots are archived or deleted)",
  groupLockedNotice: "This group is archived and is read-only",
  botBotLockedNotice: "This Bot↔Bot direct is read-only: you are not a participant",
  botDmOpened: "Opened directs",
  sendHint: "Enter to send · Shift+Enter for newline",
  sendHintShortcut: "Send (Enter)",
  mentionTooltip: "Mention a bot (@)",
  suggestNext: "Suggested next",
  forkTooltip: "When enabled, send will fork a new turn without redirecting live work",
  forkBadge: "Fork",
  emptySessionPrompt1: "What can you help me with?",
  emptySessionPrompt2: "List files in the workspace",
  emptySessionPrompt3: "Start a new task",
  membersCount: (count: number) => `${count} members`,
  online: "Idle",
  segmentPart: (index: number) => `Part ${index}`,
  segmentCount: (count: number) => `${count} outputs`,
  messageCount: (count: number) => `${count} messages`,
  annotationCards: (count: number) => (count === 1 ? "1 annotation" : `${count} annotations`),
  annotationSource: (session: string) => `From the message in ${session}`,
  annotationOpenFile: "Open in the preview",
};
