import type { CopyShape } from "./shape.ts";

export const zh = {
  title: "Claude Agent",
  help: "关于 Claude Agent",
  hint: "让 Bot 由你本机安装并登录的 Claude Code 来跑：在 Bot 面板的「运行方式」里逐个开启。Deskfolk 只启动它、问它自己的状态，不经手你的 Claude 登录和凭据。用量记在它登录的账号上；应用自己的判断（读句、分类、要不要接话）照旧用端点。",
  path: "位置",
  version: "版本",
  network: "网络",
  direct: "直连",
  proxySource: { env: "环境变量", system: "系统代理" } as Record<string, string>,
  source: { setting: "你填的路径", path: "PATH", known: "常见安装位置", login_shell: "登录 shell" } as Record<string, string>,
  notFound: "没找到 claude。装好 Claude Code 后点「重新检测」，或在下面填它的完整路径。",
  signedOut: "还没登录：在终端里运行 claude 登录。",
  apiKey: "用的是 API key：Bot 的每一轮按 token 计费。",
  baseUrl: "设了 ANTHROPIC_BASE_URL：Claude Code 的请求会发到那里。",
  outdated: (version: string) => `版本低于 Deskfolk 带的 Agent SDK（${version}），有些功能可能用不了：在终端里运行 claude update。`,
  recheck: "重新检测",
  checking: "检测中…",
  pathPlaceholder: "claude 的完整路径，留空则自动查找",
  pathSave: "保存路径",
  failed: "没查到，再试一次",
  localOnly: "只能在电脑上查看。",
  subscription: (plan: string) => `Claude ${plan} 订阅`,
  /** The Claude accounts besides the daemon's own environment, each a Claude Code config directory. */
  accounts: {
    heading: "账号",
    help: "关于账号",
    hint: "每个账号一个 Claude Code 配置目录（CLAUDE_CONFIG_DIR）。这台电脑上登录了不止一个 Claude 账号时，把其他账号的目录加在这里，再在 Bot 面板里给每个 Bot 选它花哪个账号的额度；没选的 Bot 用默认账号。登录在终端里做，Deskfolk 只记目录。每个账号下是它的用量，只在有 Bot 用它时显示。",
    defaultTag: "默认",
    placeholder: "配置目录，例如 ~/.claude-b",
    add: "添加",
    remove: "移除",
    signedOut: "未登录，在终端里运行：",
    inUse: "还有 Bot 在用这个账号：先在它的面板里换一个账号，再移除。",
    invalid: "填配置目录的完整路径（可以 ~/ 开头），不能是主目录本身。"
  },
  methods: {
    "claude.ai": "Claude 订阅",
    oauth_token: "长期令牌（Claude 订阅）",
    api_key: "API key（按 token 计费）",
    api_key_helper: "apiKeyHelper（按 token 计费）",
    third_party: "第三方平台（Bedrock / Vertex / Foundry）",
    none: "未登录"
  } as Record<string, string>,
  /** Your Claude plan's usage, as your Claude Code reads it: the sidebar meter and this card. */
  usage: {
    title: "Claude 用量",
    fiveHour: "5 小时",
    sevenDay: "7 天",
    fiveHourShort: "5小时",
    sevenDayShort: "7天",
    left: (percent: string) => `剩${percent}`,
    model: (name: string) => `${name} · 7 天`,
    resetsIn: (wait: string) => `${wait}后重置`,
    resetsAt: (when: string) => `${when} 重置`,
    resetsSoon: "即将重置",
    hoursMinutes: (hours: number, minutes: number) => (hours > 0 ? `${hours} 小时 ${minutes} 分` : `${minutes} 分钟`),
    checkedAt: (time: string) => `${time} 查的 · 由你本机的 Claude Code 读取`,
    stale: (time: string) => `这次没查到，显示的是 ${time} 的数据`,
    refresh: "刷新",
    refreshing: "刷新中…",
    expand: "展开 Claude 用量",
    collapse: "收起 Claude 用量",
    noPlan: "这个登录方式没有套餐额度：用量按 token 计费。",
    failed: "没查到用量：Claude Code 可能太旧，在终端里运行 claude update 后再刷新。",
    signedOut: "这个账号还没登录。",
    own: "默认账号"
  }
};

export const en: CopyShape<typeof zh> = {
  title: "Claude Agent",
  help: "About Claude Agent",
  hint: "Let a Bot be run by the Claude Code you installed and signed in to on this computer: turn it on per Bot under \"Runs on\" in the Bot panel. Deskfolk only starts it and asks it about itself; it never handles your Claude sign-in or credentials. Usage counts against the account it is signed in with; the app's own judgements (reading lines, filing, who joins in) still run on your endpoints.",
  path: "Location",
  version: "Version",
  network: "Network",
  direct: "Direct",
  proxySource: { env: "environment", system: "system proxy" } as Record<string, string>,
  source: { setting: "the path you set", path: "PATH", known: "a usual install place", login_shell: "your login shell" } as Record<string, string>,
  notFound: "claude was not found. Install Claude Code and press Check again, or give its full path below.",
  signedOut: "Not signed in: run claude in a terminal and sign in.",
  apiKey: "It uses an API key: every Bot turn is billed per token.",
  baseUrl: "ANTHROPIC_BASE_URL is set: Claude Code sends its requests there.",
  outdated: (version: string) => `Older than the Agent SDK Deskfolk ships with (${version}); some things may not work: run claude update in a terminal.`,
  recheck: "Check again",
  checking: "Checking…",
  pathPlaceholder: "Full path to claude; leave empty to look for it",
  pathSave: "Save path",
  failed: "Could not check; try again",
  localOnly: "Only visible on the computer itself.",
  subscription: (plan: string) => `Claude ${plan} subscription`,
  accounts: {
    heading: "Accounts",
    help: "About accounts",
    hint: "Each account is a Claude Code config directory (CLAUDE_CONFIG_DIR). When more than one Claude account is signed in on this computer, add the others' directories here, then pick in each Bot's panel whose plan it spends; a Bot left alone uses the default account. Signing in happens in a terminal; Deskfolk keeps only the directory. Under each account is its usage, shown once a Bot runs on it.",
    defaultTag: "Default",
    placeholder: "Config directory, such as ~/.claude-b",
    add: "Add",
    remove: "Remove",
    signedOut: "Not signed in; run in a terminal:",
    inUse: "A Bot still runs on this account: move it to another one in its panel first.",
    invalid: "Give the config directory's full path (~/ works), not your home folder itself."
  },
  methods: {
    "claude.ai": "Claude subscription",
    oauth_token: "Long-lived token (Claude subscription)",
    api_key: "API key (billed per token)",
    api_key_helper: "apiKeyHelper (billed per token)",
    third_party: "Third-party platform (Bedrock / Vertex / Foundry)",
    none: "Not signed in"
  } as Record<string, string>,
  usage: {
    title: "Claude usage",
    fiveHour: "5-hour",
    sevenDay: "7-day",
    fiveHourShort: "5h",
    sevenDayShort: "7d",
    left: (percent: string) => `${percent} left`,
    model: (name: string) => `${name} · 7-day`,
    resetsIn: (wait: string) => `Resets in ${wait}`,
    resetsAt: (when: string) => `Resets ${when}`,
    resetsSoon: "Resets shortly",
    hoursMinutes: (hours: number, minutes: number) => (hours > 0 ? `${hours} h ${minutes} min` : `${minutes} min`),
    checkedAt: (time: string) => `Checked ${time} · read by your own Claude Code`,
    stale: (time: string) => `Could not check this time; showing what it said at ${time}`,
    refresh: "Refresh",
    refreshing: "Refreshing…",
    expand: "Show Claude usage",
    collapse: "Hide Claude usage",
    noPlan: "This sign-in has no plan limits: usage is billed per token.",
    failed: "Could not read the usage: Claude Code may be too old. Run claude update in a terminal, then refresh.",
    signedOut: "This account is not signed in.",
    own: "Default account"
  }
};
