import type { CopyShape } from "./shape.ts";

/** Built-in connectors (ADR 0072): the picker shown when adding an endpoint, and the key-only form. */
export const zh = {
  pickHint: "内置的服务只要填 key；别的服务选「自定义」，自己填地址和格式。",
  name: { anthropic: "Anthropic", xiaomi: "小米 MiMo", qwen: "千问" },
  blurb: {
    anthropic: "Claude 系列模型，Anthropic 官方 API",
    xiaomi: "MiMo 系列模型，Token Plan 或按量付费",
    qwen: "阿里云百炼：千问，以及百炼上的 GLM、DeepSeek 等",
  },
  custom: "自定义",
  /** On a model in a picker whose endpoint is not a built-in one. */
  customMark: "Custom",
  customBlurb: "任意 OpenAI 兼容或 Anthropic 兼容的地址",
  plan: {
    "anthropic:api": "官方 API",
    "xiaomi:token-plan-cn": "Token Plan · 中国",
    "xiaomi:token-plan-sgp": "Token Plan · 新加坡",
    "xiaomi:token-plan-ams": "Token Plan · 欧洲",
    "xiaomi:payg": "按量付费",
    "qwen:token-plan": "Token Plan",
    "qwen:payg-cn": "按量付费 · 北京",
    "qwen:payg-intl": "按量付费 · 国际",
  },
  planLabel: "套餐",
  planHint: "填好 key 会自动识别，也可以手动选。",
  keyPlaceholder: { anthropic: "sk-ant-…", xiaomi: "tp-… 或 sk-…", qwen: "sk-… 或 sk-sp-…" },
  waitingKey: "填上 key，就会识别它属于哪个套餐，并拉取模型。",
  waitingKeySingle: "填上 key，就会验证它并拉取模型。",
  detecting: "正在识别这把 key 属于哪个套餐…",
  verifying: "正在验证 key…",
  detected: (plan: string, count: number) => `已识别：${plan} · ${count} 个模型`,
  verified: (count: number) => `key 可用 · ${count} 个模型`,
  listSeparator: "、",
  keyRefused: (name: string, plans: string) => `「${name}」的这几个地址都不认这把 key：${plans}。检查一下是否复制完整，或者是不是别家的 key。`,
  keyRefusedSingle: (name: string) => `「${name}」不认这把 key。检查一下是否复制完整。`,
  keyMayBeWorkspace: "之前在密钥栏填过工作区 ID 的，它已经被当成密钥存下了：把 sk-ant- 开头的 key 重新贴进来，工作区 ID 填到下面那一栏。",
  workspace: "Anthropic 工作区 ID",
  workspaceOptional: "选填",
  workspaceHint: "key 绑定了工作区就不用填。sk-ant-usr- 开头、没绑定工作区的个人 key 要填：在 Anthropic Console → Settings → Workspaces 的 ID 列，形如 wrkspc_…",
  workspaceNeeded: "这把 key 没绑定工作区，Anthropic 要求每个请求都带上它的工作区 ID。在下面填上就会再试一次。",
  workspaceInvalid: "Anthropic 工作区 ID 是 wrkspc_ 加一串字母和数字。",
  keyIsWorkspace: "这是 Anthropic 工作区 ID，不是密钥：请填到下面的「Anthropic 工作区 ID」。密钥是 sk-ant- 开头的那一串。",
  useCustom: "改用自定义地址",
};

export const en: CopyShape<typeof zh> = {
  pickHint: "A built-in service takes only a key; for any other, pick Custom and enter its address and format.",
  name: { anthropic: "Anthropic", xiaomi: "Xiaomi MiMo", qwen: "Qwen" },
  blurb: {
    anthropic: "Claude models, from Anthropic's own API",
    xiaomi: "MiMo models, on a Token Plan or pay-as-you-go",
    qwen: "Alibaba Cloud Model Studio: Qwen, and GLM, DeepSeek and more there",
  },
  custom: "Custom",
  customMark: "Custom",
  customBlurb: "Any OpenAI-compatible or Anthropic-compatible address",
  plan: {
    "anthropic:api": "Anthropic API",
    "xiaomi:token-plan-cn": "Token Plan · China",
    "xiaomi:token-plan-sgp": "Token Plan · Singapore",
    "xiaomi:token-plan-ams": "Token Plan · Europe",
    "xiaomi:payg": "Pay-as-you-go",
    "qwen:token-plan": "Token Plan",
    "qwen:payg-cn": "Pay-as-you-go · Beijing",
    "qwen:payg-intl": "Pay-as-you-go · International",
  },
  planLabel: "Plan",
  planHint: "Found from the key once it is entered; you can also pick it.",
  keyPlaceholder: { anthropic: "sk-ant-…", xiaomi: "tp-… or sk-…", qwen: "sk-… or sk-sp-…" },
  waitingKey: "Enter the key to find which plan it belongs to and fetch the models.",
  waitingKeySingle: "Enter the key to check it and fetch the models.",
  detecting: "Finding which plan this key belongs to…",
  verifying: "Checking the key…",
  detected: (plan: string, count: number) => `Found: ${plan} · ${count} model${count === 1 ? "" : "s"}`,
  verified: (count: number) => `Key works · ${count} model${count === 1 ? "" : "s"}`,
  listSeparator: ", ",
  keyRefused: (name: string, plans: string) => `None of ${name}'s addresses takes this key: ${plans}. Check it was copied whole, and that it is not another vendor's key.`,
  keyRefusedSingle: (name: string) => `${name} does not take this key. Check it was copied whole.`,
  keyMayBeWorkspace: "If a workspace ID was once entered in the key field, it was saved as the key: paste the key starting sk-ant- again, and the workspace ID in the field below.",
  workspace: "Anthropic workspace ID",
  workspaceOptional: "Optional",
  workspaceHint: "Not needed for a key scoped to a workspace. A personal key (sk-ant-usr-…) that is not needs one: the ID column under Anthropic Console → Settings → Workspaces, like wrkspc_…",
  workspaceNeeded: "This key is not scoped to a workspace, so Anthropic needs a workspace ID on every request. Enter one below and it is tried again.",
  workspaceInvalid: "A workspace ID is wrkspc_ followed by letters and digits.",
  keyIsWorkspace: "That is an Anthropic workspace ID, not a key: it goes in the Anthropic workspace ID field below. The key is the one starting sk-ant-.",
  useCustom: "Use a custom address",
};
