import type { CopyShape } from "./shape.ts";

export const zh = {
  hintStop: (who: string) => `这句像是要停下${who}：`,
  hintContinue: (who: string) => `这句像是要让${who}继续：`,
  hintEither: "这句像是在说停下或继续：",
  hintAbandon: "要停下，还是作废这件事？",
  stop: "停下",
  stopWho: (who: string) => `停下${who}`,
  continue: "继续",
  cancel: "作废这件事",
  undo: "撤销",
  stopAll: "扩大到所有 Bot",
  stopPlan: (title: string) => `一起停下《${title}》`,
  onlyPlan: (title: string) => `只停《${title}》`,
  continueOnly: (who: string) => `只让${who}继续`,
  continueOnlyHere: "只让这里继续",
  continueAll: "全部继续",
  resume: "继续",
  leave: "先放着",
  removeChecks: (count: number) => (count === 1 ? "删掉这条检查" : `删掉这 ${count} 条检查`),
  confirmCheck: "确认",
  /** On a card about a hand-over's required items (ADR 0046). */
  confirmReviewCheck: "确认这条检查",
  confirmItem: "算它做到了",
  removeItem: "不再要这条",
  /** On a card about a hand-over with no reviewer and nothing required (ADR 0046). */
  approveSubmission: "放行",
  sendBack: "退回",
  sendBackNote: "哪里要改？原话转给做的 Bot（可以不写）",
  sendBackConfirm: "确认退回",
  sendBackCancel: "取消",
  /** On a ceiling card (ADR 0046): how a part that keeps failing goes on. */
  /** On a card about a Bot's default model (ADR 0048). */
  keepDefaultModel: "就用这个",
  adoptLesson: "采用",
  declineLesson: "不要",
  lessonAdopted: "已采用",
  lessonDeclined: "没有采用",
  useEndpointDefault: "用端点默认",
  /** On a card about a line that reads as a complaint about delivered work (ADR 0046). */
  sendBackToRework: "转回返工",
  leaveIt: "不用",
  anotherWay: "换一种做法",
  anotherPlan: "改方案绕开它",
  relaxRequirement: "放宽这条要求",
  acceptAsIs: "就用现在的",
  editCheck: "改",
  declineCheck: "不要",
  useNewCheck: "用新的",
  keepOldCheck: "留原来的",
  confirmRequirements: "都是",
  reviewRequirements: "逐条看",
  requirementsSettled: "已在流程图上逐条处理",
  makeStanding: "升为常设",
  keepProject: "不用",
  undoPlan: "撤销",
  mergePlan: "并入…",
  confirmUndoPlan: "确认撤销",
  confirmMergePlan: "确认并入",
  cancelPlanAction: "返回",
  planUndoWarning: "先停下并作废这件新开的事。保留文件、原话和需求；已开始的外部操作不会撤回。",
  planMergeWarning: "只改归引用的这句原话和对应需求；新开的事会停下并作废，文件和执行历史留在原处。不会解除已有叫停。",
  planMergeTarget: "并入哪件事",
  noMergeTargets: "没有可并入的同项目规划",
  planRetained: "已停下并作废；文件、原话和执行历史已保留，已开始的操作没有撤回。",
  acted: {
    stop: "已停下",
    continue: "已继续",
    cancel: "已记为作废",
    undo: "已撤销",
    stop_all: "已停下所有 Bot",
    stop_plan: "已一起停下",
    only_plan: "已只停这件事",
    continue_only: "已只让它继续",
    continue_all: "已全部继续",
    resume: "已继续",
    leave: "先放着",
    confirm_check: "已确认",
    edit_check: "",
    remove_check: "已删掉",
    confirm_requirements: "已确认都是你说的",
    review_requirements: "",
    make_standing: "已升为常设",
    keep_project: "先不升",
    undo_plan: "新开的事已停下并作废",
    merge_plan: "原话已改归，新开的事已停下并作废",
    confirm_item: "已认可做到了",
    remove_item: "已不再要求",
    approve: "已放行",
    reject: "已退回",
    another_way: "已让它换一种做法",
    another_plan: "已让它改方案绕开",
    relax: "这条要求已放宽",
    accept: "已按现在的收下",
    rework: "已转回返工",
    dismiss: "没转回返工",
    confirm: "已定为默认模型",
    decline: "改用端点默认"
  },
  partlyResumed: (continued: number, held: number) => `${continued} 轮接着做了，${held} 轮还被叫停扣着，解除后再按「继续」`,
  spent: "已解除",
  failed: "没做成，再试一次",
  menu: "停下的范围",
  thisBot: (who: string) => `停下${who}的全部工作`,
  thisJob: "停下这件事",
  thisJobNamed: (title: string) => `停下这件事《${title}》`,
  thisGroup: "停下这个群里的工作",
  allBots: "停下所有 Bot",
  stopEverything: "全部停下",
  stopEverythingHint: "先停下：对哪个 Bot 说话就放开哪个",
  goOnEverything: "全部继续",
  holdsTitle: "叫停中",
  lift: "解除",
  dropped: "作废",
  liftOnNext: "你对它说话就放开它",
  released: (names: string) => `（已放开 ${names}）`,
  scope: {
    global: "所有 Bot 的工作",
    bot: (who: string) => `${who}的全部工作`,
    session: (where: string) => `${where}里的工作`,
    plan: (title: string) => `「${title}」这件事`,
    aPlan: "一件事",
    botPlan: (who: string, title: string) => `${who}在「${title}」上的工作`,
    turn: (who: string) => `${who}的一段`,
    ticket: (title: string) => `「${title}」里的一个任务`
  },
  rowHeld: "已叫停",
  join: "、"
};

export const en: CopyShape<typeof zh> = {
  hintStop: (who: string) => `This reads like stopping ${who}:`,
  hintContinue: (who: string) => `This reads like letting ${who} go on:`,
  hintEither: "This reads like a stop or a go on:",
  hintAbandon: "Stop, or drop this job?",
  stop: "Stop",
  stopWho: (who: string) => `Stop ${who}`,
  continue: "Continue",
  cancel: "Drop this job",
  undo: "Undo",
  stopAll: "Stop every Bot",
  stopPlan: (title: string) => `Stop “${title}” too`,
  onlyPlan: (title: string) => `Only “${title}”`,
  continueOnly: (who: string) => `Only ${who} goes on`,
  continueOnlyHere: "Only this goes on",
  continueAll: "All go on",
  resume: "Continue",
  leave: "Not now",
  removeChecks: (count: number) => (count === 1 ? "Remove this check" : `Remove these ${count} checks`),
  confirmCheck: "Confirm",
  confirmReviewCheck: "Confirm the check",
  confirmItem: "Count it as met",
  removeItem: "No longer require it",
  approveSubmission: "Approve",
  sendBack: "Send it back",
  sendBackNote: "What should change? Passed on word for word to the Bot that made it (optional)",
  sendBackConfirm: "Send it back",
  sendBackCancel: "Cancel",
  keepDefaultModel: "Keep it",
  adoptLesson: "Adopt",
  declineLesson: "No",
  lessonAdopted: "Adopted",
  lessonDeclined: "Not adopted",
  useEndpointDefault: "Use the endpoint's default",
  sendBackToRework: "Send back to rework",
  leaveIt: "Leave it",
  anotherWay: "Another way",
  anotherPlan: "Change the plan",
  relaxRequirement: "Relax this requirement",
  acceptAsIs: "Take it as it is",
  editCheck: "Change",
  declineCheck: "No",
  useNewCheck: "Use the new one",
  keepOldCheck: "Keep the old one",
  confirmRequirements: "All mine",
  reviewRequirements: "Go through them",
  requirementsSettled: "Gone through one by one on the board",
  makeStanding: "Make it standing",
  keepProject: "Not now",
  undoPlan: "Undo",
  mergePlan: "Merge into…",
  confirmUndoPlan: "Confirm undo",
  confirmMergePlan: "Confirm merge",
  cancelPlanAction: "Back",
  planUndoWarning: "Stop and abandon this newly opened job. Keep its files, your words and requirements; external actions already started are not reversed.",
  planMergeWarning: "Refile only the quoted message and its requirements. Stop and abandon the new job; leave its files and execution history in place. Existing stops stay in force.",
  planMergeTarget: "Merge into which job",
  noMergeTargets: "No existing jobs in this project",
  planRetained: "Stopped and abandoned; files, your words and execution history retained. Actions already started are not reversed.",
  acted: {
    stop: "Stopped",
    continue: "Going on",
    cancel: "Dropped",
    undo: "Undone",
    stop_all: "Every Bot stopped",
    stop_plan: "Stopped too",
    only_plan: "Narrowed to this job",
    continue_only: "Only that one goes on",
    continue_all: "All going on",
    resume: "Going on",
    leave: "Left as it is",
    confirm_check: "Confirmed",
    edit_check: "",
    remove_check: "Removed",
    confirm_requirements: "Confirmed as yours",
    review_requirements: "",
    make_standing: "Made standing",
    keep_project: "Left as it is",
    undo_plan: "New job stopped and abandoned",
    merge_plan: "Message refiled; new job stopped and abandoned",
    confirm_item: "Counted as met",
    remove_item: "No longer required",
    approve: "Approved",
    reject: "Sent back",
    another_way: "Asked for another way",
    another_plan: "Asked to change the plan",
    relax: "Requirement relaxed",
    accept: "Taken as it is",
    rework: "Sent back to rework",
    dismiss: "Left as it is",
    confirm: "Kept as the default model",
    decline: "On the endpoint's default"
  },
  partlyResumed: (continued: number, held: number) => `${continued} going on; ${held} still held by a stop — lift it, then Continue again`,
  spent: "Lifted",
  failed: "That did not work; try again",
  menu: "What to stop",
  thisBot: (who: string) => `Stop all of ${who}’s work`,
  thisJob: "Stop this job",
  thisJobNamed: (title: string) => `Stop the job “${title}”`,
  thisGroup: "Stop the work in this group",
  allBots: "Stop every Bot",
  stopEverything: "Stop everything",
  stopEverythingHint: "Stops for now: speak to a Bot and it goes on",
  goOnEverything: "All go on",
  holdsTitle: "Stopped",
  lift: "Lift",
  dropped: "Dropped",
  liftOnNext: "Speak to a Bot and it goes on",
  released: (names: string) => ` (going on: ${names})`,
  scope: {
    global: "Every Bot’s work",
    bot: (who: string) => `All of ${who}’s work`,
    session: (where: string) => `The work in ${where}`,
    plan: (title: string) => `The job “${title}”`,
    aPlan: "A job",
    botPlan: (who: string, title: string) => `${who}’s work on “${title}”`,
    turn: (who: string) => `One turn of ${who}`,
    ticket: (title: string) => `A ticket in “${title}”`
  },
  rowHeld: "Stopped",
  join: ", "
};
