import type { CopyShape } from "./shape.ts";

export const zh = {
  titleGroup: "群组设置",
  titleBot: "Bot 设置",
  backToSections: "返回",
  botTabBasics: "基础信息",
  botTabSkills: "技能",
  botTabRoutines: "日程",
  botTabMemory: "记忆",
  botTabActions: "操作",
  botBasics: "Bot 基础信息",
  sessionActions: "会话操作",
  dangerZone: "危险区域",
  backToGroup: "返回群组设置",
  backToBot: "返回 Bot 设置",
  judgements: "判断日志",
  none: "还没有判断。",
  pullIn: "拉入",
  remove: "移出",
  members: "成员",
  saveFailed: "没能保存。",
  clearHistory: "清空历史",
  clearHistoryBody: "清空后，本会话的消息、轮次和判断都去掉。会话还在。进行中的轮会 Stop。你在这里说过的话另存着，不跟着清掉；这里的事只是休眠。",
  confirmClearHistory: "确认清空",
  deleteGroup: "删除群聊",
  deleteGroupBody: "删除后，这个群和里面的消息、轮次都去掉。名册上的 Bot 还在。你在群里说过的话另存着，不跟着删掉。",
  eraseQuotes: "同时抹掉在这里说过的话",
  confirmDeleteGroup: "确认删除",
  cancel: "取消",
};

export const en: CopyShape<typeof zh> = {
  titleGroup: "Group settings",
  titleBot: "Bot settings",
  backToSections: "Back",
  botTabBasics: "Basics",
  botTabSkills: "Skills",
  botTabRoutines: "Routines",
  botTabMemory: "Memory",
  botTabActions: "Actions",
  botBasics: "Bot basics",
  sessionActions: "Actions",
  dangerZone: "Danger Zone",
  backToGroup: "Back to group settings",
  backToBot: "Back to bot settings",
  judgements: "Judgement log",
  none: "No judgements yet.",
  pullIn: "Pull in",
  remove: "Remove",
  members: "Members",
  saveFailed: "Couldn’t save.",
  clearHistory: "Clear history",
  clearHistoryBody: "This removes the session’s messages, turns, and judgements. The session stays. Live turns are stopped. What you said here is kept apart and stays; the jobs here are only set aside.",
  confirmClearHistory: "Confirm clear",
  deleteGroup: "Delete group",
  deleteGroupBody: "This removes the group and its messages and turns. Bots on the roster stay. What you said in the group is kept apart and stays.",
  eraseQuotes: "Also erase what you said here",
  confirmDeleteGroup: "Confirm delete",
  cancel: "Cancel",
};
