import { isWindows } from "./platform-words.ts";
import type { CopyShape } from "./shape.ts";

export const zh = {
  title: "通知",
  tabActionable: "待处理",
  tabUnread: "未读",
  tabAll: "全部",
  markAllRead: "全部标为已读",
  acknowledged: "我知道了",
  viewApproval: "查看批准",
  viewAsk: "查看问题",
  viewFailure: "查看原因",
  viewReply: "查看回复",
  needsApproval: "等你批准",
  needsAsk: "等你回答",
  readPrefix: "已读 · ",
  readNeedsApproval: "已读 · 等你批准",
  readNeedsAsk: "已读 · 等你回答",
  workResults: "工作结果",
  needsYou: "等你处理",
  newReply: "有新回复",
  newRoutineResult: "有新结果",
  turnInterrupted: "本轮未完成",
  executionFailed: "执行失败",
  emptyActionable: "暂时没有需要你处理的事项",
  emptyUnread: "都看过了",
  emptyAll: "暂无通知",
  connecting: "连接执行 Mac 后读取通知",
  hostUnreachable: "执行主机不可达",
  retry: "重试",
  targetMissing: "原内容已不存在",
  targetProcessed: "这项请求已处理",
  retentionNotice: "较早通知已整理，可到会话查看",
  sectionCategories: "通知类别",
  categoriesSubtitle: "控制哪些事件会触发系统通知；会话列表仍标出待处理状态",
  catApproval: "待我批准",
  catAsk: "待我回答",
  catFailure: "任务失败",
  catInterrupted: "任务中断",
  catReply: "面向你的回复",
  catRoutineResult: "日程结果",
  quietHours: "免打扰",
  quietHoursSubtitle: "在指定时间段内抑制系统通知，会话列表照常标出待处理状态",
  quietHoursEnabled: "开启免打扰",
  quietHoursStart: "开始时间",
  quietHoursEnd: "结束时间",
  quietHoursTimeZone: "时区",
  quietHoursEqualTimes: "开始时间与结束时间不能相同",
  sessionMute: "静音普通回复",
  deviceNotifications: "本设备系统通知",
  deviceSubtitle: "管理当前设备接收系统通知与推送的偏好",
  deviceEnable: "开启这台设备的系统通知",
  /** Shown once notifications are on. Windows doesn't have this native path built yet. */
  deviceEnabledDesktopNote: isWindows ? "Windows 桌面通知暂未实现，设置会保留" : "通过 macOS 本地横幅与提示音通知",
  deviceEnabled: "已开启",
  deviceDisabled: "已关闭",
  deviceSound: "声音",
  devicePreview: "内容预览",
  previewGeneric: "仅通用提示",
  previewExcerpt: "普通回复摘要",
  deviceBadge: "应用图标角标",
  sendTest: "发送测试通知",
  testSubmitting: "正在发送测试…",
  testSent: "系统已接受测试通知",
  testQueued: "测试通知已入队，等待本机投递槽；系统尚未展示",
  testRemoteQueued: "测试通知已入队，等待执行 Mac 向推送服务投递；手机接收尚未确认",
  testRemoteAccepted: "推送服务已接受测试通知；请查看手机系统通知",
  testRemoteTimeout: "执行 Mac 连接推送服务超时，已安排重试；请检查 Mac 的网络与代理",
  testPushPending: "上一条推送仍在发送或等待重试，请稍后再测试",
  testRateLimited: "每 60 秒可以发送一次测试通知，请稍后再试",
  testContactRequired: "请先在执行 Mac 上配置推送联系人 URI，再发送测试通知",
  testFailed: "测试通知发送失败",
  testDeliveryGated: "本机系统通知未合格，不能发送测试",
  nativeTestDisabled: "本机系统横幅未合格，测试通知不可用",
  permissionDenied: "系统通知已被阻止。待处理状态仍标在对应会话上。",
  iosInstallRequired: "添加到主屏幕后，从该图标打开并开启通知",
  needsRepair: "需要重新开启此设备通知",
  repairButton: "重新开启",
  browserAllowedUnregistered: "浏览器已允许，尚未连接执行 Mac 完成登记",
  pushUpgrading: "推送升级中",
  pushUnsupported: "不支持此推送服务",
  remoteGated: "远控激活仍关闭",
  unconfirmedClose: "关闭尚未确认，仍可能收到通知",
  localOnlyClose: "此浏览器已停止订阅，主机停用尚未确认",
  hostOnlyClose: "执行 Mac 已停止新推送；浏览器订阅清理未完成",
  upgradeRequired: "更新执行 Mac 后使用通知设置",
  tabTakeoverNotice: "此设备已在另一标签页连接",
  tabTakeoverButton: "接管连接",
  tabTakeoverTimeout: "接管超时，请关闭旧标签页",
  askEnded: "此问题已结束，答案尚未发送",
  askEndedReadOnly: "此问题已结束",
};

export const en: CopyShape<typeof zh> = {
  title: "Notifications",
  tabActionable: "Actionable",
  tabUnread: "Unread",
  tabAll: "All",
  markAllRead: "Mark all as read",
  acknowledged: "Got it",
  viewApproval: "View approval",
  viewAsk: "View question",
  viewFailure: "View reason",
  viewReply: "View reply",
  needsApproval: "Needs your approval",
  needsAsk: "Waiting for your answer",
  readPrefix: "Read · ",
  readNeedsApproval: "Read · Needs your approval",
  readNeedsAsk: "Read · Waiting for your answer",
  workResults: "Work results",
  needsYou: "Needs your attention",
  newReply: "New reply",
  newRoutineResult: "New routine result",
  turnInterrupted: "Turn interrupted",
  executionFailed: "Execution failed",
  emptyActionable: "No items need your attention right now",
  emptyUnread: "All caught up",
  emptyAll: "No notifications",
  connecting: "Connect to execution Mac to load notifications",
  hostUnreachable: "Execution host unreachable",
  retry: "Retry",
  targetMissing: "Original content no longer exists",
  targetProcessed: "This request has already been processed",
  retentionNotice: "Earlier notifications have been cleaned up; check session for details",
  sectionCategories: "Notification Categories",
  categoriesSubtitle: "Choose which events trigger system notifications; the chat list still shows pending state",
  catApproval: "Approvals",
  catAsk: "Questions",
  catFailure: "Failures",
  catInterrupted: "Interrupted turns",
  catReply: "Replies to you",
  catRoutineResult: "Routine results",
  quietHours: "Quiet Hours",
  quietHoursSubtitle: "Suppress system notifications during scheduled hours; the chat list still shows pending state",
  quietHoursEnabled: "Enable quiet hours",
  quietHoursStart: "Start time",
  quietHoursEnd: "End time",
  quietHoursTimeZone: "Time zone",
  quietHoursEqualTimes: "Start and end times cannot be equal",
  sessionMute: "Mute regular replies",
  deviceNotifications: "Device System Notifications",
  deviceSubtitle: "Manage system notification and push preferences for this device",
  deviceEnable: "Enable system notifications for this device",
  deviceEnabledDesktopNote: isWindows
    ? "Desktop notifications aren't implemented on Windows yet; the setting is kept"
    : "Desktop native banners and alerts are active",
  deviceEnabled: "Enabled",
  deviceDisabled: "Disabled",
  deviceSound: "Sound",
  devicePreview: "Preview content",
  previewGeneric: "Generic prompt only",
  previewExcerpt: "Excerpt for regular replies",
  deviceBadge: "App icon badge",
  sendTest: "Send test notification",
  testSubmitting: "Sending test…",
  testSent: "System accepted the test notification",
  testQueued: "Test notification queued for the local delivery slot; the system has not presented it",
  testRemoteQueued: "Test notification queued for the execution Mac to send to the push service; phone receipt is unconfirmed",
  testRemoteAccepted: "Push service accepted the test notification; check your phone's system notifications",
  testRemoteTimeout: "The execution Mac timed out connecting to the push service. A retry is scheduled; check the Mac's network and proxy settings",
  testPushPending: "A previous push is still sending or waiting to retry. Try again shortly",
  testRateLimited: "A test notification can be sent once every 60 seconds. Try again shortly",
  testContactRequired: "Configure a push contact URI on the execution Mac before sending a test notification",
  testFailed: "Test notification failed",
  testDeliveryGated: "Native system notifications are unqualified; a test cannot be sent",
  nativeTestDisabled: "Native banners are unqualified; test notifications stay unavailable",
  permissionDenied: "System notifications blocked. Pending state stays on the conversation.",
  iosInstallRequired: "Add to Home Screen, open from that icon, and enable notifications",
  needsRepair: "Need to re-enable notifications for this device",
  repairButton: "Re-enable",
  browserAllowedUnregistered: "Browser allowed; not yet registered with execution Mac",
  pushUpgrading: "Push notifications upgrading",
  pushUnsupported: "Push service not supported",
  remoteGated: "Remote activation remains off",
  unconfirmedClose: "Disable unconfirmed; notifications may still arrive",
  localOnlyClose: "Browser unsubscribed; host disable unconfirmed",
  hostOnlyClose: "Execution Mac stopped new pushes; browser subscription cleanup incomplete",
  upgradeRequired: "Update execution Mac to use notification settings",
  tabTakeoverNotice: "This device is already connected in another tab",
  tabTakeoverButton: "Take over connection",
  tabTakeoverTimeout: "Takeover timed out; please close the other tab",
  askEnded: "This question has ended; answer was not sent",
  askEndedReadOnly: "This question has ended",
};
