import { osName } from "./platform-words.ts";
import type { CopyShape } from "./shape.ts";

export const zh = {
  welcome: "欢迎使用 Deskfolk",
  subtitle: `本机 ${osName} 单人 Agent 协作空间。初次使用，先设好工作区和模型服务，再建第一个 Bot，就能开始协作。`,
  step1Title: "工作区目录",
  step2Title: "连接模型",
  step3Title: "模型选择与默认",
  step4Title: "第一个 Bot",
  stepWorkspace: "1. 配置文件工作区",
  workspaceDesc: "Bot 的文件读写和命令执行都限制在这个目录里。点选本机文件夹，不能手填路径；不存在时保存会自动创建，也可一键使用推荐目录 ~/deskfolk-workspace。",
  useDefaultWorkspace: "使用推荐目录 (~/deskfolk-workspace)",
  stepProvider: "2. 配置 AI 模型服务",
  providerDesc: "连接一个 OpenAI 兼容端点。之后可在设置里再添加更多端点。",
  connectEndpoint: "接模型端点",
  connectEndpointDesc: "OpenAI / Anthropic 兼容的服务，云端、本机（Ollama 等）或自定义地址都行。",
  connectClaude: "用本机 Claude Code",
  connectClaudeDesc: "不用端点和密钥：Bot 由你装好并登录的 Claude Code 来跑，用的是你 Claude 账号的额度。",
  claudeCheckDesc: "Deskfolk 会用这台电脑上的 claude 命令。没装或没登录时，在终端里装好、登录（claude 后输入 /login），再回来点「重新检测」。",
  claudeNotReady: "还没找到已登录的 Claude Code。",
  step2NextClaude: "下一步：选择 Claude 模型",
  claudeModelsDesc: "应用自己发起的调用——读你的话、整理看板与计划、判断谁来接话、反思和复盘——都用这个 Claude 模型。之后可在 设置 › 模型服务 › 内置模型 里逐项改。",
  claudeModel: "内置调用用的模型",
  claudeAccount: "Claude 账号",
  claudeLimits: "只用 Claude Code 时，Bot 都是 Claude Agent。端点上的 Bot、从对话里学记忆和技能要等你在设置里加了端点才有。",
  stepModelsDesc: "勾选当前要启用的模型名单，并指定用于日常任务补全的默认模型。",
  presetCustom: "自定义",
  presetOpenAI: "OpenAI",
  presetDeepSeek: "DeepSeek",
  presetOpenRouter: "OpenRouter",
  presetOllama: "Ollama (本地)",
  localPresetHint: "先在这台电脑上启动模型服务并装好模型（Ollama：ollama pull 模型名），模型列表会自动读出来。Bot 每一步的提示词常有 2–9 万 token，把服务的上下文调到 64K 以上，并选支持工具调用的模型；详见 README 的「本地模型」。",
  nextStep: "下一步",
  prevStep: "上一步",
  step1Next: "下一步：配置模型服务",
  step2Next: "下一步：选择模型",
  step3Next: "保存，下一步：建第一个 Bot",
  submit: "完成配置，开始使用",
  skip: "稍后在设置中配置，直接进入应用",
  stepBot: "4. 创建第一个 Bot",
  botDesc: "Bot 是有名字、职责和边界的持久队友，建好就能和它私聊、交代工作。下面已按通用助手填好，可以直接创建，也可以改成你想要的样子。一份调研报告、一套上线文案或一个带测试的小工具，一个 Bot 就能从头做到交付；活要分给几个角色、或者要有人专门审的时候，再在名册里加队友、开群。",
  botNameSuggested: "助理",
  botDutiesSuggested: "读工作区里的资料，把发现和出处记下来，再写成要交付的文档\n写脚本和代码，写测试并真的跑一遍，照说明亲自跑通\n交付前逐条对照要求自查，没做到的补上或说清楚",
  botBoundariesSuggested: "删除文件、对外发送内容或花钱之前先问你；拿不准要求时先和你确认。",
  botModelHint: "使用上一步设的默认模型；之后可在 Bot 资料里换。",
  botClaudeHint: "由本机 Claude Code 来跑（Claude Agent），用它自己的默认模型；之后可在 Bot 资料里换。",
  createBot: "创建并开始私聊",
  skipBot: "跳过，稍后再建",
  reopenGuide: "基础设置未完成，点击打开引导页",
};

export const en: CopyShape<typeof zh> = {
  welcome: "Welcome to Deskfolk",
  subtitle: `Your local ${osName} single-user agent workspace. Set up the workspace and a model provider, then create your first bot to start collaborating.`,
  step1Title: "Workspace",
  step2Title: "Connect a model",
  step3Title: "Models",
  step4Title: "First bot",
  stepWorkspace: "1. Configure Workspace Directory",
  workspaceDesc: "Bot file and shell access stay inside this folder. Pick a local folder; the path cannot be typed. Missing folders are created when you save; you can also use the recommended ~/deskfolk-workspace.",
  useDefaultWorkspace: "Use recommended (~/deskfolk-workspace)",
  stepProvider: "2. Configure AI Model Provider",
  providerDesc: "Connect an OpenAI-compatible endpoint. You can add more endpoints later in Settings.",
  connectEndpoint: "Model endpoint",
  connectEndpointDesc: "An OpenAI- or Anthropic-compatible service: in the cloud, on this computer (Ollama and the like) or at an address of your own.",
  connectClaude: "Claude Code on this computer",
  connectClaudeDesc: "No endpoint or key: Bots are run by the Claude Code you installed and signed in to, on your Claude account's usage.",
  claudeCheckDesc: "Deskfolk runs the claude command on this computer. If it is missing or signed out, install it and sign in from a terminal (run claude, then /login), then come back and press Check again.",
  claudeNotReady: "No signed-in Claude Code found yet.",
  step2NextClaude: "Next: Claude model",
  claudeModelsDesc: "The calls the app makes on its own — reading your lines, keeping the board and plan in order, judging who answers, reflections and retrospectives — run on this Claude model. Change each one later in Settings › Models › Built-in models.",
  claudeModel: "Model for built-in calls",
  claudeAccount: "Claude account",
  claudeLimits: "With Claude Code alone, every Bot is a Claude Agent. Bots on an endpoint, and learning memories and skills from a conversation, wait until you add an endpoint in Settings.",
  stepModelsDesc: "Select the models you wish to enable, and set the default model for agent turns.",
  presetCustom: "Custom",
  presetOpenAI: "OpenAI",
  presetDeepSeek: "DeepSeek",
  presetOpenRouter: "OpenRouter",
  presetOllama: "Ollama (Local)",
  localPresetHint: "Start the model server on this computer and install a model first (Ollama: ollama pull <model>); the model list is read from it. A Bot's prompt is often 20–90K tokens per step, so raise the server's context to 64K or more and pick a model that calls tools; see \"Local models\" in the README.",
  nextStep: "Next",
  prevStep: "Back",
  step1Next: "Next: Model Provider",
  step2Next: "Next: Select Models",
  step3Next: "Save, next: First bot",
  submit: "Save & Get Started",
  skip: "Skip for now, enter app",
  stepBot: "4. Create Your First Bot",
  botDesc: "A bot is a lasting teammate with a name, duties and boundaries; once it exists you can message it and hand it work. The fields below describe a general assistant: create it as is or make it your own. One bot can take a research report, a set of launch copy or a small tool with tests from start to delivery; add teammates from the roster and open a group when the work splits across roles or needs someone whose job is to review it.",
  botNameSuggested: "Assistant",
  botDutiesSuggested: "Reads the material in the workspace, notes findings and sources, and writes them up as the deliverable\nWrites scripts and code, writes the tests and actually runs them, follows its own instructions end to end\nChecks the delivery against every requirement before handing it over, and fixes or explains what is missing",
  botBoundariesSuggested: "Asks you before deleting files, sending anything out, or spending money; checks with you when a request is unclear.",
  botModelHint: "Runs on the default model from the previous step; you can change it later in the bot's profile.",
  botClaudeHint: "Run by Claude Code on this computer (Claude Agent), on its own default model; you can change it later in the bot's profile.",
  createBot: "Create & start chatting",
  skipBot: "Skip, create one later",
  reopenGuide: "Setup incomplete, click to open setup guide",
};
