import type { CopyShape } from "./shape.ts";

export const zh = {
  /** The word for one content area inside the desktop window. Not 窗口, which is the Tauri window. */
  title: "窗格",
  splitUp: "向上分割",
  splitDown: "向下分割",
  splitLeft: "向左分割",
  splitRight: "向右分割",
  dockToSplit: "浮动的窗格先停靠回布局，才能分割。",
  close: "关闭窗格",
  closeTab: "关闭标签页",
  closeOtherTabs: "关闭其他标签页",
  closeTabsRight: "关闭右侧标签页",
  closeAllTabs: "关闭所有标签页",
  /** The ⋯ on a tab, and the menu it opens: what the tab offers for what it shows. */
  tabActions: "更多操作",
  /** One tab out into a floating pane of its own; the pane's other tabs stay where they are. */
  floatTab: "浮动这个标签页",
  dock: "停靠回布局",
  equalise: "平分",
  reset: "重置布局",
  resize: "调整窗格大小",
  junction: "调整交叉点",
  empty: "这个窗格还没有内容",
  emptyHint: "打开一条会话、一个终端、工作区或日程图。",
  emptyPick: "从侧栏点一条会话放进来，或者从下面挑一个。",
  tabsIn: "{name} 的标签页",
  newTab: "新建标签页",
  runningTerminals: "可接回",
  noRunningTerminals: "没有可接回的终端",
  findOpen: "按名字或路径找",
  panes: "窗格",
  tooSmall: "窗口太窄，放不下再分一块。",
  copy: "复制",
  paste: "粘贴",
  /** A conversation's own flow board. The name stays put while the board changes jobs. */
  flowOf: (name: string) => `${name}流程`,
  /** The tickets' board of a conversation's job, a tab of its own beside the flow. */
  boardOf: (name: string) => `${name}看板`,
  /** The spec of a conversation's job, a tab of its own beside the flow. */
  specOf: (name: string) => `${name}要点`,
  /** A conversation's own artifact preview. The name stays put while the file changes. */
  artifactsOf: (name: string) => `${name}的产物`,
};

export const en: CopyShape<typeof zh> = {
  title: "Pane",
  splitUp: "Split up",
  splitDown: "Split down",
  splitLeft: "Split left",
  splitRight: "Split right",
  dockToSplit: "Dock a floating pane back into the layout to split it.",
  close: "Close pane",
  closeTab: "Close tab",
  closeOtherTabs: "Close other tabs",
  closeTabsRight: "Close tabs to the right",
  closeAllTabs: "Close all tabs",
  tabActions: "More actions",
  floatTab: "Float this tab",
  dock: "Dock back into the layout",
  equalise: "Even out",
  reset: "Reset layout",
  resize: "Resize pane",
  junction: "Move junction",
  empty: "Nothing open in this pane",
  emptyHint: "Open a conversation, a terminal, the workspace or the calendar.",
  emptyPick: "Open a conversation from the sidebar, or pick one of these.",
  tabsIn: "Tabs in {name}",
  newTab: "New tab",
  runningTerminals: "Reattach",
  noRunningTerminals: "No terminal to reattach",
  findOpen: "Find by name or path",
  panes: "Panes",
  tooSmall: "The window is too narrow to divide again.",
  copy: "Copy",
  paste: "Paste",
  flowOf: (name: string) => `${name} flow`,
  boardOf: (name: string) => `${name} board`,
  specOf: (name: string) => `${name} plan`,
  artifactsOf: (name: string) => `${name}'s artifacts`,
};
