import type { CopyShape } from "./shape.ts";

export const zh = {
  noSpec: "还没有整理出要点。等这件事有人动过，应用会整理出目标、验收和任务。",
  brief: "开头的要求",
  kind: "类别",
  status: { active: "进行中", done: "已完成", parked: "搁置" },
  ticketStatus: { todo: "待做", doing: "进行中", review: "待验收", done: "已完成", parked: "搁置" },
  /** A stage the status alone does not say (ADR 0046): shown in its place. */
  ticketStage: { submitted: "已交付", in_review: "审查中", rework: "返工", approved: "已通过" },
  partsApproved: (approved: number, total: number) => `${approved}/${total} 已通过`,
  ball: {
    owner: (name: string) => `球在 ${name} 手里`,
    lead: (name: string) => `等负责人 ${name} 派人`,
    delegation: (name: string) => `${name} 在做委派给它的部分`,
    reviewer: (name: string) => `等 ${name} 审`,
    approval: "应用下一拍放行",
    job: "在等渲染结果",
    ask: "在等你回答",
    blocked: "卡住了，在等你",
    held: "你叫停了",
    held_dependency: "它等的任务被叫停了",
    review: "等你审批",
    acceptance: "等你验收（在板上标完成）",
    ceiling: "卡在能力天花板，等你决定",
    unclaimed: "没人在做，等你派"
  } as Record<string, string | ((name: string) => string)>,
  /** A ticket waiting for another not through yet (ADR 0060): the sample until you approve it, any other until it is handed over. */
  ballWaits: (tag: string, sample: boolean) => sample ? `等样片 ${tag} 你放行` : `等 ${tag} 先交`,
  sample: "样片",
  sampleHint: "先做的那一件：按整件事的水准做足、由你放行；其余各件等它，交上来时拿它对照",
  dependsOn: (tags: string) => `要等 ${tags} 先完成`,
  editDepends: "依赖",
  dependsHint: "这张任务要等哪些先完成（监督器不会先叫醒它）",
  dependsNone: "没有别的任务可选",
  modelOverride: "这张任务用的模型",
  modelOwn: "用 Bot 自己的模型",
  dependsLoop: "它已经在等这张任务，再选会成环",
  dependsParked: "它已搁置，等它就永远等不到",
  reviewer: "审查者",
  noReviewer: "无审查者",
  /** The picked ticket's settings, as short labels beside their menus. */
  modelShort: "模型",
  dependsNothing: "不等别的任务",
  /** An unpicked ticket's reviewer and model, said in its line. */
  reviewedBy: (name: string) => `${name}审`,
  onModel: (model: string) => `用 ${model}`,
  spec: {
    title: "要点",
    name: "名字",
    nameHint: "这件事在应用里和 Bot 的局面里都叫这个名字；它的文件夹不跟着改名。",
    renamedGoal: (goal: string) => `目标还写着「${goal}」，Bot 照目标做；对不上就一起改。`,
    editGoal: "改目标",
    /** A large job (ADR 0060), and your word on it. */
    scaleLarge: (unit: string | null) => `大活：先拆成几件${unit ? `（每件${unit}）` : ""}，先做样片给你放行，再铺开。`,
    scaleWhy: { reader: (why: string | null) => why ? `从你说的「${why}」认出来的。` : "从你的话认出来的。",
      signal: (why: string | null) => why ? `${why}，应用认出来的。` : "做了好几段还没有一件通过，应用认出来的。",
      user: (_why: string | null) => "你定的。" },
    scaleSingle: "你说过这件不用拆。",
    scaleNotLarge: "不用拆",
    scaleMakeLarge: "按大活做",
    goal: "目标",
    acceptance: "验收",
    rules: "规则",
    process: "流程与分工",
    progress: "进展",
    done: "已完成",
    open: "待做",
    blocked: "卡住"
  },
  checks: {
    title: "检查",
    run: "跑检查",
    add: "+ 检查",
    summary: (pass: number, total: number) => `检查 ${pass}/${total} 通过`,
    none: "还没有检查",
    orphansTitle: "对不上验收条目的检查",
    derivedTitle: "按你的话加的检查",
    editHint: "改写一条验收时它的检查会跟着这一条；删掉的条目的检查会移到「对不上验收条目的检查」。",
    status: { pass: "通过", fail: "没过", running: "跑着", blocked: "拦下", error: "出错", none: "没跑过", unbound: "未绑定", proposed: "待确认" },
    sourceOrganizer: "整理跳加的",
    sourceUser: "你加的",
    sourceReflection: "Bot 反思后提议、你采用的：没过会打回，但改过一次才算你写的",
    sourceDerived: "按你的话加的：要改就说改成多少",
    stateProposed: "你确认之后它才拦东西；交付了就先量给你看。",
    unconfirmed: (got: string, said: string) => `未确认的检查：${got}，你说的是${said}（待你确认）`,
    confirm: "确认",
    confirmFailed: "没能确认。",
    lastRun: "上次跑",
    neverRun: "还没跑过",
    rerun: "重跑",
    remove: "删",
    confirmRemoveTitle: "删掉这条检查",
    confirmRemoveBody: "删掉后它的跑动记录还在，但不会再跑。",
    confirmRemove: "确认删除",
    itemLabel: "对应哪条验收",
    kindExists: "文件存在",
    kindContains: "包含文字",
    kindMatches: "匹配正则",
    kindCommand: "运行命令",
    kindContinuity: "衔接一致",
    pathLabel: "文件路径",
    patternLabel: "文字",
    patternLabelRegex: "正则",
    negateContains: "不包含",
    negateMatches: "不匹配",
    commandLabel: "命令",
    cwdLabel: "目录",
    cwdPlaceholder: "默认在工作区根目录",
    expectExitLabel: "期望退出码",
    expectStdoutToggle: "期望输出",
    expectStdoutLabel: "期望输出",
    expectStdoutHint: "留空则不比对退出码之外的输出",
    timeoutLabel: "超时（秒）",
    continuityPathLabel: "各部分（文件、通配或一份按标题切分的文档）",
    continuityCommandLabel: "列出各部分顺序的命令（可选）",
    itemRequired: "选一条验收",
    pathRequired: "填文件路径",
    patternRequired: "填文字或正则",
    commandRequired: "填命令",
    pathOrCommandRequired: "填各部分的路径、通配，或列出各部分顺序的命令",
    expectExitInvalid: "退出码要是整数",
    timeoutInvalid: "超时要是 1–600 的整数",
    createFailed: "没能加上这条检查。",
    runFailed: "没能开始跑。",
    removeFailed: "没能删除。",
    outsideWorkspace: "只能检查工作区里的文件和命令",
    tooManyChecks: "一个规划最多 10 条检查",
    checkGone: "这条检查已经被改过或删掉了，刷新后再试",
    describeExists: (path: string) => `${path} 存在且不为空`,
    describeContains: (path: string, pattern: string, negate: boolean) =>
      `${path} ${negate ? "不" : ""}包含 “${pattern}”`,
    describeMatches: (path: string, pattern: string, negate: boolean) =>
      `${path} ${negate ? "不" : ""}匹配 /${pattern}/`,
    describeCommand: (command: string, cwd: string | null, expectExit: number) =>
      cwd ? `在 ${cwd} 运行 \`${command}\`，期望退出码 ${expectExit}` : `运行 \`${command}\`，期望退出码 ${expectExit}`,
    describeContinuity: (path: string, command: string, cwd: string | null) =>
      command
        ? `检查 \`${command}\`${cwd ? `（在 ${cwd}）` : ""} 列出的各部分之间是否衔接一致`
        : `检查 ${path} 各部分之间是否衔接一致`,
    measure: {
      duration: (range: string) => `时长 ${range} 秒`,
      resolution: (range: string) => `短边 ${range} 像素`,
      fps: (range: string) => `帧率 ${range}`,
      aspect: (ratio: string) => `画幅 ${ratio}`,
      portrait: "竖屏（高大于宽）",
      landscape: "横屏（宽大于高）",
      atLeast: (value: string) => `至少 ${value}`,
      atMost: (value: string) => `不超过 ${value}`
    },
    describeMeasure: (what: string, path: string | null) =>
      path ? `${what}：${path}` : `${what}；交付最终成品（文件名带 MASTER 或 final 的视频，或放在 deliverables/ 下）后才开始检查`
  },
  empty: "（无）",
  edit: "改",
  save: "保存",
  cancel: "取消",
  linesHint: "一行一条",
  saveFailed: "没能保存。",
  conflict: "要点刚刚变了，已重新读取，请再改一次。",
  revision: (n: number) => `第 ${n} 版`,
  byApp: "应用整理",
  byUser: "你改的",
  byHold: "叫停改的",
  history: "改动记录",
  historyNone: "还没有改动记录。",
  jumpToMessage: "跳到那条消息",
  tickets: "任务",
  ticketsNone: "还没有拆出任务。",
  ticketCounts: (open: number, total: number) => `${open} 未完成 · 共 ${total}`,
  /** Who is on a ticket: filled from the division of work when it opens, so a ticket nobody started yet reads as theirs to do. */
  worker: (name: string, started = true) => (started ? `${name}在做` : `${name}来做`),
  /** Who made a ticket that is closed (approved, dropped): nobody is still on it. */
  workerDone: (name: string) => `${name}做的`,
  nobody: "还没人接",
  artifacts: (n: number) => `${n} 个产物`,
  jumpToTurn: "跳到这一轮",
  changeStatus: "改状态",
  segmentSpec: "要点",
  segmentTickets: "任务",
  segmentBoard: "看板",
  segmentTrace: "经过",
  showSpec: "在旁边看要点",
  hideSpec: "收起要点",
  showTickets: "在旁边看任务",
  hideTickets: "收起任务",
  showBoard: "看板上的五列占满这块区域",
  hideBoard: "收回看板，看流程图",
  /** The five columns, and a move that waits because a hand-over is still open. */
  board: {
    emptyColumn: "没有任务",
    focusClear: "不再只看这一列",
    dragHint: "拖到另一列改状态；触控用状态下拉",
    pendingMove: (column: string) => `移到「${column}」会作废还在等你放行或退回的交付；移到已完成会直接变成已通过。`,
    moveAnyway: "仍然移动",
    keep: "留下",
    conflictDropped: "规划刚变过，没移成的已放回。"
  },
  /** How the plan's spec and its tickets point at each other: every ticket meets the spec, some lines hold for one ticket alone. */
  links: {
    ticketsHint: "每个任务都要满足要点里的验收、规则和你的要求；点一个任务，流程图点亮它的轮，并列出它要满足的。",
    heldTo: "要满足",
    planWide: (parts: string) => `要点里的${parts}，每个任务都要满足`,
    join: "、",
    acceptanceCount: (n: number) => `验收 ${n} 条`,
    rulesCount: (n: number) => `规则 ${n} 条`,
    requirementsCount: (n: number) => `你的要求 ${n} 条`,
    planWideNone: "要点里还没有验收和规则，也还没记下你的要求。",
    onlyThis: "只管这个任务的",
    showSpec: "在要点里看",
    focus: "正在看任务",
    focusHint: "它要满足下面的验收、规则和你的要求；只管别的任务的已变暗。",
    showTicket: (label: string) => `看任务 ${label}`,
    clearFocus: "不再看这个任务",
    ticketStates: "任务",
    progressHint: "任务的状态以这一行为准；下面是整理跳按经过记的文字进展。"
  },
  dormant: "休眠",
  dormantHint: "会话被清空或删除后先放一边；你再说到它或在流程图上改它就醒来",
  lastChange: (ago: string, what: string) => `上次变化 ${ago}（${what}）`,
  ago: {
    now: "刚刚",
    minute: (n: number) => `${n} 分钟前`,
    hour: (n: number) => `${n} 小时前`,
    day: (n: number) => `${n} 天前`
  },
  requirements: {
    title: "你的要求",
    hint: "每条都站在你说过的原话上；Bot 的局面里就是这张单子。",
    none: "还没记下要求。",
    inherited: (title: string, count: number) => `继承自「${title}」的 ${count} 条`,
    proposed: "待你确认",
    proposedHint: "还没生效；你确认了才算。",
    unverified: "旧规则（出处未核实）",
    unverifiedHint: "只作参考，不拦东西；是你说的就确认。",
    excluded: "不适用这件事的",
    said: (n: number) => `已说 ${n} 次`,
    saidAcross: (n: number, plans: number) => `已说 ${n} 次（跨 ${plans} 件事）`,
    restated: (text: string) => `转述：${text}`,
    replaces: (seq: number, quote: string) => `要取代 R-${seq}「${quote}」`,
    scope: {
      ticket: (label: string) => `适用：任务 ${label}`,
      plan: "适用：这件事",
      project: "适用：这个会话的每件事",
      standing: (domain: string | null) => (domain === "video" ? "适用：每个视频" : domain ? `适用：常设（${domain}）` : "适用：常设")
    },
    source: {
      message: "你说的",
      ask_answer: "你的回答",
      annotation: "你的批注",
      board: "你在流程图写的",
      legacy: "旧规则",
      capture: "你的原话，整句记下"
    },
    jump: "看原话",
    confirm: "确认",
    reject: "不是要求",
    waive: "不再适用",
    notHere: "不适用这件事",
    hereAgain: "恢复",
    wholeProject: "对这个会话都适用",
    failed: "没做成，再试一次。"
  },
  retrospective: {
    title: "完工复盘",
    hint: "这件事交付后，做过它的 Bot 回看了一遍：踩了哪些坑、哪些做法让你返工、下次该照做什么，并改了它自己的记忆和技能。每一处改动都能撤销。",
    running: (bot: string) => `${bot} 正在复盘…`,
    failed: {
      call_failed: "复盘没跑成：模型调用失败，什么都没改。",
      truncated: "复盘没跑成：回答没写完，什么都没改。",
      unreadable: "复盘没跑成：回答读不懂，什么都没改。",
      interrupted: "复盘没跑成：被重启打断，什么都没改。",
      no_model: "复盘没跑成：没有能用的模型，什么都没改。",
      other: "复盘没跑成，什么都没改。"
    },
    pitfalls: "踩的坑",
    reworkCauses: "让你返工的做法",
    keep: "下次照做",
    earlier: "以前的结论",
    verdict: { held: "仍然成立", recurred: "又犯了", obsolete: "已不成立" },
    changes: "改动",
    noChanges: "没有改记忆和技能。",
    change: {
      memoryNew: (label: string) => `新记忆「${label}」`,
      memoryRewrite: (label: string) => `改写记忆「${label}」`,
      memoryForget: (label: string) => `删掉记忆「${label}」`,
      skillEdit: (label: string) => `改了技能「${label}」`,
      skillCreate: (label: string) => `新建技能「${label}」`
    },
    undo: "撤销",
    undone: "已撤销",
    undoChanged: "撤销没成：它之后又被改过，现在是新的样子。",
    undoFailed: "撤销没成，再试一次。",
    showDiff: "看改了什么",
    before: "原来",
    after: "现在",
    notApplied: (reason: string) => `没写进去：${reason}`,
    reason: {
      off: "你停用了它",
      full: "已经满了",
      over_cap: "超出一次复盘能改的条数",
      unchanged: "和原来一样",
      missing: "没有这一条",
      project_skill: "这是项目共享技能，不归它改",
      name_taken: "已有同名技能",
      project_name: "和一条项目共享技能同名",
      too_long: "太长了",
      required: "缺内容",
      edit_missing: (n: number) => `第 ${n} 处：技能里找不到它指的那段原文`,
      edit_repeated: (n: number, times: number) => `第 ${n} 处：它指的那段原文出现了 ${times} 次`,
      edit_not_one_sentence: (n: number) => `第 ${n} 处：一次只能改正一句`,
      edit_unread: (n: number) => `第 ${n} 处：技能太长没读，只能在末尾追加`,
      drops: (names: string) => `会丢掉 ${names}`,
      refused: "被拒绝了"
    }
  }
};

export const en: CopyShape<typeof zh> = {
  noSpec: "No plan yet. Once someone has worked on this, the app writes up the goal, what counts as done, and the tickets.",
  brief: "Opening request",
  kind: "Kind",
  status: { active: "In progress", done: "Done", parked: "Parked" },
  ticketStatus: { todo: "To do", doing: "In progress", review: "In review", done: "Done", parked: "Parked" },
  ticketStage: { submitted: "Submitted", in_review: "In review", rework: "Rework", approved: "Approved" },
  partsApproved: (approved: number, total: number) => `${approved}/${total} approved`,
  ball: {
    owner: (name: string) => `With ${name}`,
    lead: (name: string) => `Waiting on the lead, ${name}, to hand it out`,
    delegation: (name: string) => `${name} is on the part handed to it`,
    reviewer: (name: string) => `Waiting on ${name}'s review`,
    approval: "The app approves it at the next tick",
    job: "Waiting on a render",
    ask: "Waiting on your answer",
    blocked: "Stuck, waiting on you",
    held: "You stopped it",
    held_dependency: "A ticket it waits for is stopped",
    review: "Waiting on your approval",
    acceptance: "Waiting on your acceptance (mark it done on the board)",
    ceiling: "At the capability ceiling, waiting on you",
    unclaimed: "Nobody is on it; yours to hand out"
  } as Record<string, string | ((name: string) => string)>,
  ballWaits: (tag: string, sample: boolean) => sample ? `Waits for you to approve sample ${tag}` : `Waits for ${tag} to be handed over`,
  sample: "Sample",
  sampleHint: "Made first, to the whole job's standard, for you to approve; the others wait for it and are compared with it",
  dependsOn: (tags: string) => `Waits for ${tags}`,
  editDepends: "Depends on",
  dependsHint: "Which tickets this one waits for (the supervisor wakes nobody to it before they are done)",
  dependsNone: "No other ticket to choose",
  modelOverride: "The model this ticket runs on",
  modelOwn: "The Bot's own model",
  dependsLoop: "It already waits for this ticket; choosing it would make a loop",
  dependsParked: "It is parked; waiting for it would never end",
  reviewer: "Reviewer",
  noReviewer: "No reviewer",
  modelShort: "Model",
  dependsNothing: "Waits for none",
  reviewedBy: (name: string) => `Reviewed by ${name}`,
  onModel: (model: string) => `On ${model}`,
  spec: {
    title: "Plan",
    name: "Name",
    nameHint: "What this job is called in the app and in every Bot's picture; its folder keeps its name.",
    renamedGoal: (goal: string) => `The goal still reads "${goal}", and the Bots work to the goal; change it too if it no longer fits.`,
    editGoal: "Edit the goal",
    scaleLarge: (unit: string | null) => `A large job: laid out in parts${unit ? ` (${unit} each)` : ""}, with a sample made first for you to approve before the rest.`,
    scaleWhy: { reader: (why: string | null) => why ? `Read from your words "${why}".` : "Read from your words.",
      signal: (why: string | null) => why ? `${why}: the app took it as one.` : "Several segments with nothing approved: the app took it as one.",
      user: (_why: string | null) => "Your call." },
    scaleSingle: "You said this one needs no laying out.",
    scaleNotLarge: "No need",
    scaleMakeLarge: "Treat as large",
    goal: "Goal",
    acceptance: "Done when",
    rules: "Rules",
    process: "Process",
    progress: "Progress",
    done: "Done",
    open: "Open",
    blocked: "Blocked"
  },
  checks: {
    title: "Checks",
    run: "Run checks",
    add: "+ Check",
    summary: (pass: number, total: number) => `${pass}/${total} checks pass`,
    none: "No checks yet",
    orphansTitle: "Checks that don’t match a line",
    derivedTitle: "Checks from what you said",
    editHint: "Rewording a line keeps its checks; a deleted line’s checks move to “Checks that don’t match a line”.",
    status: { pass: "Pass", fail: "Fail", running: "Running", blocked: "Blocked", error: "Error", none: "Never run", unbound: "Not bound", proposed: "To confirm" },
    sourceOrganizer: "Added by the organizer",
    sourceUser: "Added by you",
    sourceReflection: "Proposed by a Bot's reflection, adopted by you: failing it sends work back, but it counts as yours once you edit it",
    sourceDerived: "From what you said: to change it, say what to make it",
    stateProposed: "It holds nothing back until you confirm it; once there is a delivery, it is measured for you to see.",
    unconfirmed: (got: string, said: string) => `Unconfirmed check: ${got}; you said ${said} (waiting for your confirm)`,
    confirm: "Confirm",
    confirmFailed: "Could not confirm.",
    lastRun: "Last run",
    neverRun: "Never run",
    rerun: "Rerun",
    remove: "Delete",
    confirmRemoveTitle: "Delete this check",
    confirmRemoveBody: "Its past runs stay, but it will not run again.",
    confirmRemove: "Confirm delete",
    itemLabel: "Proves which line",
    kindExists: "File exists",
    kindContains: "Contains text",
    kindMatches: "Matches regex",
    kindCommand: "Runs a command",
    kindContinuity: "Seams",
    pathLabel: "File path",
    patternLabel: "Text",
    patternLabelRegex: "Regex",
    negateContains: "Does not contain",
    negateMatches: "Does not match",
    commandLabel: "Command",
    cwdLabel: "Directory",
    cwdPlaceholder: "Defaults to the workspace root",
    expectExitLabel: "Expected exit code",
    expectStdoutToggle: "Expected output",
    expectStdoutLabel: "Expected output",
    expectStdoutHint: "Leave blank to skip comparing output beyond the exit code",
    timeoutLabel: "Timeout (seconds)",
    continuityPathLabel: "Parts (a file, a glob, or a document split by headings)",
    continuityCommandLabel: "Command that lists the part order (optional)",
    itemRequired: "Pick a line",
    pathRequired: "Enter a file path",
    patternRequired: "Enter text or a regex",
    commandRequired: "Enter a command",
    pathOrCommandRequired: "Enter a path or glob for the parts, or a command that lists their order",
    expectExitInvalid: "Exit code must be an integer",
    timeoutInvalid: "Timeout must be an integer from 1 to 600",
    createFailed: "Couldn’t add that check.",
    runFailed: "Couldn’t start the run.",
    removeFailed: "Couldn’t delete it.",
    outsideWorkspace: "Only files and commands inside the workspace can be checked",
    tooManyChecks: "A plan holds at most 10 checks",
    checkGone: "This check was already changed or deleted; reload and try again",
    describeExists: (path: string) => `${path} exists and is not empty`,
    describeContains: (path: string, pattern: string, negate: boolean) =>
      `${path} ${negate ? "does not contain" : "contains"} “${pattern}”`,
    describeMatches: (path: string, pattern: string, negate: boolean) =>
      `${path} ${negate ? "does not match" : "matches"} /${pattern}/`,
    describeCommand: (command: string, cwd: string | null, expectExit: number) =>
      cwd ? `Runs \`${command}\` in ${cwd}, expecting exit code ${expectExit}` : `Runs \`${command}\`, expecting exit code ${expectExit}`,
    describeContinuity: (path: string, command: string, cwd: string | null) =>
      command
        ? `Checks the parts listed by \`${command}\`${cwd ? ` (in ${cwd})` : ""} fit together`
        : `Checks the parts of ${path} fit together`,
    measure: {
      duration: (range: string) => `Running time ${range} s`,
      resolution: (range: string) => `Short side ${range} px`,
      fps: (range: string) => `Frame rate ${range} fps`,
      aspect: (ratio: string) => `Aspect ${ratio}`,
      portrait: "Portrait (taller than wide)",
      landscape: "Landscape (wider than tall)",
      atLeast: (value: string) => `at least ${value}`,
      atMost: (value: string) => `at most ${value}`
    },
    describeMeasure: (what: string, path: string | null) =>
      path ? `${what}: ${path}` : `${what}; checked once the final cut is delivered (a video named *MASTER* or *final*, or under deliverables/)`
  },
  empty: "(none)",
  edit: "Edit",
  save: "Save",
  cancel: "Cancel",
  linesHint: "One per line",
  saveFailed: "Couldn’t save.",
  conflict: "The plan just changed and was reloaded; please make the edit again.",
  revision: (n: number) => `Version ${n}`,
  byApp: "by the app",
  byUser: "by you",
  byHold: "by a stop",
  history: "History",
  historyNone: "No history yet.",
  jumpToMessage: "Jump to that message",
  tickets: "Tickets",
  ticketsNone: "No tickets yet.",
  ticketCounts: (open: number, total: number) => `${open} open · ${total} total`,
  worker: (name: string, started = true) => (started ? `${name} is on it` : `For ${name}`),
  /** Who made a ticket that is closed (approved, dropped): nobody is still on it. */
  workerDone: (name: string) => `By ${name}`,
  nobody: "Nobody yet",
  artifacts: (n: number) => `${n} file${n === 1 ? "" : "s"}`,
  jumpToTurn: "Jump to this turn",
  changeStatus: "Change status",
  segmentSpec: "Plan",
  segmentTickets: "Tickets",
  segmentBoard: "Board",
  segmentTrace: "Trace",
  showSpec: "Show the plan alongside",
  hideSpec: "Hide the plan",
  showTickets: "Show tickets alongside",
  hideTickets: "Hide tickets",
  showBoard: "The five columns take the whole area",
  hideBoard: "Put the board away and see the trace",
  /** The five columns, and a move that waits because a hand-over is still open. */
  board: {
    emptyColumn: "No tickets",
    focusClear: "Don't just show this column",
    dragHint: "Drag a card to another column to change its status; on touch, use the status menu",
    pendingMove: (column: string) => `Moving it to “${column}” drops the hand-over still waiting for you to approve or send back; moving it to done marks it approved.`,
    moveAnyway: "Move it anyway",
    keep: "Leave it",
    conflictDropped: "The plan just changed, so the moves that had not gone through are back."
  },
  links: {
    ticketsHint: "Every ticket meets the plan’s done-when lines, rules and what you asked for. Pick one: the board lights its turns and it lists what it has to meet.",
    heldTo: "Has to meet",
    planWide: (parts: string) => `The plan’s ${parts}, as every ticket does`,
    join: ", ",
    acceptanceCount: (n: number) => `${n} done-when line${n === 1 ? "" : "s"}`,
    rulesCount: (n: number) => `${n} rule${n === 1 ? "" : "s"}`,
    requirementsCount: (n: number) => `${n} thing${n === 1 ? "" : "s"} you asked for`,
    planWideNone: "The plan has no done-when lines or rules yet, and nothing you asked for is written down.",
    onlyThis: "For this ticket alone",
    showSpec: "See in the plan",
    focus: "Looking at ticket",
    focusHint: "It has to meet the lines below; those held to another ticket alone are dimmed.",
    showTicket: (label: string) => `Show ticket ${label}`,
    clearFocus: "Stop looking at this ticket",
    ticketStates: "Tickets",
    progressHint: "This row is where the tickets stand; below is the organizer’s written account of the work."
  },
  dormant: "Dormant",
  dormantHint: "Set aside when its conversation was cleared or deleted; it wakes when you mention it again or edit it on the board",
  lastChange: (ago: string, what: string) => `Last change ${ago} (${what})`,
  ago: {
    now: "just now",
    minute: (n: number) => `${n} min ago`,
    hour: (n: number) => `${n} h ago`,
    day: (n: number) => `${n} d ago`
  },
  requirements: {
    title: "What you asked for",
    hint: "Each stands on words you said; this is the list the Bots read in their situation.",
    none: "Nothing written down yet.",
    inherited: (title: string, count: number) => `${count} inherited from “${title}”`,
    proposed: "Waiting for you",
    proposedHint: "Not in force until you confirm.",
    unverified: "Old rules (source unverified)",
    unverifiedHint: "For reference only, holding nothing back; confirm the ones you said.",
    excluded: "Not for this job",
    said: (n: number) => `said ${n} times`,
    saidAcross: (n: number, plans: number) => `said ${n} times (across ${plans} jobs)`,
    restated: (text: string) => `Restated: ${text}`,
    replaces: (seq: number, quote: string) => `would replace R-${seq} “${quote}”`,
    scope: {
      ticket: (label: string) => `For ticket ${label}`,
      plan: "For this job",
      project: "For every job in this conversation",
      standing: (domain: string | null) => (domain === "video" ? "For every video job" : domain ? `Standing (${domain})` : "Standing")
    },
    source: {
      message: "You said",
      ask_answer: "Your answer",
      annotation: "Your annotation",
      board: "You wrote on the board",
      legacy: "Old rule",
      capture: "Your words, kept whole"
    },
    jump: "See the words",
    confirm: "Confirm",
    reject: "Not a requirement",
    waive: "No longer holds",
    notHere: "Not for this job",
    hereAgain: "Restore",
    wholeProject: "For the whole conversation",
    failed: "That did not work; try again."
  },
  retrospective: {
    title: "Retrospective",
    hint: "Once this job was delivered, the Bots that made it looked back on it: where they tripped up, which of their ways made you send work back, what to do again — and changed their own memories and skills. Every change can be taken back.",
    running: (bot: string) => `${bot} is looking back…`,
    failed: {
      call_failed: "The retrospective did not run: the model call failed. Nothing was changed.",
      truncated: "The retrospective did not run: its answer was cut off. Nothing was changed.",
      unreadable: "The retrospective did not run: its answer could not be read. Nothing was changed.",
      interrupted: "The retrospective did not run: a restart cut it off. Nothing was changed.",
      no_model: "The retrospective did not run: no model was available. Nothing was changed.",
      other: "The retrospective did not run. Nothing was changed."
    },
    pitfalls: "Where it tripped up",
    reworkCauses: "What made you send work back",
    keep: "Do again next time",
    earlier: "Earlier conclusions",
    verdict: { held: "still holds", recurred: "happened again", obsolete: "no longer holds" },
    changes: "Changes",
    noChanges: "No memory or skill changed.",
    change: {
      memoryNew: (label: string) => `New memory "${label}"`,
      memoryRewrite: (label: string) => `Rewrote memory "${label}"`,
      memoryForget: (label: string) => `Deleted memory "${label}"`,
      skillEdit: (label: string) => `Changed skill "${label}"`,
      skillCreate: (label: string) => `New skill "${label}"`
    },
    undo: "Undo",
    undone: "Undone",
    undoChanged: "Not undone: it was changed again since, and is new now.",
    undoFailed: "That did not work; try again.",
    showDiff: "What changed",
    before: "Before",
    after: "Now",
    notApplied: (reason: string) => `Not made: ${reason}`,
    reason: {
      off: "you turned it off",
      full: "it is full",
      over_cap: "past what one retrospective may change",
      unchanged: "the same as before",
      missing: "there is no such one",
      project_skill: "a project skill is not the Bot's to change",
      name_taken: "a skill of that name exists",
      project_name: "a project skill has that name",
      too_long: "too long",
      required: "something was missing",
      edit_missing: (n: number) => `edit ${n}: the passage it names is not in the skill`,
      edit_repeated: (n: number, times: number) => `edit ${n}: the passage it names is in the skill ${times} times`,
      edit_not_one_sentence: (n: number) => `edit ${n}: a correction changes one sentence at a time`,
      edit_unread: (n: number) => `edit ${n}: the skill was too long to read, so it can only be added to at its end`,
      drops: (names: string) => `it would drop ${names}`,
      refused: "refused"
    }
  }
};
