import type { CopyShape } from "./shape.ts";

export const zh = {
  intro: "应用写给模型的话。改动从下一次调用起生效，随时能撤销；也可以让 Bot 来改，经你批准。",
  search: "搜索提示词",
  noMatch: "没有对得上的提示词",
  filter: { all: "全部", edited: "已改" },
  groups: { turn: "每一轮的系统指令", agent: "Claude Agent", tool: "工具说明", call: "应用自己的调用" },
  toolsNote: "模型看到的每个工具是做什么的；参数的说明不在这里。",
  state: { default: "默认", edited: "已改", conflict: "默认已更新 · 有冲突" },
  editedBy: (who: string) => `${who}改的`,
  you: "你",
  app: "应用",
  aBot: "Bot",
  parseFailures: (n: number) => `读不懂 ${n} 次`,
  parseFailuresSinceEdit: (n: number) => `自这次修改起，回答读不懂 ${n} 次`,
  parseFailuresWeek: (n: number) => `近 7 天回答读不懂 ${n} 次`,
  back: "返回",
  language: { zh: "中文", en: "English" },
  onlyLanguage: (lang: string) => `只有${lang}版本：不论应用用什么语言，这一段都用它。`,
  onlyLanguageShort: (lang: string) => `只有${lang}版`,
  view: { text: "内容", compare: "对比默认", history: "修改记录" },
  editorLabel: "可改的部分",
  saving: "保存中…",
  saved: "已保存",
  unsaved: "未保存",
  changedElsewhere: "刚被改过，已载入最新。",
  copyMine: "复制我没保存的",
  copied: "已复制",
  placeholdersTitle: "占位符",
  placeholdersHint: "应用会把内容填进这些位置",
  placeholderRule: { once: "保留恰好一次", at_least_once: "至少保留一次" },
  formatTitle: "输出格式（应用固定）",
  formatNote: "代码按这个格式读回答，所以它锁着；你文字里 {format} 的位置就是它插进去的地方。",
  sameAsDefault: "和默认一样",
  reset: "恢复默认",
  resetConfirmTitle: "恢复默认？",
  resetConfirmBody: "你的版本会换回应用自带的默认文字。这一步也记进修改记录，能撤销。",
  cancel: "取消",
  conflictTitle: "默认已更新，和你的版本合不上",
  conflictBody: "现在用的仍是你的版本。看看默认改了什么，再决定留哪个。",
  conflictShow: "看默认改了什么",
  conflictHide: "收起",
  conflictKeep: "保留我的版本",
  conflictTake: "换成新的默认",
  history: "修改记录",
  noHistory: "还没有改过。",
  op: { edit: "修改", reset: "恢复默认", merge: "合并了新默认", keep_mine: "保留了你的版本", undo: "撤销", restore: "恢复了旧版" },
  openMessage: "看那条消息",
  undo: "撤销",
  restoreVersion: "恢复这一版",
  showChange: "看改动",
  hideChange: "收起",
  asDefault: "（默认）",
  errors: {
    prompt_empty: "不能是空的。",
    prompt_too_long: (max: string) => `太长了：最多 ${max} 个字。`,
    prompt_placeholder_missing: (name: string) => `少了 ${name}。`,
    prompt_placeholder_repeated: (name: string) => `${name} 只能出现一次。`,
    prompt_placeholder_unknown: (name: string) => `${name} 不是这一段能用的占位符。`,
    prompt_brace: "这一段不能有大括号：它的回答是从第一个大括号读起的。",
    prompt_control_chars: "里面有看不见的控制字符。",
    prompt_locale: "这一段没有这个语言的版本。",
    changed_since: "之后又改过了，先撤销更新的那次。",
    other: "没保存上，再试一次。",
  },
  loadFailed: "读不出来，稍后再试。",
  card: {
    expand: "展开全部",
    collapse: "收起",
    undo: "撤销这次修改",
    undone: "已撤销",
    undoFailed: "撤销不了：之后又改过了",
    openSettings: "在设置里看",
  },
};

export const en: CopyShape<typeof zh> = {
  intro: "What the app tells models. A change applies from the next call on and can always be undone; Bots can propose changes too, with your approval.",
  search: "Search prompts",
  noMatch: "No prompt matches",
  filter: { all: "All", edited: "Edited" },
  groups: { turn: "Every turn", agent: "Claude Agent", tool: "Tool descriptions", call: "The app's own calls" },
  toolsNote: "What each tool is for, as models see it; parameter descriptions are not here.",
  state: { default: "Default", edited: "Edited", conflict: "New default · conflict" },
  editedBy: (who: string) => `by ${who}`,
  you: "you",
  app: "the app",
  aBot: "a Bot",
  parseFailures: (n: number) => `${n} unreadable`,
  parseFailuresSinceEdit: (n: number) => `${n} answer(s) unreadable since this edit`,
  parseFailuresWeek: (n: number) => `${n} answer(s) unreadable in the last 7 days`,
  back: "Back",
  language: { zh: "Chinese", en: "English" },
  onlyLanguage: (lang: string) => `${lang} only: this one is used whatever language the app is in.`,
  onlyLanguageShort: (lang: string) => `${lang} only`,
  view: { text: "Text", compare: "Diff vs default", history: "History" },
  editorLabel: "Editable part",
  saving: "Saving…",
  saved: "Saved",
  unsaved: "Not saved",
  changedElsewhere: "It was just changed; the latest is loaded.",
  copyMine: "Copy my unsaved text",
  copied: "Copied",
  placeholdersTitle: "Placeholders",
  placeholdersHint: "The app fills these in",
  placeholderRule: { once: "keep exactly once", at_least_once: "keep at least once" },
  formatTitle: "Answer format (fixed)",
  formatNote: "Code reads the answer in this format, so it is locked; it goes where {format} sits in your text.",
  sameAsDefault: "Same as the default",
  reset: "Restore default",
  resetConfirmTitle: "Restore the default?",
  resetConfirmBody: "Your version is replaced by the text the app ships. This is recorded in the history too, and can be undone.",
  cancel: "Cancel",
  conflictTitle: "A newer default does not merge with your version",
  conflictBody: "Your version is still the one in use. See what the default changed, then choose.",
  conflictShow: "See what the default changed",
  conflictHide: "Hide",
  conflictKeep: "Keep my version",
  conflictTake: "Take the new default",
  history: "History",
  noHistory: "Not changed yet.",
  op: { edit: "Edited", reset: "Restored default", merge: "Merged the new default", keep_mine: "Kept your version", undo: "Undid", restore: "Restored an earlier version" },
  openMessage: "Open the message",
  undo: "Undo",
  restoreVersion: "Restore this version",
  showChange: "Show change",
  hideChange: "Hide",
  asDefault: "(default)",
  errors: {
    prompt_empty: "It cannot be empty.",
    prompt_too_long: (max: string) => `Too long: at most ${max} characters.`,
    prompt_placeholder_missing: (name: string) => `${name} is missing.`,
    prompt_placeholder_repeated: (name: string) => `${name} may appear only once.`,
    prompt_placeholder_unknown: (name: string) => `${name} is not a placeholder this prompt has.`,
    prompt_brace: "This one cannot hold a brace: its answer is read from the first one.",
    prompt_control_chars: "It contains invisible control characters.",
    prompt_locale: "This prompt has no version in that language.",
    changed_since: "It changed since; undo the newer change first.",
    other: "Not saved; try again.",
  },
  loadFailed: "Could not load it; try again later.",
  card: {
    expand: "Show all",
    collapse: "Show less",
    undo: "Undo this change",
    undone: "Undone",
    undoFailed: "Cannot undo: it changed since",
    openSettings: "Open in settings",
  },
};
