import { enHost, zhHost } from "./platform-words.ts";
import type { CopyShape } from "./shape.ts";

export const zh = {
  pairTitle: "配对访问设备",
  pairLead: "用 Mac 上显示的配对内容完成本设备登记。新设备必须人在 Mac 旁确认。",
  pairHint: "只粘贴 Mac 上给的配对内容。不要把它当成网址打开，也不要写进查询串或日志。",
  pairPaste: "配对内容",
  pairSubmit: "提交并等待 Mac 确认",
  pairWaiting: "已发给这台 Mac，等待本地确认…",
  pairExpired: "配对窗口已过期。请在 Mac 上重新打开配对。",
  pairRejected: "配对被拒绝或取消。",
  pairInvalid: "配对内容无效。",
  pairUrl: "配对内容不能是网址或查询串。",
  fingerprint: "主机签名指纹",
  experimental: "实验性远控。公网配对默认关闭；S-rev、G-uv 与真机 L1 尚未通过。",
  uvNeeded: "高危动作需要本设备 WebAuthn 用户验证，没有点击确认替代。",
  uvFailed: "WebAuthn 登记失败。普通聊天仍可用，但不能做高危动作。",
  uvRegister: "登记本设备用户验证",
  draftConfirm: "重连后仍有未发送草稿。确认后才发送，不会自动重放。",
  draftSend: "确认发送草稿",
  draftDiscard: "丢弃草稿",
  statusOff: "远控关闭",
  statusUnavailable: "原生凭据不可用",
  statusGated: "远控激活仍关闭",
  statusConnecting: "正在连接中继",
  statusOnline: "远控在线",
  statusDisconnected: "远控已断开",
  statusMismatch: "远控信任不匹配",
  devices: (n: number) => `已配对设备 ${n}`,
  noOfflineQueue: "没有离线命令队列。结果未知时查询同一请求回执，不换新编号重发。",
  maintenance: "维护",
  maintenanceLead: "状态、脱敏诊断和受控重启只走已加密会话。超时或掉线不会自动强制。",
  version: (v: string) => `版本 ${v}`,
  modeWindow: "窗监督",
  modeStandalone: "独立运行时",
  modeNone: "无监督者",
  restartAvailable: "可由当时监督者拉起",
  restartUnavailable: "重启不可用：窗不在且未独立。不会安装后台任务。",
  drainRunning: "运行中",
  drainWaiting: (n: number) => `正在排空，剩余 ${n} 个活轮`,
  drainDrained: "已排空",
  drainForced: "已强制中断",
  refreshStatus: "刷新状态",
  downloadDiagnostics: "下载脱敏诊断",
  drainRestart: "排空后重启",
  forceRestart: "强制中断并重启",
  forceWarn: "强制会中断活轮且不重放工具。必须新的用户验证，不能点确认代替。",
  forceConfirm: "确认强制重启",
  stopRuntime: "停止运行时",
  stopWarn: "停止会写入闩并退出。监督者不会再拉起，直到本机清除停止闩。",
  stopConfirm: "确认停止",
  revokeOther: "吊销其它设备",
  revokeConfirm: (name: string) => `确认吊销 ${name}`,
  noOtherDevices: "没有可吊销的其它设备。",
  reconnectHint: "重连只查询状态和同一请求回执，不会再触发重启。",
  errorDraining: "运行时正在排空，新请求被拒绝。",
  errorUnavailable: "当前没有可用的监督者，不能远程重启。",
  errorCancelled: "排空等待已取消。没有自动强制。",
  errorUv: "需要新鲜的 WebAuthn 用户验证。",
  errorUnknown: "结果未知。请查询同一回执，不要换新编号。",
  push: "待办推送",
  pushDesc: "仅泛化提醒「Deskfolk 有待处理事项」。点击打开信使回到会话列表，不会批准或执行命令。拒绝或过期不影响待办。iOS 需 16.4+ 主屏幕；真机主屏幕门尚未通过。",
  pushDenied: "系统已拒绝通知。待办仍标在对应会话上。",
  pushUnsupported: "此浏览器不支持 Web Push。",
  pushFailed: "未能更新推送订阅。",
  hostPair: "配对新设备",
  hostPairPaste: "在设备上打开中继地址，把这段粘进配对页。它带一次性密钥，十分钟后失效，别写进日志或聊天记录。",
  hostPairFingerprint: "核对设备上显示的主机指纹，对得上再继续。",
  hostPairEmpty: `还没有设备配对到这台${zhHost.trimEnd()}。`,
  connectedDevices: "已连接设备",
  connectedDevicesEmpty: "还没有已连接设备。",
  lastActive: (value: string) => `最近活跃于 ${value}`,
  lastActiveUnknown: "最近活跃时间未知",
  removeDevice: "移除设备",
  removeDeviceConfirm: (name: string) => `确认移除 ${name}`,
  deviceActionFailed: "设备操作失败，请重试。",
  confirmNeedsHello: "这台电脑还没设 Windows Hello：先在 Windows 设置 → 账户 → 登录选项 里设一个 PIN（或人脸、指纹），再批准一次。",
  hostPairRetry: "重新开一个窗口",
  hostPairWaiting: "等待设备提交…",
  hostPairArrived: (name: string) => `${name} 请求配对。`,
  hostPairCompare: "这串要和设备上显示的一致。",
  hostPairApprove: "批准这台设备",
  hostPairDone: `已配对。设备现在可以连上这台${zhHost.trimEnd()}。`,
  hostPairExpired: "配对窗口已过期，重新开一个。",
  hostPairFailed: "开配对窗口失败。",
  hostConnectIntro: `先把这台${zhHost}接到你自己的中继上，才能配对设备。三项都在部署中继时准备好了：中继地址、RELAY_ID，和 bootstrap 文件里的令牌。`,
  hostConnectOrigin: "中继地址",
  hostConnectRelayId: "中继 ID",
  hostConnectToken: "一次性 bootstrap 令牌",
  hostConnectTokenHint: "令牌只能用一次。接好后把两台机器上的 bootstrap 文件清空。",
  hostConnect: "接入中继",
  hostConnectInvalidOrigin: "中继地址是 https:// 开头、不带路径的网址。",
  hostConnectInvalidRelayId: "中继 ID 只含字母、数字、- 和 _，最多 64 个字符。",
  hostConnectInvalidToken: "令牌是 43 个字符：字母、数字、- 和 _。",
  hostConnectRefused: "中继没收这个令牌。令牌只能用一次：从中继的 bootstrap 文件取一个新的，并确认中继开着配对（RELAY_PAIRING_ENABLED=1）。",
  hostConnectUnreachable: "这个地址上连不到中继。",
  hostConnectFailed: "没能接入。检查中继地址和中继 ID。",
  setupChannelLost: "这个窗口打开时运行时已经在跑，窗口管不到它的远控设置。退出 Deskfolk 再打开。",
  setupNeedsDevSwitch: "从源码运行时，要带 REAL_BOT_DEV_REMOTE=1 启动（REAL_BOT_DEV_REMOTE=1 pnpm dev）才能在这里接入中继；安装的应用不需要。",
  relayGuideSummary: "还没有中继？部署到你自己的服务器",
  relayGuideLead: `中继是一个很小的转发服务，放在你自己的服务器和域名上：${zhHost.trimStart()}只往外连它，它只转发自己解不开的密文。准备一台装好 Docker Compose 的 Linux 服务器（80、443 端口空着），和一个解析到它的域名。`,
  relayGuidePrepare: "以 root 登录服务器，取代码、建数据目录、生成一次性令牌：",
  relayGuideEnv: "写配置。复制下面这段，先把域名和邮箱换成你的、RELAY_ID 起一个自己认得的名字，再在服务器上执行：",
  relayGuideUp: "在 deskfolk 目录里构建并启动（第一次要几分钟），再自检：",
  relayGuideUpNote: "浏览器打开 https://你的域名，看到配对页就成了。",
  relayGuideFill: `回到这里填下面三项：中继地址是 https:// 加你的域名，中继 ID 是 RELAY_ID，令牌是服务器上 /srv/deskfolk-relay/bootstrap 的内容。把这个文件拷到${zhHost}上再从里面复制，别经过聊天。`,
  relayGuidePairingOff: "手机配好以后把配对关掉；要配下一台时再改回 1：",
  relayGuideCopy: "复制",
  relayGuideFull: "完整部署指南",
  relayGuideFullNote: "不用 Docker（比如服务器上已有 nginx 占着 80/443）、限额和出错排查，都在指南里。",
};

export const en: CopyShape<typeof zh> = {
  pairTitle: "Pair this device",
  pairLead: "Use the pairing payload shown on the Mac to enroll this device. A person must confirm the new device at the Mac.",
  pairHint: "Paste only the pairing content from the Mac. Do not open it as a URL or put it in a query string or log.",
  pairPaste: "Pairing payload",
  pairSubmit: "Submit and wait for Mac confirmation",
  pairWaiting: "Sent to the Mac; waiting for local confirmation…",
  pairExpired: "The pairing window expired. Open a new pair on the Mac.",
  pairRejected: "Pairing was rejected or cancelled.",
  pairInvalid: "That pairing payload is invalid.",
  pairUrl: "Pairing payload cannot be a URL or query string.",
  fingerprint: "Host signing fingerprint",
  experimental: "Experimental remote access. Public pairing stays default-off; S-rev, G-uv and physical L1 have not passed.",
  uvNeeded: "High-risk actions need WebAuthn user verification on this device. There is no click-to-confirm fallback.",
  uvFailed: "WebAuthn registration failed. Ordinary chat still works; high-risk actions stay disabled.",
  uvRegister: "Register user verification on this device",
  draftConfirm: "An unsent draft survived reconnect. Confirm before sending; nothing is replayed automatically.",
  draftSend: "Confirm send draft",
  draftDiscard: "Discard draft",
  statusOff: "Remote is off",
  statusUnavailable: "Native credentials unavailable",
  statusGated: "Remote activation remains gated",
  statusConnecting: "Connecting to the relay",
  statusOnline: "Remote online",
  statusDisconnected: "Remote disconnected",
  statusMismatch: "Remote trust mismatch",
  devices: (n: number) => `${n} paired devices`,
  noOfflineQueue: "There is no offline command queue. Unknown results look up the same request receipt instead of sending a new id.",
  maintenance: "Maintenance",
  maintenanceLead: "Status, redacted diagnostics and controlled restart stay on the encrypted session. Timeouts and disconnects never auto-force.",
  version: (v: string) => `Version ${v}`,
  modeWindow: "Window supervised",
  modeStandalone: "Independent runtime",
  modeNone: "No supervisor",
  restartAvailable: "The current supervisor can relaunch",
  restartUnavailable: "Restart is unavailable: the window is gone and independent mode is off. No background job is installed.",
  drainRunning: "Running",
  drainWaiting: (n: number) => `Draining; ${n} live turns remaining`,
  drainDrained: "Drained",
  drainForced: "Force-interrupted",
  refreshStatus: "Refresh status",
  downloadDiagnostics: "Download redacted diagnostics",
  drainRestart: "Drain then restart",
  forceRestart: "Force-interrupt and restart",
  forceWarn: "Force interrupts live turns and does not replay tools. A fresh user verification is required; click-to-confirm is not enough.",
  forceConfirm: "Confirm force restart",
  stopRuntime: "Stop runtime",
  stopWarn: "Stop writes the latch then exits. The supervisor will not relaunch until the stop latch is cleared on the Mac.",
  stopConfirm: "Confirm stop",
  revokeOther: "Revoke other devices",
  revokeConfirm: (name: string) => `Confirm revoke ${name}`,
  noOtherDevices: "No other devices to revoke.",
  reconnectHint: "Reconnect only queries status and the same request receipt. It does not start another restart.",
  errorDraining: "The runtime is draining; new requests are rejected.",
  errorUnavailable: "No supervisor is available for a remote restart.",
  errorCancelled: "The drain wait was cancelled. Nothing was auto-forced.",
  errorUv: "Fresh WebAuthn user verification is required.",
  errorUnknown: "The result is unknown. Look up the same receipt instead of minting a new id.",
  push: "Pending-item push",
  pushDesc: "Generic reminders only: “Deskfolk has pending items”. A click opens the messenger on the chat list; it never approves or sends commands. Deny or expiry does not drop pending items. iOS needs 16.4+ home screen; the physical G-push gate has not passed.",
  pushDenied: "Notifications are blocked. Pending state stays on the conversation.",
  pushUnsupported: "This browser does not support Web Push.",
  pushFailed: "Could not update the push subscription.",
  hostPair: "Pair a device",
  hostPairPaste: "Open the relay address on the device and paste this into its pairing screen. It carries a one-time secret, expires in ten minutes, and does not belong in logs or chats.",
  hostPairFingerprint: "Check the host fingerprint the device shows against this one.",
  hostPairEmpty: `No device is paired with this ${enHost} yet.`,
  connectedDevices: "Connected devices",
  connectedDevicesEmpty: "No connected devices yet.",
  lastActive: (value: string) => `Last active ${value}`,
  lastActiveUnknown: "Last active time unknown",
  removeDevice: "Remove device",
  removeDeviceConfirm: (name: string) => `Confirm remove ${name}`,
  deviceActionFailed: "The device action failed. Try again.",
  confirmNeedsHello: "Windows Hello is not set up on this computer: set a PIN (or face or fingerprint) under Windows Settings → Accounts → Sign-in options, then approve again.",
  hostPairRetry: "Open a new window",
  hostPairWaiting: "Waiting for the device to submit…",
  hostPairArrived: (name: string) => `${name} is asking to pair.`,
  hostPairCompare: "This has to match what the device is showing.",
  hostPairApprove: "Approve this device",
  hostPairDone: `Paired. The device can reach this ${enHost} now.`,
  hostPairExpired: "The pairing window expired; open a new one.",
  hostPairFailed: "Could not open a pairing window.",
  hostConnectIntro: `Connect this ${enHost} to your own relay before pairing a device. You made all three when you set the relay up: its address, its RELAY_ID, and the token in its bootstrap file.`,
  hostConnectOrigin: "Relay address",
  hostConnectRelayId: "Relay ID",
  hostConnectToken: "One-time bootstrap token",
  hostConnectTokenHint: "The token works once. Empty the bootstrap file on both machines afterwards.",
  hostConnect: "Connect to relay",
  hostConnectInvalidOrigin: "The relay address is an https:// URL with no path.",
  hostConnectInvalidRelayId: "The relay ID is letters, digits, - and _, up to 64 characters.",
  hostConnectInvalidToken: "The token is 43 characters: letters, digits, - and _.",
  hostConnectRefused: "The relay refused the token. Each token works once: take a fresh one from the relay's bootstrap file, and check the relay has pairing on (RELAY_PAIRING_ENABLED=1).",
  hostConnectUnreachable: "No relay answered at that address.",
  hostConnectFailed: `Could not connect this ${enHost}. Check the relay address and relay ID.`,
  setupChannelLost: "The runtime was already running when this window opened, so this window cannot set up remote access. Quit Deskfolk and open it again.",
  setupNeedsDevSwitch: "A source run sets up remote access here only when started with REAL_BOT_DEV_REMOTE=1 (REAL_BOT_DEV_REMOTE=1 pnpm dev). The installed app needs no switch.",
  relayGuideSummary: "No relay yet? Deploy one on your own server",
  relayGuideLead: `The relay is a small forwarding service on your own server and domain: the ${enHost} only connects out to it, and it only forwards ciphertext it cannot read. You need a Linux server with Docker Compose and ports 80 and 443 free, and a domain pointing at it.`,
  relayGuidePrepare: "As root on the server, fetch the code, create the data directories and a one-time token:",
  relayGuideEnv: "Write the configuration. Copy this, put in your own domain and email and a RELAY_ID you will recognize, then run it on the server:",
  relayGuideUp: "In the deskfolk directory, build and start (the first build takes a few minutes), then check:",
  relayGuideUpNote: "Open https://your-domain in a browser; the pairing page means it works.",
  relayGuideFill: `Come back and fill in the three fields below: the relay address is https:// plus your domain, the relay ID is RELAY_ID, and the token is the content of /srv/deskfolk-relay/bootstrap on the server. Copy that file to the ${enHost} and paste from it; keep it out of chats.`,
  relayGuidePairingOff: "Once the phone is paired, turn pairing off; set it back to 1 to pair the next one:",
  relayGuideCopy: "Copy",
  relayGuideFull: "Full deployment guide",
  relayGuideFullNote: "Running without Docker (say, nginx already holds 80/443), quotas and troubleshooting are all in the guide.",
};
