import type { CopyShape } from "./shape.ts";

export const zh = {
  tab: "分工",
  intro: "应用自己发起的每个模型调用，画在它跑的地方：什么时候跑、用哪个模型、照哪几段提示词。点开一个，设它的模型、改它的提示词。",
  mapLabel: "调用分工图",
  lanes: {
    line: "你的一句话",
    group: "群里没点名的一句",
    accepted: "你接受一件交付",
    overturned: "你推翻一次放行",
    compose: "你按 ✨",
  },
  edges: {
    wakes: "读完才叫醒",
    aside: "同时记下，不挡",
    nearFull: "上下文快满时",
    settle: "活停下来后",
    handedIn: "交上来时",
    joins: "要接就进 Bot 一轮",
  },
  model: "模型",
  prompts: "提示词",
  follows: { default: "跟默认模型", bot: "跟 Bot 的模型" },
  older: "这台 Mac 上的应用较旧，这个调用还不能单独选模型。",
  noEndpoint: "先在「模型」里加一个端点，才能给它单独选模型；提示词照样能改。",
  noPrompts: "这台 Mac 上的应用还没说哪几段提示词属于这个调用，到「提示词」页里找。",
  promptsLoadFailed: "提示词没读出来，过一会再打开设置。",
  edited: (n: number) => `改了 ${n} 段`,
  conflict: "提示词有冲突",
  failures: (n: number) => `读不懂 ${n} 次`,
  turn: {
    name: "Bot 一轮",
    hint: "Bot 自己干活的一轮，用这个 Bot 设的模型；一件活连着没过时，按模型阶梯往上换。每一轮都带着系统指令、技能、记忆和工具说明这些提示词。这两样不在这页设。",
    model: "Bot 自己的模型",
    ladder: (rungs: string) => `阶梯：${rungs}`,
    toLadder: "设模型阶梯",
    toPrompts: "改每一轮的提示词",
  },
  promptsMoved: "读句、整理器这些应用自己调用的提示词，和它们的模型一起在「分工」页。",
  toRouting: "去分工页",
  summary: (changed: number) => (changed > 0 ? `改过 ${changed} 个调用` : "全部照旧"),
};

export const en: CopyShape<typeof zh> = {
  tab: "Roles",
  intro: "Every model call the app makes on its own, drawn where it runs: when it runs, on which model, with which prompts. Open one to set its model and edit its prompts.",
  mapLabel: "Map of the app's calls",
  lanes: {
    line: "A line of yours",
    group: "A group line naming nobody",
    accepted: "You accept a delivery",
    overturned: "You overturn an approval",
    compose: "You press ✨",
  },
  edges: {
    wakes: "wakes a Bot once read",
    aside: "written down beside it",
    nearFull: "near the context window",
    settle: "once the work goes quiet",
    handedIn: "when a part is handed in",
    joins: "a Bot that takes it up goes on to its turn",
  },
  model: "Model",
  prompts: "Prompts",
  follows: { default: "Follows the default model", bot: "Follows the Bot's model" },
  older: "The app on this Mac is older; this call's model cannot be chosen yet.",
  noEndpoint: "Add an endpoint under Models to give it a model of its own; its prompts can still be edited.",
  noPrompts: "The app on this Mac does not say which prompts belong to this call yet; find them under Prompts.",
  promptsLoadFailed: "The prompts could not be read; open settings again in a moment.",
  edited: (n: number) => (n === 1 ? "1 prompt edited" : `${n} prompts edited`),
  conflict: "A prompt conflicts",
  failures: (n: number) => (n === 1 ? "1 answer unread" : `${n} answers unread`),
  turn: {
    name: "A Bot's turn",
    hint: "A Bot working on its own, on the model set for that Bot; a job that keeps failing moves up the model ladder. Every turn carries the system instructions, skills, memories and tool descriptions. Neither is set on this page.",
    model: "The Bot's own model",
    ladder: (rungs: string) => `Ladder: ${rungs}`,
    toLadder: "Set the model ladder",
    toPrompts: "Edit every turn's prompts",
  },
  promptsMoved: "The prompts of the app's own calls (line reading, the organizer and the rest) are on the Roles page, with their models.",
  toRouting: "Open Roles",
  summary: (changed: number) => (changed === 0 ? "All as before" : changed === 1 ? "1 call changed" : `${changed} calls changed`),
};
