import { enHost, isWindows, zhHost } from "./platform-words.ts";
import type { CopyShape } from "./shape.ts";

export const zh = {
  title: "Mac 屏幕",
  connecting: "正在连接 Mac 屏幕…",
  loading: "正在加载远程屏幕…",
  linking: "正在连接 Mac…",
  waitingMac: "正在等 Mac 的屏幕共享回应…",
  noAnswer: "Mac 的屏幕共享没有回应。",
  direct: "直连",
  relay: "经中继",
  relayHint: "没能直连，画面经中继传，会慢一些",
  reconnect: "重新连接",
  disconnect: "断开",
  signInTitle: "登录这台 Mac 的屏幕共享",
  signInHint: "用 Mac 上的账户名和登录密码。",
  keepSignIn: "记住，下次自动登录（存在这台手机上）",
  receiving: (total: string, rate: string) => `正在接收画面 · ${total} MB · ${rate} MB/s`,
  username: "账户名",
  password: "密码",
  signIn: "连接",
  wrongPassword: "账户名或密码不对，屏幕共享拒绝了。",
  disabledOnMac: "这台 Mac 没有允许远程屏幕。在 Mac 上打开 设置 → 远程控制，打开「允许看和操作这台 Mac 的屏幕」。",
  sharingOff: "Mac 上的「屏幕共享」没开。在 Mac 上打开 系统设置 → 通用 → 共享 → 屏幕共享。",
  ended: "连接已断开。",
  failed: "连不上 Mac 屏幕。",
  paused: "离开这页时已断开，回来会自动接回。",
  keys: "按键",
  keyboard: "键盘",
  fit: "适应屏幕",
  actualSize: "原始大小",
  trackpad: "触摸板",
  trackpadTitle: "触摸板模式：手指移动光标，点按在光标处单击",
  trackpadHint: "单指滑动移动光标，点按单击，双指点按右键，双指滑动滚动；按住不动再滑动是拖拽。",
  smooth: "流畅",
  smoothTitle: "流畅模式：连着时把 Mac 的分辨率临时降低，画面跟得更快；断开后恢复",
  smoothApplied: (size: string) => `Mac 的屏幕临时降到 ${size}，画面更流畅；断开后恢复`,
  smoothAlreadyLow: "这台 Mac 的屏幕已经不是 Retina 分辨率，没有可降的",
  smoothFailed: "Mac 没能降低分辨率，画面照旧",
  smoothUnsupported: "这台 Mac 上的 Deskfolk 还不支持流畅模式",
  macLowered: (to: string, from: string) => `为了手机上的画面流畅，屏幕临时从 ${from} 降到 ${to}，手机断开后恢复`,
  modifier: (name: string) => `${name}：作用于下一个键`,
  macToggle: `允许看和操作这台${zhHost}的屏幕`,
  macToggleDesc: isWindows
    ? "已配对的设备可以在「工具 → 电脑屏幕」里看到并操作这台电脑，锁屏时也能输密码解锁。画面和输入来自你装的 VNC 服务（推荐 TightVNC），连接时还要输它的 VNC 密码。默认关闭。"
    : "已配对的设备可以在「工具 → Mac 屏幕」里看到并操作这台 Mac，锁屏时也能输密码解锁。画面和输入来自 macOS 自带的「屏幕共享」，连接时还要输这台 Mac 的账户密码。默认关闭。",
  macSharingOn: isWindows ? "VNC 服务已就绪" : "屏幕共享已打开",
  macSharingOff: isWindows ? "没找到 VNC 服务：手机连不上" : "屏幕共享没开：手机连不上",
  macSharingSettings: isWindows ? "下载 TightVNC" : "打开共享设置",
  macVncSteps: "Windows 没有自带的屏幕共享，要装一个 VNC 服务：装 TightVNC 时选上 TightVNC Server，并让它注册成系统服务（这样锁屏和 UAC 弹窗也能操作）；设一个主密码（VNC 密码只认前 8 位）；在 TightVNC 服务的配置 → Access Control 里勾上「Allow loopback connections」，再勾「Loopback connections only」，5900 端口就只对本机开放。",
  macIceServers: "STUN / TURN 服务器",
  macIceServersDesc: `每行一个 stun: 或 turn: 地址，用来让手机直连${zhHost.trimEnd()}；留空时只在同一网络或 IPv6 下直连，连不上就经中继。turn: 地址写成 turn:主机:端口 用户名 密码。`,
  macIceSave: "保存",
  macIceInvalid: "有一行不是 stun: 或 turn: 地址。",
  macActive: (name: string, mode: string) => `${name} 正在看这台${zhHost}的屏幕（${mode}）`,
  macDisconnect: "断开",
  macTraffic: (sent: string, size: string | null) => (size ? `屏幕 ${size} · 已发出 ${sent} MB` : `已发出 ${sent} MB`),
  macFailed: "没能读取或保存远程屏幕的设置。",
  ctrlAltDel: "Ctrl+Alt+Del",
  ctrlAltDelLabel: "发送 Ctrl+Alt+Del",
};

export const en: CopyShape<typeof zh> = {
  title: "Mac screen",
  connecting: "Connecting to the Mac's screen…",
  loading: "Loading the remote screen…",
  linking: "Connecting to the Mac…",
  waitingMac: "Waiting for the Mac's Screen Sharing to answer…",
  noAnswer: "The Mac's Screen Sharing did not answer.",
  direct: "Direct",
  relay: "Via relay",
  relayHint: "No direct connection; the picture comes through the relay and is slower",
  reconnect: "Reconnect",
  disconnect: "Disconnect",
  signInTitle: "Sign in to this Mac's Screen Sharing",
  signInHint: "Use the Mac's account name and login password.",
  keepSignIn: "Remember, and sign in by itself next time (kept on this phone)",
  receiving: (total: string, rate: string) => `Receiving the picture · ${total} MB · ${rate} MB/s`,
  username: "Account name",
  password: "Password",
  signIn: "Connect",
  wrongPassword: "Screen Sharing refused that account name or password.",
  disabledOnMac: "This Mac does not allow its screen to be shown. On the Mac, open Settings → Remote access and turn on \"Allow viewing and controlling this Mac's screen\".",
  sharingOff: "Screen Sharing is off on the Mac. Turn it on in System Settings → General → Sharing → Screen Sharing.",
  ended: "Disconnected.",
  failed: "Could not reach the Mac's screen.",
  paused: "Disconnected while you were away from this page; it reconnects when you come back.",
  keys: "Keys",
  keyboard: "Keyboard",
  fit: "Fit to screen",
  actualSize: "Actual size",
  trackpad: "Trackpad",
  trackpadTitle: "Trackpad mode: your finger moves the pointer, and a tap clicks where it is",
  trackpadHint: "Slide one finger to move the pointer, tap to click, tap with two fingers to right-click, slide two fingers to scroll; hold still, then slide, to drag.",
  smooth: "Smooth",
  smoothTitle: "Smooth mode: lowers the Mac's resolution while you are connected, so the picture keeps up; it goes back when you disconnect",
  smoothApplied: (size: string) => `The Mac's screen is at ${size} for now, for a smoother picture; it goes back when you disconnect`,
  smoothAlreadyLow: "This Mac's screen is not at a Retina resolution; there is nothing to lower",
  smoothFailed: "The Mac could not lower its resolution; the picture is as before",
  smoothUnsupported: "Deskfolk on this Mac does not support smooth mode yet",
  macLowered: (to: string, from: string) => `For a smooth picture on the phone, the screen is at ${to} instead of ${from} until it disconnects`,
  modifier: (name: string) => `${name} for the next key`,
  macToggle: `Allow viewing and controlling this ${enHost}'s screen`,
  macToggleDesc: isWindows
    ? "Paired devices can see and operate this computer under Tools → Computer screen, and type the password at the lock screen. The picture and input come from a VNC server you install (TightVNC is the one to use), which asks for its VNC password on each connection. Off by default."
    : "Paired devices can see and operate this Mac under Tools → Mac screen, and type the password at the lock screen. The picture and input come from macOS's own Screen Sharing, which also asks for this Mac's account password on each connection. Off by default.",
  macSharingOn: isWindows ? "The VNC server is ready" : "Screen Sharing is on",
  macSharingOff: isWindows ? "No VNC server found: the phone cannot connect" : "Screen Sharing is off: the phone cannot connect",
  macSharingSettings: isWindows ? "Download TightVNC" : "Open Sharing settings",
  macVncSteps: "Windows has no screen sharing of its own, so install a VNC server: when installing TightVNC, choose TightVNC Server and let it register as a system service (so the lock screen and UAC prompts can be operated too); set a primary password (VNC uses only its first 8 characters); in the TightVNC service's configuration → Access Control, tick \"Allow loopback connections\", then \"Loopback connections only\", so port 5900 is open to this computer alone.",
  macIceServers: "STUN / TURN servers",
  macIceServersDesc: `One stun: or turn: address per line, for the phone to reach the ${enHost} directly. Left empty, a direct connection is tried only on the same network or over IPv6, and the relay carries it otherwise. Write a turn: address as turn:host:port username password.`,
  macIceSave: "Save",
  macIceInvalid: "A line is not a stun: or turn: address.",
  macActive: (name: string, mode: string) => `${name} is viewing this ${enHost}'s screen (${mode})`,
  macDisconnect: "Disconnect",
  macTraffic: (sent: string, size: string | null) => (size ? `Screen ${size} · ${sent} MB sent` : `${sent} MB sent`),
  macFailed: "Could not read or save the remote screen settings.",
  ctrlAltDel: "Ctrl+Alt+Del",
  ctrlAltDelLabel: "Send Ctrl+Alt+Del",
};
