import { isWindows, osName } from "./platform-words.ts";
import type { CopyShape } from "./shape.ts";

export const zh = {
  title: "设置",
  tabGeneral: "通用",
  tabNotifications: "通知",
  tabLessons: "教训",
  tabPrompts: "提示词",
  tabRemote: "远程控制",
  tabModels: "模型服务",
  tabAgents: "Agent",
  tabMcp: "MCP 扩展",
  tabAbout: "关于",
  sectionWorkspace: "工作区目录",
  workspaceSubtitle: "Bot 的文件读写与命令执行限制在此目录下",
  workspaceConfigured: "已配置",
  workspaceUnsetNotice: "未配置",
  workspaceSecurityBoundary: "工作区安全边界",
  sectionPreferences: "基础偏好",
  preferencesSubtitle: "个性化外观、显示语言与系统启动行为",
  themeDesc: "界面外观配色偏好",
  languageDesc: "界面所使用的显示语言",
  launchDesc: "系统登录时在后台自动启动 Deskfolk",
  aboutDescription: "多天、多步、要返工的活交给 Bot；Bot 说做完的，应用先核过。",
  remoteSection: "中继连接",
  remoteSubtitle: "浏览器配对身份只存在本机 IndexedDB。聊天、快照、草稿、命令和文件不持久化。",
  remoteSubtitleHost: "手机或另一台电脑经你自己部署的中继连回这里，端到端加密。实验性功能，默认关闭。",
  sectionEndpoint: "端点与鉴权",
  sectionModels: "模型配置",
  sectionMcpServers: "已配置服务器",
  sectionMcpAdd: "添加 MCP 服务器",
  wizardHint: "向导就是设置的空态：工作区路径、至少一个端点的 URL 和密钥齐了即完成。每个端点有自己的模型名单。不抢主转录。",
  wizardIncomplete: "工作区路径、端点和密钥还没齐。",
  providerName: "名称",
  providerAdd: "添加端点",
  providerEdit: "编辑端点",
  providerEmpty: "还没有模型端点。",
  providerDelete: "删除",
  providerDeleteBody: "删除后，钉了这个端点的 Bot 会改回空钉。若删的是默认端点，默认会换成剩下的第一个。",
  providerConfirmDelete: "确认删除",
  providerCancel: "取消",
  providerDefault: "默认",
  providerSetDefault: "设为默认",
  providerModelCount: (count: number) => (count === 1 ? "1 个模型" : `${count} 个模型`),
  providersHint: "管理模型端点，选择各端点的默认模型。",
  modelsSectionEndpoints: "端点",
  modelsEndpointsSummary: (count: number, defaultName: string | null) =>
    `${count} 个端点${defaultName ? ` · 默认 ${defaultName}` : ""}`,
  providerConnection: "连接",
  providerModels: "名单",
  providerDefaultModel: (name: string) => `默认模型 ${name}`,
  providerPickDefault: "设为这个端点的默认模型",
  providerNoDefault: "还没选默认模型。先启用一个，再点那一行。",
  providerNameEmpty: "填写一个名称。",
  workspace: "工作区",
  workspaceChoose: "选择文件夹",
  workspaceChange: "更换文件夹",
  workspaceUnsetValue: "尚未选择",
  workspacePickerUnavailable: "请在桌面应用里选择文件夹；浏览器开发态打不开系统对话框。",
  workspaceHostOnly: "工作区根目录只在本机窗口里改，远控不能改。",
  workspaceBrowseRemote: "在执行 Mac 上逐级浏览目录。改根仍须人在 Mac 旁确认。",
  workspaceAuthorizeMac: "在 Mac 上授权一次文件访问后再试。",
  workspaceUseFolder: "使用此目录",
  workspaceUp: "上级",
  workspaceConfirmRoot: "更换工作区根目录需要在 Mac 上确认。",
  copyRelpath: "复制相对路径",
  downloadFile: "下载",
  endpoint: "端点",
  endpointKey: "端点密钥",
  apiFormat: "接口格式",
  apiFormatOpenai: "OpenAI 兼容",
  apiFormatAnthropic: "Anthropic 兼容",
  apiFormatAnthropicShort: "Anthropic",
  apiFormatOpenaiHint: "Chat Completions 接口，地址通常以 /v1 结尾。",
  apiFormatAnthropicHint: "Anthropic Messages 接口：填 Claude Code 的 ANTHROPIC_BASE_URL 那种地址，如 https://api.anthropic.com，不带 /v1/messages。",
  keySet: "已配置",
  keyUnset: "未配置",
  keyNotNeeded: "本地，不用密钥",
  keyLocalPlaceholder: "本地模型服务可以不填",
  keyLocalHint: "这个地址在本机或局域网里：Ollama、LM Studio、llama.cpp 这类本地模型服务不用密钥，留空即可；服务自己设了密钥才填。",
  language: "语言",
  localeZh: "中文",
  localeEn: "English",
  theme: "外观",
  themeSystem: "跟随系统",
  themeLight: "亮色",
  themeDark: "暗色",
  launch: "登录启动",
  independentRuntime: "独立运行时",
  independentRuntimeDesc: "退出桌面后仍由 LaunchAgent 保活本机运行时。默认关；未通过原生封闭门时保持禁用。",
  independentRuntimeGated: "原生运行时未封闭（G-pack 未通过），不能安装独立作业。默认仍由窗口监督。",
  independentRuntimeDev: "开发态不会安装 LaunchAgent。",
  independentRuntimeBrowser: "请在桌面应用里开关此项；浏览器不能安装本机作业。",
  independentRuntimeConfirmEnable: "确认开启独立运行时",
  independentRuntimeConfirmEnableBody:
    "会先排空当前活轮，再把运行时交给用户域 LaunchAgent。失败会明确停机，不会偷偷改回窗口拉起。退出桌面不再停止任务。",
  independentRuntimeConfirmDisable: "确认关闭独立运行时",
  independentRuntimeConfirmDisableBody:
    "会先恢复窗口监督，再卸下 LaunchAgent。桌面未打开时关掉会停止远控，直到你在 Mac 上打开 Deskfolk。",
  independentRuntimeWaiting: "正在等待当前活轮结束…",
  independentRuntimeForce: "强制中断并交接",
  independentRuntimeCancel: "取消",
  independentRuntimeFailed: "独立运行时未能启动，请在 Mac 上打开 Deskfolk 或重试。",
  independentRuntimeConfirm: "确认",
  save: "保存",
  workspaceEmpty: "选择一个本机目录。",
  workspaceInvalid: "需要本机绝对路径；不能是文件。目录不存在时会自动创建。",
  endpointEmpty: "填写端点 URL。",
  endpointInvalid: "端点必须是 http 或 https 的 URL。",
  keyEmpty: "粘贴端点密钥。",
  models: "可用模型",
  modelsEmpty: "至少填一个模型名。",
  modelsFetch: "获取模型",
  modelsFetching: "获取中...",
  modelsFetchFailed: "未能获取模型列表，可手动添加模型名。",
  modelsRefetch: "重新获取",
  modelsCounts: (enabled: number, available: number) => `已启用 ${enabled} · 可用 ${available}`,
  modelsAutoFetchHint: "填好端点 URL 和密钥后会自动获取模型列表。",
  modelsFetchingHint: "正在从端点获取模型列表…",
  modelsEmptyHint: "还没有模型。获取不到时可以手动添加模型名。",
  modelsFilterAll: "全部",
  modelsFilterEnabled: "已启用",
  modelsEnabledEmpty: "还没有启用的模型，切到「全部」勾选。",
  modelsAddManual: "手动添加模型名",
  modelsAddManualPlaceholder: "端点认的模型名",
  modelsAddConfirm: "添加",
  modelCustomBadge: "手动添加",
  modelAttrsToggle: (name: string) => `${name} 的决策属性`,
  modelPriceTitle: "应用挑模型时参考的相对价格。",
  modelStrengthsAdd: "自定义",
  modelStrengthsAddPlaceholder: "例如 vision",
  modelStrengthRemove: (tag: string) => `移除 ${tag}`,
  modelSettings: "模型属性",
  modelSettingsHint: "设置选路参考价、思考等级和擅长领域。计费单价用于估算调用花费。",
  modelsSelectionHint: "点选要启用的模型，点「属性」调整模型能力。",
  modelSettingsAction: "属性",
  modelsSelectVisible: "全选结果",
  modelsClearVisible: "取消结果",
  modelsClearSearch: "清除搜索",
  modelsEnabledCount: (count: number) => `已启用 ${count} 个模型`,
  modelsManualAdded: (name: string) => `已启用 ${name}`,
  modelsAlreadyEnabled: "这个模型已经启用。",
  providerChooseDefault: "选择默认模型",
  providerEnableFirst: "先在名单中启用模型",
  modelsSelectTitle: "选择要启用的模型",
  modelsSearchPlaceholder: "搜索模型...",
  modelsSelectAll: "全选",
  modelsDeselectAll: "全不选",
  modelsManualToggle: "直接编辑文本",
  modelsListToggle: "返回列表选择",
  modelsAddCustom: "添加自定义模型",
  defaultModel: "默认模型",
  defaultModelEmpty: "挑一个默认模型。",
  defaultModelInvalid: "默认模型必须在可用名单里。",
  modelAttrsEmptyFilter: "没有匹配的模型。",
  modelAttrsDefaultBadge: "默认",
  modelPrice: "选路参考价",
  modelPriceHint: "可选，如 1.5",
  modelBilling: "计费单价",
  modelBillingUnit: "USD / 百万 token",
  modelBillingInput: "输入",
  modelBillingOutput: "输出",
  modelBillingCached: "缓存输入",
  modelBillingOptional: "可选",
  modelBillingHint: "输入和输出一起填写。缓存输入留空时使用输入单价；改动会重算这个模型以往没有实报金额的调用。",
  modelBillingInvalid: "填写完整的输入、输出单价，数值须为非负数；也可以清空整组。",
  modelBillingClear: "清空计费单价",
  modelThinking: "思考等级",
  modelThinkingAdd: "自定义",
  modelThinkingAddPlaceholder: "例如 xhigh",
  modelStrengths: "擅长领域",
  modelInputImage: "看图",
  modelInputImageYes: "能看图",
  modelInputImageNo: "看不了图",
  modelInputImageUnknown: "不确定",
  modelContextWindow: "上下文窗口（token）",
  modelContextWindowPlaceholder: "例如 32768",
  modelContextWindowHint: "模型每次最多读多少 token。知道就填，不知道留空。",
  modelContextWindowLocalHint: "本地模型服务会把它现在的设置报上来，获取模型时自动填好（Ollama 没加载这个模型时报的是模型上限）。一步的提示词明显超出时不会发出去；服务把提示词截掉了，这一轮会停下并说明。",
  modelContextWindowInvalid: "填一个正整数，或者留空。",
  modelSpeed: "速度和工具调用",
  modelSpeedRun: "测一下",
  modelSpeedRunning: "测试中…",
  modelSpeedRate: (tps: number) => `约 ${tps} token/秒`,
  modelSpeedFirstByte: (seconds: number) => `首字 ${seconds} 秒`,
  modelSpeedTools: "能调用工具",
  modelSpeedJoin: "，",
  modelSpeedNoTools: "给了工具也没有调用：这个模型多半做不了 Bot 的活，换一个支持工具调用的模型。",
  modelSpeedFailed: (reason: string) => `测试没跑完：${reason}`,
  modelSpeedError: (message: string) => `没能测：${message}`,
  modelSpeedRecorded: (tps: number) => `已记录 ${tps} token/秒`,
  modelSpeedHint: "用已保存的端点和模型发两次短请求。测到速度的六成会记下来，用来定每一步最多写多久；本地模型最需要。本地服务正替 Bot 写着的时候，要等它写完这一步才轮到测试，首字时间也会算上这段等待。",
  modelNoTools: "不支持工具",
  modelNoToolsTitle: "模型服务说这个模型不能调用工具，Bot 用它干不了活。",
  saveFailed: "没能保存。",
  retry: "重试",
  mcp: "MCP",
  mcpEmpty: "还没有 MCP 服务器。",
  mcpEdit: "编辑 MCP 服务器",
  mcpSearch: "搜索名称、传输或连接地址",
  mcpClearSearch: "清除搜索",
  mcpNoResults: "没有匹配的 MCP 服务器。",
  mcpName: "名",
  mcpTransport: "传输",
  mcpTransportStdio: "stdio",
  mcpTransportHttp: "HTTP",
  mcpCommand: "command",
  mcpArgs: "args",
  mcpUrl: "URL",
  mcpHeaders: "headers",
  mcpAuth: "Authorization",
  mcpAuthHint: isWindows ? "Bearer token。只写进 Windows 凭据管理器，不进列表。" : "Bearer token。只写进钥匙串，不进列表。",
  mcpEnabled: "启用",
  mcpAdd: "添加",
  mcpConfirmAdd: "确认添加",
  mcpConfirmEdit: "确认改连接",
  mcpCancel: "取消",
  mcpDelete: "删除",
  mcpNameEmpty: "填写一个名。",
  mcpCommandEmpty: "填写 command。",
  mcpUrlEmpty: "填写 MCP URL。",
  mcpUrlInvalid: "URL 必须是 http 或 https。",
  mcpMustConfirm: "新增和改 command / args / URL / headers 必须确认，没有 Always allow。",
  mcpUsageNote: "用法备注",
  mcpUsageNotePlaceholder: "这台用来做什么、什么时候用、什么时候不要用",
  mcpUsageNoteHint:
    "写给所有 Bot 看，每一跳都排在服务器自带说明前面。名称和备注改完即写入、不用确认，改连接也不会丢；留空就只用服务器自带的说明。",
  version: (version: string) => `版本 ${version}`,
  checkUpdates: "检查更新",
  checkingUpdates: "检查中...",
  upToDate: "已是最新版本。",
  updateAvailable: (version: string) => `有新版本 ${version} 可用。`,
  updateDownload: "下载更新",
  updateInstall: "下载并安装",
  updateInstallHint: "在应用内下载，装好自动重启，不用再过一遍安装器。",
  updateDownloading: "正在下载",
  updateVerifying: "正在校验安装包",
  updateInstalling: "正在替换应用",
  updateRestarting: "装好了，正在重启",
  updateInstallCancel: "取消",
  updateInstallRetry: "重试",
  updateInstallFailedDownload: "没能下载这个版本。",
  updateInstallFailedVerify: "下载到的安装包不是这个版本，已经丢掉。",
  updateInstallFailedInstall: "没能替换当前应用，原来这份没有动。",
  updateInstallFailedReadOnly: "没有权限替换当前这份应用，用浏览器下载后自己覆盖。",
  updateInstallFailedNotInstalled: "当前是从源码跑的，没有可替换的应用。",
  updateInstallFailedOther: "更新没装上，原来这份没有动。",
  updateNotes: "查看发布说明",
  updateChanges: "这一版改了什么",
  updateIgnore: "忽略此版本",
  updateFailed: "没能检查更新。",
};

export const en: CopyShape<typeof zh> = {
  title: "Settings",
  tabGeneral: "General",
  tabNotifications: "Notifications",
  tabLessons: "Lessons",
  tabPrompts: "Prompts",
  tabRemote: "Remote access",
  tabModels: "Models",
  tabAgents: "Agents",
  tabMcp: "MCP Servers",
  tabAbout: "About",
  sectionWorkspace: "Workspace Directory",
  workspaceSubtitle: "Root folder where bot file operations and commands run",
  workspaceConfigured: "Configured",
  workspaceUnsetNotice: "Unset",
  workspaceSecurityBoundary: "Workspace Security Boundary",
  sectionPreferences: "Preferences",
  preferencesSubtitle: "Personalize appearance, language, and launch behavior",
  themeDesc: "Color theme for the interface",
  languageDesc: "Display language for the interface",
  launchDesc: `Start Deskfolk automatically when logging into ${osName}`,
  aboutDescription: "Multi-day, multi-step jobs that need rework go to Bots; when a Bot says done, the app checks first.",
  remoteSection: "Relay connection",
  remoteSubtitle: "Browser pairing identity lives in IndexedDB only. Chat, snapshots, drafts, commands and files are not persisted.",
  remoteSubtitleHost: "A phone or another computer reaches this one through a relay you deploy yourself, end-to-end encrypted. Experimental, off by default.",
  sectionEndpoint: "Endpoint & Auth",
  sectionModels: "Model Configuration",
  sectionMcpServers: "Configured Servers",
  sectionMcpAdd: "Add MCP Server",
  wizardHint:
    "Setup is the empty settings state: workspace path, plus at least one endpoint URL and key. Each endpoint has its own model list. It does not steal the transcript.",
  wizardIncomplete: "Workspace path, endpoint, and key are not all set.",
  providerName: "Name",
  providerAdd: "Add endpoint",
  providerEdit: "Edit endpoint",
  providerEmpty: "No model endpoints yet.",
  providerDelete: "Delete",
  providerDeleteBody:
    "Bots pinned to this endpoint revert to an empty pin. If this is the default, the first remaining endpoint becomes default.",
  providerConfirmDelete: "Confirm delete",
  providerCancel: "Cancel",
  providerDefault: "Default",
  providerSetDefault: "Set as default",
  providerModelCount: (count: number) => (count === 1 ? "1 model" : `${count} models`),
  providersHint: "Manage your endpoints and choose a default model for each.",
  modelsSectionEndpoints: "Endpoints",
  modelsEndpointsSummary: (count: number, defaultName: string | null) =>
    `${count === 1 ? "1 endpoint" : `${count} endpoints`}${defaultName ? ` · default ${defaultName}` : ""}`,
  providerConnection: "Connection",
  providerModels: "Models",
  providerDefaultModel: (name: string) => `Default model ${name}`,
  providerPickDefault: "Make this the endpoint's default model",
  providerNoDefault: "No default yet. Enable a model, then click its row.",
  providerNameEmpty: "Enter a name.",
  workspace: "Workspace",
  workspaceChoose: "Choose folder",
  workspaceChange: "Change folder",
  workspaceUnsetValue: "No folder selected",
  workspacePickerUnavailable: "Choose a folder in the desktop app; the browser dev server cannot open the system dialog.",
  workspaceHostOnly: "The workspace root is set on the Mac window, not over remote.",
  workspaceBrowseRemote: "Browse directories on the execution Mac. Changing the root still needs a person at the Mac.",
  workspaceAuthorizeMac: "Authorize file access once on the Mac, then retry.",
  workspaceUseFolder: "Use this folder",
  workspaceUp: "Up",
  workspaceConfirmRoot: "Changing the workspace root requires confirmation on the Mac.",
  copyRelpath: "Copy relative path",
  downloadFile: "Download",
  endpoint: "Endpoint",
  endpointKey: "Endpoint key",
  apiFormat: "API format",
  apiFormatOpenai: "OpenAI-compatible",
  apiFormatAnthropic: "Anthropic-compatible",
  apiFormatAnthropicShort: "Anthropic",
  apiFormatOpenaiHint: "A Chat Completions API; the address usually ends in /v1.",
  apiFormatAnthropicHint: "An Anthropic Messages API: the address Claude Code takes as ANTHROPIC_BASE_URL, such as https://api.anthropic.com, without /v1/messages.",
  keySet: "Configured",
  keyUnset: "Not configured",
  keyNotNeeded: "Local, no key",
  keyLocalPlaceholder: "Not needed for a local server",
  keyLocalHint: "This address is on this computer or network: a local model server such as Ollama, LM Studio or llama.cpp takes no key, so leave it blank unless you set one on the server.",
  language: "Language",
  localeZh: "中文",
  localeEn: "English",
  theme: "Appearance",
  themeSystem: "System",
  themeLight: "Light",
  themeDark: "Dark",
  launch: "Launch at login",
  independentRuntime: "Independent runtime",
  independentRuntimeDesc: "Keep the local runtime alive with a LaunchAgent after quitting the window. Off by default; stays disabled until the sealed-native gate passes.",
  independentRuntimeGated: "The native runtime is unsealed (G-pack not passed), so an independent job cannot be installed. The window still supervises by default.",
  independentRuntimeDev: "Development mode never installs a LaunchAgent.",
  independentRuntimeBrowser: "Turn this on in the desktop app; the browser cannot install a local job.",
  independentRuntimeConfirmEnable: "Enable independent runtime",
  independentRuntimeConfirmEnableBody:
    "Live turns drain first, then the runtime is handed to a user-domain LaunchAgent. Failure stays Down; the window does not silently resume spawning. Quitting the desktop no longer stops work.",
  independentRuntimeConfirmDisable: "Disable independent runtime",
  independentRuntimeConfirmDisableBody:
    "Window supervision is restored first, then the LaunchAgent is unloaded. Turning this off without the desktop open stops remote work until you open Deskfolk on the Mac.",
  independentRuntimeWaiting: "Waiting for live turns to finish…",
  independentRuntimeForce: "Force interrupt and hand off",
  independentRuntimeCancel: "Cancel",
  independentRuntimeFailed: "The independent runtime did not start. Open Deskfolk on the Mac or retry.",
  independentRuntimeConfirm: "Confirm",
  save: "Save",
  workspaceEmpty: "Choose a local folder.",
  workspaceInvalid: "Use an absolute local path; it cannot be a file. Missing folders are created.",
  endpointEmpty: "Enter the endpoint URL.",
  endpointInvalid: "The endpoint must be an http or https URL.",
  keyEmpty: "Paste the endpoint key.",
  models: "Available models",
  modelsEmpty: "Enter at least one model name.",
  modelsFetch: "Fetch models",
  modelsFetching: "Fetching...",
  modelsFetchFailed: "Couldn't fetch models; you can add names by hand.",
  modelsRefetch: "Refetch",
  modelsCounts: (enabled: number, available: number) => `${enabled} enabled · ${available} available`,
  modelsAutoFetchHint: "The model list is fetched automatically once the endpoint URL and key are filled in.",
  modelsFetchingHint: "Fetching the model list from the endpoint…",
  modelsEmptyHint: "No models yet. If fetching fails you can add model names by hand.",
  modelsFilterAll: "All",
  modelsFilterEnabled: "Enabled",
  modelsEnabledEmpty: "Nothing enabled yet; switch to All and tick some.",
  modelsAddManual: "Add a model name by hand",
  modelsAddManualPlaceholder: "A name the endpoint accepts",
  modelsAddConfirm: "Add",
  modelCustomBadge: "Added by hand",
  modelAttrsToggle: (name: string) => `Routing attributes for ${name}`,
  modelPriceTitle: "Relative price used when choosing a model.",
  modelStrengthsAdd: "Custom",
  modelStrengthsAddPlaceholder: "e.g. vision",
  modelStrengthRemove: (tag: string) => `Remove ${tag}`,
  modelSettings: "Model attributes",
  modelSettingsHint: "Set the routing reference price, thinking levels and strengths. Billing rates estimate call costs.",
  modelsSelectionHint: "Select models to enable. Tap Attributes to adjust their capabilities.",
  modelSettingsAction: "Attributes",
  modelsSelectVisible: "Select results",
  modelsClearVisible: "Deselect results",
  modelsClearSearch: "Clear search",
  modelsEnabledCount: (count: number) => `${count} models enabled`,
  modelsManualAdded: (name: string) => `Enabled ${name}`,
  modelsAlreadyEnabled: "This model is already enabled.",
  providerChooseDefault: "Choose a default model",
  providerEnableFirst: "Enable models in the list first",
  modelsSelectTitle: "Select models to use",
  modelsSearchPlaceholder: "Search models...",
  modelsSelectAll: "Select all",
  modelsDeselectAll: "Deselect all",
  modelsManualToggle: "Edit text directly",
  modelsListToggle: "Back to list",
  modelsAddCustom: "Add custom model",
  defaultModel: "Default model",
  defaultModelEmpty: "Pick a default model.",
  defaultModelInvalid: "The default model must be on the available list.",
  modelAttrsEmptyFilter: "No matching models.",
  modelAttrsDefaultBadge: "Default",
  modelPrice: "Routing reference price",
  modelPriceHint: "Optional, e.g. 1.5",
  modelBilling: "Billing rates",
  modelBillingUnit: "USD / million tokens",
  modelBillingInput: "Input",
  modelBillingOutput: "Output",
  modelBillingCached: "Cached input",
  modelBillingOptional: "Optional",
  modelBillingHint: "Set both input and output rates. Cached input defaults to the input rate. Changing them re-prices this model's past calls that have no reported amount.",
  modelBillingInvalid: "Set both input and output rates using non-negative numbers, or clear all rates.",
  modelBillingClear: "Clear billing rates",
  modelThinking: "Thinking levels",
  modelThinkingAdd: "Custom",
  modelThinkingAddPlaceholder: "e.g. xhigh",
  modelStrengths: "Strengths",
  modelInputImage: "Pictures",
  modelInputImageYes: "Takes pictures",
  modelInputImageNo: "No pictures",
  modelInputImageUnknown: "Not sure",
  modelContextWindow: "Context window (tokens)",
  modelContextWindowPlaceholder: "e.g. 32768",
  modelContextWindowHint: "The most tokens the model reads per request. Fill it in if you know it; leave it blank if not.",
  modelContextWindowLocalHint: "A local model server reports its current setting, filled in when models are fetched (Ollama reports the model's own limit while the model is not loaded). A step's prompt clearly over it is not sent; if the server cuts a prompt, the turn stops and says so.",
  modelContextWindowInvalid: "Enter a whole number, or leave it blank.",
  modelSpeed: "Speed and tool calls",
  modelSpeedRun: "Test",
  modelSpeedRunning: "Testing…",
  modelSpeedRate: (tps: number) => `about ${tps} tokens/s`,
  modelSpeedFirstByte: (seconds: number) => `first token in ${seconds} s`,
  modelSpeedTools: "calls tools",
  modelSpeedJoin: ", ",
  modelSpeedNoTools: "It did not call the tool it was given: this model probably cannot do a Bot's work. Pick one that calls tools.",
  modelSpeedFailed: (reason: string) => `The test did not finish: ${reason}`,
  modelSpeedError: (message: string) => `Could not test: ${message}`,
  modelSpeedRecorded: (tps: number) => `On record: ${tps} tokens/s`,
  modelSpeedHint: "Sends two short requests to the saved endpoint and model. 60% of the measured speed is recorded to size how long a step may write; local models need it most. While a local server is writing a Bot's step, the test waits for it, and that wait counts toward the time to the first token.",
  modelNoTools: "No tools",
  modelNoToolsTitle: "The model server says this model cannot call tools; a Bot cannot work on it.",
  saveFailed: "Couldn’t save.",
  retry: "Retry",
  mcp: "MCP",
  mcpEmpty: "No MCP servers yet.",
  mcpEdit: "Edit MCP server",
  mcpSearch: "Search names, transports or connections",
  mcpClearSearch: "Clear search",
  mcpNoResults: "No matching MCP servers.",
  mcpName: "Name",
  mcpTransport: "Transport",
  mcpTransportStdio: "stdio",
  mcpTransportHttp: "HTTP",
  mcpCommand: "command",
  mcpArgs: "args",
  mcpUrl: "URL",
  mcpHeaders: "headers",
  mcpAuth: "Authorization",
  mcpAuthHint: isWindows
    ? "Bearer token. Written only to Windows Credential Manager, never listed."
    : "Bearer token. Written only to the keychain, never listed.",
  mcpEnabled: "Enabled",
  mcpAdd: "Add",
  mcpConfirmAdd: "Confirm add",
  mcpConfirmEdit: "Confirm connection",
  mcpCancel: "Cancel",
  mcpDelete: "Delete",
  mcpNameEmpty: "Enter a name.",
  mcpCommandEmpty: "Enter a command.",
  mcpUrlEmpty: "Enter the MCP URL.",
  mcpUrlInvalid: "The URL must be http or https.",
  mcpMustConfirm: "Adding and changing command / args / URL / headers must be confirmed. There is no Always allow.",
  mcpUsageNote: "Usage note",
  mcpUsageNotePlaceholder: "What this server is for, when to use it, when not to",
  mcpUsageNoteHint:
    "Shown to every Bot on every hop, above the server's own instructions. The name and note save as you edit, with no confirmation, and survive connection changes; leave the note empty to rely on the server's own text.",
  version: (version: string) => `Version ${version}`,
  checkUpdates: "Check for updates",
  checkingUpdates: "Checking...",
  upToDate: "You’re on the latest version.",
  updateAvailable: (version: string) => `Version ${version} is available.`,
  updateDownload: "Download update",
  updateInstall: "Download and install",
  updateInstallHint: "Downloads in the app and restarts itself once it is in place — no installer to walk through.",
  updateDownloading: "Downloading",
  updateVerifying: "Checking the download",
  updateInstalling: "Replacing the app",
  updateRestarting: "Installed — restarting",
  updateInstallCancel: "Cancel",
  updateInstallRetry: "Try again",
  updateInstallFailedDownload: "Couldn’t download this version.",
  updateInstallFailedVerify: "The download wasn’t this version, so it was thrown away.",
  updateInstallFailedInstall: "Couldn’t replace the app. The installed copy is untouched.",
  updateInstallFailedReadOnly: "This copy can’t be replaced from here. Download it in the browser and replace it yourself.",
  updateInstallFailedNotInstalled: "This build runs from source, so there is no app to replace.",
  updateInstallFailedOther: "The update didn’t install. The installed copy is untouched.",
  updateNotes: "Release notes",
  updateChanges: "What changed in this version",
  updateIgnore: "Skip this version",
  updateFailed: "Couldn’t check for updates.",
};
