import type { CopyShape } from "./shape.ts";

export const zh = {
  roster: "名册",
  pinned: "置顶",
  pin: "置顶",
  unpin: "取消置顶",
  expand: "展开",
  collapse: "收起",
  search: "搜索会话、消息、文件、日程",
  searchShort: "搜索",
  searchClear: "清除搜索",
  emptySearch: "没有命中。",
  globalSearch: "全局搜索",
  searchAll: "全部",
  searchIntro: "从这里找到会话、消息、文件和日程",
  searchHint: "输入名称、关键词或文件路径。",
  searchLoading: "正在搜索…",
  searchFailed: "搜索失败，请重试。",
  searchOffline: "连上运行时后即可搜索。",
  searchRetry: "重试",
  searchNoResults: "没有找到匹配的结果",
  searchTryAnother: "试试其他关键词，或换一个分类。",
  searchUnavailable: "这条结果已无法打开。",
  searchResults: (n: number) => `${n} 条结果`,
  searchNavigate: "选择",
  searchOpen: "打开",
  searchClose: "关闭",
  searchCancel: "取消",
  searchEverywhere: "在编辑器或终端中搜索",
  searchKindBot: "Bot",
  searchKindSession: "会话",
  searchKindMessage: "消息",
  searchKindRoutine: "日程",
  routineUnavailable: "日程或所属 Bot 已不可用，无法打开。历史日程仍会保留。",
  searchKindFile: "文件",
  groups: "群",
  fileDrop: "文件",
  fileDropHint: "从远程发来的文件落在工作区 inbox/，文字留在这里。这里不叫醒任何 Bot。",
  fileDropEmpty: "这里还是空的。写几句，或点下面的附件、把文件拖进来。",
  fileDropPlaceholder: "写点什么，或发个文件",
  youBot: "你 ↔ Bot",
  botBot: "Bot ↔ Bot",
  botBotSource: (title: string) => `来自 ${title}`,
  botBotSourceRoot: (immediate: string, root: string) => `来自 ${immediate}（源头：${root}）`,
  botBotSourceUnknown: "来源未知",
  botBotSourceMissing: "来源已不在",
  botBotMore: (n: number) => `还有 ${n} 个`,
  rosterEmpty: "还没有会话",
  rosterEmptyHint: "先建一个 Bot 单聊，或者拉几个 Bot 建个群。",
  settings: "设置",
  notifications: "通知",
  addBot: "新建 Bot",
  addGroup: "新建群",
  createMenu: "新建",
  botName: "名字",
  botDuties: "职责",
  botBoundaries: "边界",
  botAvatar: "头像",
  botAvatarRefresh: "换一个",
  botAvatarStyle: "风格",
  botAvatarCustom: "上传图片",
  botAvatarCustomHint: "PNG、JPEG 或 WebP，最大 8 MB。",
  botAvatarInvalidType: "请选 PNG、JPEG 或 WebP 图片。",
  botAvatarTooLarge: "图片太大了。",
  botAvatarDecodeFailed: "没能读这张图片。",
  botModel: "模型",
  botModelDefault: "自动",
  botModelInvalid: "挑名单里的一个模型。",
  botModelUnlisted: "不在名单上",
  botModelUnlistedHint: "钉的模型已经不在任何端点的名单上了：先用端点默认，它回到名单上就照钉的用。要换就挑一个，或改回自动。",
  botThinking: "思考等级",
  botModelAutoHint: "自动：每条消息由应用挑模型，思考等级跟着那个模型走。挑一个模型就要同时定下思考等级。",
  botThinkingHint: "只列这个模型支持的档。换模型时会落到新模型的默认档。",
  botThinkingInvalid: "挑这个模型支持的思考等级。",
  thinkingLevels: { none: "不思考", low: "低", medium: "中", high: "高", xhigh: "极高", max: "最大", minimal: "最低" },
  botRunner: "运行方式",
  botRunnerApp: "Deskfolk（端点上的模型）",
  botRunnerClaude: "Claude Agent（你本机的 Claude Code）",
  botRunnerAppHint: "应用用你配的端点跑这个 Bot 的每一轮。",
  botRunnerClaudeHint: (account: string) => `每一轮由你本机安装并登录的 Claude Code 来跑，用的是它登录的账号：${account}。Deskfolk 不经手你的 Claude 登录。`,
  botRunnerClaudeChecking: "正在找你本机的 Claude Code…",
  botRunnerClaudeMissing: "这台电脑上没找到 Claude Code（claude）。装好以后在终端里运行 claude 登录，再回来选。",
  botRunnerClaudeSignedOut: "你本机的 Claude Code 还没登录：在终端里运行 claude 登录。Deskfolk 不经手你的 Claude 登录。",
  botRunnerClaudeAccountSignedOut: (command: string) => `这个账号还没登录：在终端里运行 ${command}。Deskfolk 不经手你的 Claude 登录。`,
  botRunnerClaudeUnavailable: "没查到 Claude Code 的状态。电脑上的 Deskfolk 版本较旧时，先在电脑上更新。",
  botRunnerClaudeCreateHint: "建好后每一轮由你本机安装并登录的 Claude Code 来跑；它用哪个 Claude 模型、思考强度多少，在 Bot 面板里选。",
  botAgentAccount: "Claude 账号",
  botAgentAccountDefault: "这台电脑的默认账号",
  botAgentAccountHint: "这个 Bot 的每一轮花哪个账号的额度。要用另一个账号，先在「设置 › Agents › Claude Agent」里添加它的配置目录。",
  botAgentAccountInvalid: "这个账号已经不在设置的列表里了，换一个。",
  botAgentModel: "Claude 模型",
  botAgentModelDefault: "Claude Code 的默认",
  botAgentModelInvalid: "这不是 Claude 的模型名。",
  botAgentEffort: "思考强度",
  botAgentEffortDefault: "默认",
  botAgentEffortHint: "能用哪几档取决于模型；不支持的档由 Claude Code 自己处理。",
  botAgentEffortInvalid: "挑一个列出来的档。",
  autoSaving: "保存中…",
  autoSaved: "已自动保存",
  autoSaveHint: "改动自动保存",
  skills: "技能",
  skillsEmpty: "还没有技能。",
  skillAdd: "添加技能",
  skillName: "名称",
  skillDescription: "何时用",
  skillBody: "怎么干",
  skillUses: "依赖的 MCP",
  skillUsesPlaceholder: "服务器名，逗号分隔；可留空",
  skillUsesHint: "写正文里要调的 MCP 服务器名。本轮没连上的会在技能目录里标出来，Bot 就不会硬套正文。",
  skillEnabled: "启用",
  skillNameEmpty: "填写一个名称。",
  skillDescriptionEmpty: "填写何时用。",
  skillBodyEmpty: "填写怎么干。",
  skillNameConflict: "这个名称已经有了。",
  skillDelete: "删除技能",
  skillDeleteBody: "删除后，这个 Bot 下一跳就看不见这条技能。",
  skillConfirmDelete: "确认删除",
  skillEdit: "编辑技能",
  skillSave: "保存技能",
  skillCancel: "取消",
  memories: "记忆",
  memoriesEmpty: "还没有记忆。Bot 自己记下跨会话要用的事，你可以改或删。",
  memoryHint: "Bot 自己记下跨会话要记住的事，每一跳都会读到。改错了或过期了，改一下或停用。",
  memorySubject: "关于",
  memoryBody: "记住了什么",
  memoryEnabled: "启用",
  memoryEdit: "编辑记忆",
  memorySave: "保存",
  memoryCancel: "取消",
  memoryDelete: "删除记忆",
  memoryDeleteBody: "删除后，这个 Bot 下一跳就看不见这条记忆。",
  memoryConfirmDelete: "确认删除",
  memorySubjectEmpty: "填写这条记忆是关于什么的。",
  memoryBodyEmpty: "填写记住了什么。",
  memorySubjectConflict: "关于这件事已经有一条记忆了。",
  memoryFormedIn: (where: string) => `记于 ${where}`,
  memoryFromRetrospective: (plan: string | null) => (plan ? `完工复盘《${plan}》写的` : "完工复盘写的"),
  learningNoneYet: "还没有后续同类任务",
  learningLater: (later: number, shorter: number) => `之后 ${later} 次同类任务，${shorter} 次更短`,
  memoryOriginMissing: "来源已不在",
  memoryEditedByYou: "你改过",
  memoryJump: "跳到记下它的那条消息",
  memoryShowAll: (n: number) => `显示全部 ${n} 条`,
  memoryCollapse: "收起",
  memoryAgeToday: "今天",
  memoryAgeThisWeek: "本周",
  memoryAgeWeeks: (n: number) => `${n} 周前`,
  memoryAgeMonths: (n: number) => `${n} 个月前`,
  groupName: "群名",
  groupMembers: "成员",
  groupMembersPlaceholder: "挑两个或更多 Bot",
  groupMemberSearch: "接着搜",
  groupMemberNoMatch: "没有匹配的 Bot。",
  groupMemberNone: "名册里还没有 Bot。",
  groupMemberRemove: "移出",
  create: "保存",
  nameEmpty: "填写一个名字。",
  dutiesEmpty: "填写职责。",
  boundariesEmpty: "填写边界。",
  nameConflict: "这个名字已经有了。",
  groupNameEmpty: "填写一个群名。",
  membersTooFew: "至少挑两个 Bot。",
  saveFailed: "没能保存。",
  profile: "人设",
  viewInfo: "查看信息",
  clearHistory: "清除历史",
  archive: "归档",
  unarchive: "取消归档",
  restore: "恢复",
  archiveBody: "从名册移入已归档。会话还在，历史消息保留。",
  restoreBody: "把这个 Bot 放回名册。",
  delete: "删除",
  deleteBody: "删除后，这个 Bot 从名册去掉。会话还在，标题会变成「已删除」。工作区文件不动。",
  confirmDelete: "确认删除",
  cancel: "取消",
  statusRunning: "思考中",
  statusReplying: "回复中",
  statusWaitingApproval: "待审批",
  statusWaitingAsk: "待回复",
  statusFailed: "未完成",
  statusInterrupted: "已中断",
  statusIdle: "空闲",
  unread: "未读",
  noMessages: "还没有消息",
  archivedSessions: "已归档会话",
  archivedEmpty: "没有已归档的会话",
  backToSessions: "返回会话列表",
  workingOnly: "只看工作中和未读",
  workingOnlyOff: "显示全部会话",
  workingEmpty: "没有正在工作或未读的会话。",
  workingEmptyPinned: "置顶之外没有正在工作或未读的会话。",
  resize: "拖动调整会话列表宽度",
  /** The toggle at the start of the top-left pane's tab strip, and ⌘B. */
  hide: "收起会话列表",
  show: "展开会话列表",
  mainNavigation: "主导航",
  sessions: "会话",
  workspace: "工作区",
  tools: "工具",
  workspaceUnset: "先在设置里选择工作区目录。",
  updateAvailable: "有新版本",
};

export const en: CopyShape<typeof zh> = {
  roster: "Roster",
  pinned: "Pinned",
  pin: "Pin",
  unpin: "Unpin",
  expand: "Expand",
  collapse: "Collapse",
  search: "Search sessions, messages, files, routines",
  searchShort: "Search",
  searchClear: "Clear search",
  emptySearch: "No hits.",
  globalSearch: "Global search",
  searchAll: "All",
  searchIntro: "Find a conversation, message, file or routine",
  searchHint: "Enter a name, keyword or file path.",
  searchLoading: "Searching…",
  searchFailed: "Search failed. Please try again.",
  searchOffline: "Connect to the runtime to search.",
  searchRetry: "Retry",
  searchNoResults: "No matching results",
  searchTryAnother: "Try another keyword or category.",
  searchUnavailable: "This result is no longer available.",
  searchResults: (n: number) => `${n} results`,
  searchNavigate: "Navigate",
  searchOpen: "Open",
  searchClose: "Close",
  searchCancel: "Cancel",
  searchEverywhere: "Search from an editor or terminal",
  searchKindBot: "Bot",
  searchKindSession: "Session",
  searchKindMessage: "Message",
  searchKindRoutine: "Routine",
  routineUnavailable: "The routine or its Bot is no longer available to open. Historical routines are retained.",
  searchKindFile: "File",
  groups: "Groups",
  fileDrop: "Files",
  fileDropHint: "Files sent over remote control land in the workspace inbox/; text stays here. Nothing here wakes a Bot.",
  fileDropEmpty: "Nothing here yet. Write a note, use the attachment button below, or drop a file in.",
  fileDropPlaceholder: "Write something, or send a file",
  youBot: "You ↔ Bot",
  botBot: "Bot ↔ Bot",
  botBotSource: (title: string) => `From ${title}`,
  botBotSourceRoot: (immediate: string, root: string) => `From ${immediate} (root: ${root})`,
  botBotSourceUnknown: "Source unknown",
  botBotSourceMissing: "Source is gone",
  botBotMore: (n: number) => `${n} more`,
  rosterEmpty: "No conversations yet",
  rosterEmptyHint: "Start a chat with one Bot, or put a few Bots in a group.",
  settings: "Settings",
  notifications: "Notifications",
  addBot: "New bot",
  addGroup: "New group",
  createMenu: "New",
  botName: "Name",
  botDuties: "Duties",
  botBoundaries: "Boundaries",
  botAvatar: "Avatar",
  botAvatarRefresh: "Randomize",
  botAvatarStyle: "Style",
  botAvatarCustom: "Upload image",
  botAvatarCustomHint: "PNG, JPEG, or WebP, up to 8 MB.",
  botAvatarInvalidType: "Pick a PNG, JPEG, or WebP image.",
  botAvatarTooLarge: "That image is too large.",
  botAvatarDecodeFailed: "Couldn’t read that image.",
  botModel: "Model",
  botModelDefault: "Automatic",
  botModelInvalid: "Pick a model from the list.",
  botModelUnlisted: "not listed",
  botModelUnlistedHint: "The pinned model is no longer listed by any endpoint: it runs on the endpoint's default meanwhile, and on the pin again once the model is back. Pick another, or go back to automatic.",
  botThinking: "Thinking level",
  botModelAutoHint: "Automatic: the app picks a model per message and the thinking level that goes with it. Picking a model means picking its thinking level too.",
  botThinkingHint: "Only the levels this model supports. Changing the model moves the pin to the new model's default.",
  botThinkingInvalid: "Pick a thinking level this model supports.",
  thinkingLevels: { none: "None", low: "Low", medium: "Medium", high: "High", xhigh: "Extra high", max: "Max", minimal: "Minimal" },
  botRunner: "Runs on",
  botRunnerApp: "Deskfolk (a model on your endpoint)",
  botRunnerClaude: "Claude Agent (your own Claude Code)",
  botRunnerAppHint: "The app runs this Bot's turns on the endpoints you set up.",
  botRunnerClaudeHint: (account: string) => `Each turn is run by the Claude Code you installed and signed in to on this computer, on the account it is signed in with: ${account}. Deskfolk never handles your Claude sign-in.`,
  botRunnerClaudeChecking: "Looking for your Claude Code…",
  botRunnerClaudeMissing: "Claude Code (claude) was not found on this computer. Install it, run claude in a terminal to sign in, then pick this again.",
  botRunnerClaudeSignedOut: "Your Claude Code is not signed in: run claude in a terminal and sign in. Deskfolk never handles your Claude sign-in.",
  botRunnerClaudeAccountSignedOut: (command: string) => `This account is not signed in: run ${command} in a terminal. Deskfolk never handles your Claude sign-in.`,
  botRunnerClaudeUnavailable: "Could not read Claude Code's status. If the computer runs an older Deskfolk, update it there first.",
  botRunnerClaudeCreateHint: "Once created, each turn is run by the Claude Code you installed and signed in to on this computer; pick its Claude model and effort in the Bot panel.",
  botAgentAccount: "Claude account",
  botAgentAccountDefault: "This computer's default account",
  botAgentAccountHint: "Whose plan this Bot's turns spend. To use another account, add its config directory under Settings › Agents › Claude Agent first.",
  botAgentAccountInvalid: "That account is no longer listed in Settings; pick another.",
  botAgentModel: "Claude model",
  botAgentModelDefault: "Claude Code's default",
  botAgentModelInvalid: "That is not a Claude model name.",
  botAgentEffort: "Effort",
  botAgentEffortDefault: "Default",
  botAgentEffortHint: "Which levels a model offers varies; Claude Code handles one it lacks.",
  botAgentEffortInvalid: "Pick one of the listed levels.",
  autoSaving: "Saving…",
  autoSaved: "Saved automatically",
  autoSaveHint: "Changes save automatically",
  skills: "Skills",
  skillsEmpty: "No skills yet.",
  skillAdd: "Add skill",
  skillName: "Name",
  skillDescription: "When to use",
  skillBody: "How to do it",
  skillUses: "Uses MCP",
  skillUsesPlaceholder: "Server names, comma-separated; optional",
  skillUsesHint: "Name the MCP servers the body calls. Servers not connected this turn are marked in the skill catalog so the Bot does not force the body.",
  skillEnabled: "Enabled",
  skillNameEmpty: "Enter a name.",
  skillDescriptionEmpty: "Enter when to use it.",
  skillBodyEmpty: "Enter how to do it.",
  skillNameConflict: "That name is already used.",
  skillDelete: "Delete skill",
  skillDeleteBody: "After this, the Bot will not see the skill on the next hop.",
  skillConfirmDelete: "Confirm delete",
  skillEdit: "Edit skill",
  skillSave: "Save skill",
  skillCancel: "Cancel",
  memories: "Memory",
  memoriesEmpty: "No memories yet. The Bot writes down what it needs across sessions; you can edit or delete.",
  memoryHint: "The Bot records what to remember across sessions and reads these on every hop. Correct or disable one that is wrong or out of date.",
  memorySubject: "About",
  memoryBody: "What it remembers",
  memoryEnabled: "Enabled",
  memoryEdit: "Edit memory",
  memorySave: "Save",
  memoryCancel: "Cancel",
  memoryDelete: "Delete memory",
  memoryDeleteBody: "After this, the Bot will not see this memory on its next hop.",
  memoryConfirmDelete: "Confirm delete",
  memorySubjectEmpty: "Enter what this memory is about.",
  memoryBodyEmpty: "Enter what it remembers.",
  memorySubjectConflict: "There is already a memory about that.",
  memoryFormedIn: (where: string) => `Formed in ${where}`,
  memoryFromRetrospective: (plan: string | null) => (plan ? `Written by the retrospective of "${plan}"` : "Written by a retrospective"),
  learningNoneYet: "No later task of this kind yet",
  learningLater: (later: number, shorter: number) =>
    `${later} later ${later === 1 ? "task" : "tasks"} of this kind, ${shorter} shorter`,
  memoryOriginMissing: "Source is gone",
  memoryEditedByYou: "Edited by you",
  memoryJump: "Jump to the message it came from",
  memoryShowAll: (n: number) => `Show all ${n}`,
  memoryCollapse: "Collapse",
  memoryAgeToday: "Today",
  memoryAgeThisWeek: "This week",
  memoryAgeWeeks: (n: number) => `${n}w ago`,
  memoryAgeMonths: (n: number) => `${n}mo ago`,
  groupName: "Group name",
  groupMembers: "Members",
  groupMembersPlaceholder: "Pick two or more bots",
  groupMemberSearch: "Keep searching",
  groupMemberNoMatch: "No bot matches.",
  groupMemberNone: "No bots in the roster yet.",
  groupMemberRemove: "Remove",
  create: "Save",
  nameEmpty: "Enter a name.",
  dutiesEmpty: "Enter duties.",
  boundariesEmpty: "Enter boundaries.",
  nameConflict: "That name is already used.",
  groupNameEmpty: "Enter a group name.",
  membersTooFew: "Pick at least two bots.",
  saveFailed: "Couldn’t save.",
  profile: "Profile",
  viewInfo: "View info",
  clearHistory: "Clear history",
  archive: "Archive",
  unarchive: "Unarchive",
  restore: "Restore",
  archiveBody: "Move the bot into Archived. Sessions stay; history is kept.",
  restoreBody: "Put this bot back on the roster.",
  delete: "Delete",
  deleteBody: "This removes the bot from the roster. Sessions stay, titled Deleted. Workspace files are not touched.",
  confirmDelete: "Confirm delete",
  cancel: "Cancel",
  statusRunning: "Thinking",
  statusReplying: "Replying",
  statusWaitingApproval: "Approval",
  statusWaitingAsk: "Waiting input",
  statusFailed: "Didn't finish",
  statusInterrupted: "Interrupted",
  statusIdle: "Idle",
  unread: "Unread",
  noMessages: "No messages",
  archivedSessions: "Archived sessions",
  archivedEmpty: "No archived sessions",
  backToSessions: "Back to sessions",
  workingOnly: "Only working or unread",
  workingOnlyOff: "Show all sessions",
  workingEmpty: "No session is working or unread.",
  workingEmptyPinned: "Nothing outside the pinned ones is working or unread.",
  resize: "Drag to resize the session list",
  hide: "Hide the session list",
  show: "Show the session list",
  mainNavigation: "Main navigation",
  sessions: "Chats",
  workspace: "Workspace",
  tools: "Tools",
  workspaceUnset: "Choose a workspace folder in Settings first.",
  updateAvailable: "Update available",
};
