import { enTrashOwner, enTrashWord, isWindows, zhTrashWord } from "./platform-words.ts";
import type { CopyShape } from "./shape.ts";

export const zh = {
  empty: "还没有消息。",
  messageIndex: "消息位置",
  messageIndexEmpty: "（无文字）",
  loadEarlier: "载入更早的消息",
  loadingEarlier: "正在载入…",
  loadingHistory: "正在载入这段对话…",
  mentionUnresolved: "这个 @ 没有匹配到群成员",
  streaming: "正在写",
  replying: "回复中",
  continueInterrupt: "继续",
  continueInterruptHint: "从中断处继续，不重试断掉的那一下",
  continueUnreachableHint: "从断开处继续",
  continueFailedHint: "从失败处继续",
  ask: "提问",
  reply: "回复",
  askPickOne: "选一个",
  askPickAny: "可多选",
  askWriteOwn: "自己写，或补充一句…",
  askAnswered: "已回答",
  askYourAnswer: "你的回答",
  approval: "批准",
  allowOnce: "允许一次",
  alwaysAllow: "Always allow",
  deny: "拒绝",
  allowed: "已允许",
  denied: "已拒绝",
  voided: "已作废",
  endpointKey: "端点密钥",
  endpointKeyHintAdd: "允许一次前必须粘贴密钥。不会写进转录。",
  endpointKeyHintEdit: "该端点还没有密钥则必须贴；已有密钥可留空保留。不会写进转录。",
  endpointKeyEmpty: "填写端点密钥。",
  mcpAuth: "Authorization",
  mcpAuthHintAdd: "允许一次前必须粘贴 Authorization（可含 Bearer）。不会写进转录。",
  mcpAuthHintEdit: "已有 Authorization 可留空保留；要换就重贴。不会写进转录。",
  mcpAuthEmpty: "填写 Authorization。",
  artifactPreview: "产物预览",
  artifactLoading: "正在打开文件…",
  office: {
    readOnly: "只读预览",
    fullscreen: "全屏预览",
    exitFull: "退出全屏（Esc）",
    loading: "正在解析办公文件…",
    failed: "无法预览这份文件。请确认文件完整且未加密，或用系统应用打开。",
    tooLarge: "文件超过预览容量限制，请用系统应用打开（文件上限 50 MiB，解压后 128 MiB）。",
    retry: "重试",
    previous: "上一张幻灯片",
    next: "下一张幻灯片",
    sheets: "工作表",
    row: "行号",
    emptySheet: "这张工作表没有单元格数据。",
    empty: "没有可预览的内容。",
    truncated: "已限制为前 50 张可见工作表，每张最多 1000 个有数据的行、100 列。",
    sheetHint: "显示单元格内容与公式的已存结果；公式未存结果时显示公式。图表、图片和原始排版请用系统应用查看。",
    layoutHint: "字体与复杂排版可能有差异；动画、宏和外部链接保持停用。",
  },
  artifactMissing: "文件不在了",
  artifactEnlarge: "放大查看",
  imageOriginal: (size: string | null) => (size ? `查看原图（${size}）` : "查看原图"),
  imageOriginalLoading: (bytes: string | null) => (bytes ? `正在载入原图 ${bytes}` : "正在载入原图…"),
  imageSave: "下载原图",
  imageSaveTapAgain: "原图已取回，再点一次下载",
  imageSaveFailed: "没能下载原图",
  artifactUnsupported: "这种文件不支持预览。",
  artifactDownload: "下载",
  artifactDownloading: (bytes: string | null) => (bytes ? `正在下载 ${bytes}` : "正在下载…"),
  artifactDownloadFailed: "没能下载这个文件",
  artifactOpenSystem: "用系统默认应用打开",
  artifactReveal: isWindows ? "在文件资源管理器中显示" : "在 Finder 中打开",
  artifactOpenTerminal: "在此位置打开终端",
  artifactCopyPath: "复制工作区路径",
  artifactCopyAbsPath: "复制绝对路径",
  artifactTrash: `移到${zhTrashWord}`,
  artifactTrashCount: (count: number) => `将 ${count} 项移到${zhTrashWord}`,
  artifactTrashTitle: (name: string, count: number) => (count > 1 ? `将 ${count} 项移到${zhTrashWord}？` : `将“${name}”移到${zhTrashWord}？`),
  artifactTrashBody: (names: string[], count: number, folders: boolean, unsaved: boolean) =>
    [
      count > 1
        ? `${names.slice(0, 3).map((name) => `“${name}”`).join("、")}${count > 3 ? ` 等 ${count} 项` : ""}会移到${isWindows ? "" : " Mac 的"}${zhTrashWord}，可以从那里放回。`
        : `它会移到${isWindows ? "" : " Mac 的"}${zhTrashWord}，可以从那里放回。`,
      folders ? "文件夹会连同里面的内容一起移走。" : "",
      unsaved ? "正在编辑的文件还有未保存的修改，会一起丢掉。" : "",
    ].join(""),
  artifactTrashFailed: (count: number, reason: string) => `有 ${count} 项没能移走：${reason}`,
  artifactTrashRetry: "重试",
  artifactDirectory: "文件夹",
  artifactOpenUnavailable: "开发态浏览器里请下载；系统打开只在 App 窗里。",
  artifactResize: "拖动调整预览宽度",
  artifactTree: "引用的文件",
  /** The chip under the pointer while several rows are dragged out of the tree. */
  dragItems: (count: number) => `${count} 项`,
  artifactTreeLoading: "正在加载文件列表…",
  artifactTreeFailed: "文件列表加载失败。",
  artifactTreeEmpty: "暂无引用的文件。",
  artifactBundle: "工作区文件",
  artifactBundleCount: (count: number) => `${count} 个文件`,
  artifactWrap: "换行",
  artifactSource: "源码",
  artifactRendered: "预览",
  artifactFind: "查找",
  artifactFindNext: "下一个",
  artifactFindPrev: "上一个",
  artifactMatchCase: "区分大小写",
  artifactRegexp: "正则",
  artifactByWord: "整词",
  artifactNoMatch: "无匹配",
  workspaceExplorer: "工作区",
  workspaceTruncated: "这一层文件太多，只列出前一部分。",
  workspaceEmpty: "这个文件夹是空的。",
  workspacePickFile: "从左侧打开一个文件。",
  artifactSave: "保存",
  artifactSaving: "保存中",
  artifactSaveFailed: "没能保存。",
  artifactSaveConflict: "文件已被修改，未覆盖；请先复制你的编辑，再重新打开文件。",
  artifactDirtyTitle: "有未保存的更改",
  artifactDirtyBody: "切换文件或关闭预览会丢掉还没保存的修改。",
  artifactDiscard: "丢弃",
  artifactTreeResize: "拖动调整文件树宽度",
  annotationsTitle: "批注",
  annotationsCount: (count: number) => `${count} 条批注`,
  annotationsEmpty: "这个文件还没有批注",
  annotationsEmptyHint: "在文件上选一处写下意见，先存成草稿，攒好一起发给交出它的 Bot。",
  annotationsEmptyOpen: "没有待处理的批注",
  annotationsEmptyOpenHint: "发出去、还没处理完的批注列在这里。",
  annotationsEmptyResolved: "还没有已处理的批注",
  annotationsEmptyResolvedHint: "Bot 或你标成已处理的批注列在这里。",
  annotationsEmptyDraft: "没有草稿",
  annotationsEmptyDraftHint: "写下的批注先存在这里，发出去之前只有你看得见。",
  annotationsFilterOpen: "待处理",
  annotationsFilterResolved: "已处理",
  annotationsFilterDraft: "草稿",
  annotationsFilterAll: "全部",
  annotationShowResolved: "显示已处理",
  annotationShowResolvedHint: "已处理的批注不再画在文件上；勾上把它们画回来。列表里一直都在。",
  annotationAdd: "批注",
  annotationAddHint: "选中文字后点「批注」；手机上点行号选中一行。",
  annotationDirtyHint: "先保存或丢弃修改，再加批注。",
  annotationStreamedHint: "远程边播边传的音视频拿不到整个文件的指纹，这里暂时不能加时间点；在 Mac 上可以。",
  annotationNoTarget: "这个文件没有 Bot 交出过，不能批注；只能看已有的批注。",
  annotationPlaceholder: "写一句意见…",
  annotationSaveDraft: "存为草稿",
  annotationCancel: "取消",
  annotationEdit: "编辑",
  annotationDelete: "删除",
  annotationResolve: "标为已处理",
  annotationReopen: "重新打开",
  annotationStatusDraft: "草稿",
  annotationStatusOpen: "待处理",
  annotationStatusResolved: "已处理",
  annotationStaleChanged: "原文已变",
  annotationStaleMissing: "文件不在了",
  annotationStaleMoved: (lines: string) => `原文已变，现在在${lines}`,
  annotationResolvedByYou: "你",
  annotationResolvedBy: (who: string) => `${who} 已处理`,
  annotationResolvedNote: "处理说明",
  annotationSendPending: (count: number) => `${count} 条批注待发送`,
  annotationSendSummary: "再补一句总话（可不填）",
  annotationSend: "发送批注",
  annotationSending: "发送中…",
  annotationClear: "清空",
  annotationClearConfirm: "清空这批草稿？",
  annotationClearYes: "清空",
  annotationSendTo: (name: string) => `将发到你和 ${name} 的私聊`,
  annotationSendFailed: "没能发送批注。",
  annotationSaveFailed: "没能保存批注。",
  annotationClearFailed: "有的草稿没能删掉，再试一次。",
  annotationFileChanged: "选好位置之后文件改过了（或有没保存的修改），这个位置可能已经对不上；取消后重新选一处。",
  annotationSendCapped: (max: number) => `一次最多发 ${max} 条，这次先发最早的 ${max} 条`,
  annotationGoTo: "定位",
  annotationDeselect: "取消选中",
  annotationMode: "批注模式",
  annotationModeExit: "退出批注",
  annotImage: {
    region: "在图上拖出一个框，或点一下",
    mark: (n: number, remark: string) => `批注 ${n}：${remark}`,
    pending: "新批注的位置，拖动可挪位置",
    resize: "拖动改大小",
    stale: "图片已变，位置可能不准",
  },
  annotPdf: {
    loading: "正在打开 PDF…",
    failed: "没能打开这个 PDF。",
    broken: "这个 PDF 已损坏，打不开。",
    password: "这个 PDF 设了密码，输入密码后打开。",
    passwordWrong: "密码不对，再试一次。",
    passwordField: "密码",
    passwordOpen: "打开",
    zoomIn: "放大",
    zoomOut: "缩小",
    zoom: "缩放",
    fitWidth: "适合宽度",
    fitPage: "适合页面",
    pageNumber: "页码",
    pageCount: (total: number) => `/ ${total} 页`,
    find: "查找",
    findPlaceholder: "在 PDF 里查找",
    findPrev: "上一个",
    findNext: "下一个",
    findClose: "关闭查找",
    findCount: (current: number, total: number) => `${current}/${total}`,
    findNone: "没有找到",
    findSearching: "正在查找…",
    goTo: "跳到链接指向的位置",
    region: "在页面上拖出一个框，或点一下",
    mark: (n: number, remark: string) => `批注 ${n}：${remark}`,
    pending: "新批注的位置，拖动可挪位置，方向键可微调",
    resize: "拖动改大小",
    stale: "文件已变，位置可能不准",
  },
  annotHtml: {
    hint: "点选页面上的一个元素",
    keysHint: "↑ ↓ 换外层或内层，Enter 选定，Esc 退出",
    pendingHint: "已选中，写下批注；也可以换到外层或内层",
    outer: "外层",
    inner: "内层",
    marks: "页面上的批注",
    markLabel: (n: number) => `第 ${n} 条批注`,
    stale: "原文已变",
    notFound: "页面里找不到这个元素了",
    blocked: "这个页面的脚本在这里跑不了，没法点选元素；切到「源码」可以按行批注",
    viewport: {
      group: "预览设备",
      desktop: "电脑",
      tablet: "平板",
      phone: "手机",
      zoomed: (width: number) => `这个页面按 ${width} 像素宽排版，再像手机浏览器那样缩小到屏幕宽`,
      enlarge: "全屏预览",
      shrink: "退出全屏（Esc）",
    },
  },
  annotMarkdown: {
    annotate: "批注",
    mark: (n: number, remark: string) => `批注 ${n}：${remark}`,
    stale: "原文已变，位置可能不准",
  },
  annotMedia: {
    markHere: "在此处批注",
    markHereHint: "把当前播放位置记为一个批注点",
    endHere: "到此为止",
    endHereHint: "把批注点延长成一段，到当前播放位置为止",
    timeline: "批注时间轴",
    pending: "待写的批注",
    durationUnknown: "还没读到时长，暂时不能批注",
    spanTooShort: "先播到或拖到终点，至少隔开 1 秒",
    spanPastEnd: "起点超出了现在的时长",
    stale: "文件已变，时间可能不准",
  },
};

export const en: CopyShape<typeof zh> = {
  empty: "No messages yet.",
  messageIndex: "Message index",
  messageIndexEmpty: "(no text)",
  loadEarlier: "Load earlier messages",
  loadingEarlier: "Loading…",
  loadingHistory: "Loading this conversation…",
  mentionUnresolved: "This @ matches no member here",
  streaming: "streaming",
  replying: "replying",
  continueInterrupt: "Continue",
  continueInterruptHint: "Continue from the interruption without retrying the cut action",
  continueUnreachableHint: "Continue from where the connection was lost",
  continueFailedHint: "Continue from the failed turn",
  ask: "ask",
  reply: "Reply",
  askPickOne: "Pick one",
  askPickAny: "Pick any",
  askWriteOwn: "Write your own, or add a note…",
  askAnswered: "Answered",
  askYourAnswer: "Your answer",
  approval: "approval",
  allowOnce: "Allow once",
  alwaysAllow: "Always allow",
  deny: "Deny",
  allowed: "Allowed",
  denied: "Denied",
  voided: "Voided",
  endpointKey: "Endpoint key",
  endpointKeyHintAdd: "Paste the key before Allow once. It is not written into the transcript.",
  endpointKeyHintEdit: "Required if this endpoint has no key yet; leave blank to keep the current key. It is not written into the transcript.",
  endpointKeyEmpty: "Paste the endpoint key.",
  mcpAuth: "Authorization",
  mcpAuthHintAdd: "Paste Authorization (Bearer allowed) before Allow once. It is not written into the transcript.",
  mcpAuthHintEdit: "Leave blank to keep the current Authorization; paste a new value to rotate it. It is not written into the transcript.",
  mcpAuthEmpty: "Paste Authorization.",
  artifactPreview: "Artifact preview",
  artifactLoading: "Opening file…",
  office: {
    readOnly: "Read-only preview",
    fullscreen: "Full-screen preview",
    exitFull: "Exit full screen (Esc)",
    loading: "Reading Office file…",
    failed: "Could not preview this file. Check that it is complete and unencrypted, or open it in a system app.",
    tooLarge: "This file exceeds preview limits. Open it in a system app (50 MiB file, 128 MiB unpacked).",
    retry: "Retry",
    previous: "Previous slide",
    next: "Next slide",
    sheets: "Worksheets",
    row: "Row number",
    emptySheet: "This worksheet has no cell data.",
    empty: "No content to preview.",
    truncated: "Showing up to 50 visible worksheets, 1000 populated rows and 100 columns per sheet.",
    sheetHint: "Shows cell contents and saved formula results; formulas without saved results appear as formulas. Open in a system app for charts, images and original formatting.",
    layoutHint: "Fonts and complex layouts may vary. Animations, macros and external links stay disabled.",
  },
  artifactMissing: "File is gone",
  artifactEnlarge: "View larger",
  imageOriginal: (size: string | null) => (size ? `View original (${size})` : "View original"),
  imageOriginalLoading: (bytes: string | null) => (bytes ? `Loading original ${bytes}` : "Loading original…"),
  imageSave: "Download original",
  imageSaveTapAgain: "Original is here — tap download again",
  imageSaveFailed: "Couldn’t download the original",
  artifactUnsupported: "This kind of file can’t be previewed.",
  artifactDownload: "Download",
  artifactDownloading: (bytes: string | null) => (bytes ? `Downloading ${bytes}` : "Downloading…"),
  artifactDownloadFailed: "Couldn’t download this file",
  artifactOpenSystem: "Open with default app",
  artifactReveal: isWindows ? "Show in File Explorer" : "Show in Finder",
  artifactOpenTerminal: "Open terminal here",
  artifactCopyPath: "Copy workspace path",
  artifactCopyAbsPath: "Copy absolute path",
  artifactTrash: `Move to ${enTrashWord}`,
  artifactTrashCount: (count: number) => `Move ${count} items to ${enTrashWord}`,
  artifactTrashTitle: (name: string, count: number) => (count > 1 ? `Move ${count} items to the ${enTrashWord}?` : `Move “${name}” to the ${enTrashWord}?`),
  artifactTrashBody: (names: string[], count: number, folders: boolean, unsaved: boolean) =>
    [
      count > 1
        ? `${names.slice(0, 3).map((name) => `“${name}”`).join(", ")}${count > 3 ? ` and ${count - 3} more` : ""} go to ${enTrashOwner} ${enTrashWord}, where you can put them back.`
        : `It goes to ${enTrashOwner} ${enTrashWord}, where you can put it back.`,
      folders ? "Folders go with everything in them." : "",
      unsaved ? "Unsaved edits in the file you are editing are lost." : "",
    ].filter(Boolean).join(" "),
  artifactTrashFailed: (count: number, reason: string) => `${count === 1 ? "1 item" : `${count} items`} could not be moved: ${reason}`,
  artifactTrashRetry: "Try again",
  artifactDirectory: "Folder",
  artifactOpenUnavailable: "In the browser, download instead. Open with system is only in the app window.",
  artifactResize: "Drag to resize preview",
  artifactTree: "Cited files",
  dragItems: (count: number) => `${count} items`,
  artifactTreeLoading: "Loading files…",
  artifactTreeFailed: "Could not load files.",
  artifactTreeEmpty: "No cited files yet.",
  artifactBundle: "Workspace files",
  artifactBundleCount: (count: number) => (count === 1 ? "1 file" : `${count} files`),
  artifactWrap: "Wrap",
  artifactSource: "Source",
  artifactRendered: "Preview",
  artifactFind: "Find",
  artifactFindNext: "Next",
  artifactFindPrev: "Previous",
  artifactMatchCase: "Match case",
  artifactRegexp: "Regexp",
  artifactByWord: "Whole word",
  artifactNoMatch: "No matches",
  workspaceExplorer: "Workspace",
  workspaceTruncated: "This folder has too many entries; only the first part is listed.",
  workspaceEmpty: "This folder is empty.",
  workspacePickFile: "Open a file from the left.",
  artifactSave: "Save",
  artifactSaving: "Saving",
  artifactSaveFailed: "Couldn’t save.",
  artifactSaveConflict: "The file changed and was not overwritten. Copy your edits, then reopen the file.",
  artifactDirtyTitle: "Unsaved changes",
  artifactDirtyBody: "Switching files or closing the preview discards unsaved edits.",
  artifactDiscard: "Discard",
  artifactTreeResize: "Drag to resize the file tree",
  annotationsTitle: "Annotations",
  annotationsCount: (count: number) => (count === 1 ? "1 annotation" : `${count} annotations`),
  annotationsEmpty: "No annotations on this file yet",
  annotationsEmptyHint: "Pick a spot on the file and write what should change. It stays a draft until you send the batch to the Bot that handed the file over.",
  annotationsEmptyOpen: "Nothing pending",
  annotationsEmptyOpenHint: "Annotations you sent that are not handled yet show here.",
  annotationsEmptyResolved: "Nothing resolved yet",
  annotationsEmptyResolvedHint: "Annotations a Bot or you marked resolved show here.",
  annotationsEmptyDraft: "No drafts",
  annotationsEmptyDraftHint: "What you write waits here, seen only by you, until you send it.",
  annotationsFilterOpen: "Pending",
  annotationsFilterResolved: "Resolved",
  annotationsFilterDraft: "Drafts",
  annotationsFilterAll: "All",
  annotationShowResolved: "Show resolved",
  annotationShowResolvedHint: "Resolved annotations come off the file; check this to draw them again. The list keeps them either way.",
  annotationAdd: "Annotate",
  annotationAddHint: "Select text, then Annotate; on a phone, tap a line number to select the line.",
  annotationDirtyHint: "Save or discard your edits before annotating.",
  annotationStreamedHint: "A clip streamed from the Mac has no whole-file fingerprint here, so it cannot take time points remotely; annotate it on the Mac.",
  annotationNoTarget: "No Bot handed this file over, so it cannot be annotated; existing annotations are shown only.",
  annotationPlaceholder: "Write a remark…",
  annotationSaveDraft: "Save draft",
  annotationCancel: "Cancel",
  annotationEdit: "Edit",
  annotationDelete: "Delete",
  annotationResolve: "Mark resolved",
  annotationReopen: "Reopen",
  annotationStatusDraft: "Draft",
  annotationStatusOpen: "Pending",
  annotationStatusResolved: "Resolved",
  annotationStaleChanged: "Text changed",
  annotationStaleMissing: "File gone",
  annotationStaleMoved: (lines: string) => `Text moved; now at ${lines}`,
  annotationResolvedByYou: "you",
  annotationResolvedBy: (who: string) => `Resolved by ${who}`,
  annotationResolvedNote: "Note",
  annotationSendPending: (count: number) => (count === 1 ? "1 annotation to send" : `${count} annotations to send`),
  annotationSendSummary: "Add a summary (optional)",
  annotationSend: "Send annotations",
  annotationSending: "Sending…",
  annotationClear: "Clear",
  annotationClearConfirm: "Discard these drafts?",
  annotationClearYes: "Discard",
  annotationSendTo: (name: string) => `Will be sent to your direct with ${name}`,
  annotationSendFailed: "The annotations could not be sent.",
  annotationSaveFailed: "The annotation could not be saved.",
  annotationClearFailed: "Some drafts could not be deleted. Try again.",
  annotationFileChanged: "The file changed after you picked this spot (or has unsaved edits), so it may no longer match; cancel and pick it again.",
  annotationSendCapped: (max: number) => `At most ${max} per batch — sending the oldest ${max} now`,
  annotationGoTo: "Go to",
  annotationDeselect: "Deselect",
  annotationMode: "Annotate",
  annotationModeExit: "Stop annotating",
  annotImage: {
    region: "Drag a box on the image, or click a spot",
    mark: (n: number, remark: string) => `Annotation ${n}: ${remark}`,
    pending: "New annotation; drag to move it",
    resize: "Drag to resize",
    stale: "Image changed; the spot may be off",
  },
  annotPdf: {
    loading: "Opening PDF…",
    failed: "Couldn't open this PDF.",
    broken: "This PDF is damaged and can't be opened.",
    password: "This PDF is password-protected. Enter the password to open it.",
    passwordWrong: "Wrong password. Try again.",
    passwordField: "Password",
    passwordOpen: "Open",
    zoomIn: "Zoom in",
    zoomOut: "Zoom out",
    zoom: "Zoom",
    fitWidth: "Fit width",
    fitPage: "Fit page",
    pageNumber: "Page number",
    pageCount: (total: number) => `of ${total}`,
    find: "Find",
    findPlaceholder: "Find in PDF",
    findPrev: "Previous match",
    findNext: "Next match",
    findClose: "Close find",
    findCount: (current: number, total: number) => `${current} of ${total}`,
    findNone: "No matches",
    findSearching: "Searching…",
    goTo: "Go to the linked place",
    region: "Drag a box on the page, or click a spot",
    mark: (n: number, remark: string) => `Annotation ${n}: ${remark}`,
    pending: "New annotation; drag to move it, or nudge it with the arrow keys",
    resize: "Drag to resize",
    stale: "File changed; the spot may be off",
  },
  annotHtml: {
    hint: "Click an element on the page",
    keysHint: "↑ ↓ for the outer or inner element, Enter to choose, Esc to leave",
    pendingHint: "Chosen. Write your remark, or move to the outer or inner element",
    outer: "Outer",
    inner: "Inner",
    marks: "Annotations on this page",
    markLabel: (n: number) => `Annotation ${n}`,
    stale: "Text changed",
    notFound: "This element is no longer on the page",
    blocked: "This page's scripts can't run here, so elements can't be picked. Switch to Source to annotate by line",
    viewport: {
      group: "Preview device",
      desktop: "Desktop",
      tablet: "Tablet",
      phone: "Phone",
      zoomed: (width: number) => `This page is laid out ${width} pixels wide, then zoomed out to the screen the way a mobile browser does`,
      enlarge: "Full screen",
      shrink: "Exit full screen (Esc)",
    },
  },
  annotMarkdown: {
    annotate: "Annotate",
    mark: (n: number, remark: string) => `Annotation ${n}: ${remark}`,
    stale: "Text changed; the spot may be off",
  },
  annotMedia: {
    markHere: "Annotate here",
    markHereHint: "Mark the current playback time",
    endHere: "End here",
    endHereHint: "Turn the point into a span that ends at the current playback time",
    timeline: "Annotation timeline",
    pending: "New annotation",
    durationUnknown: "The length is not known yet, so this cannot be annotated",
    spanTooShort: "Play or seek to the end first; at least 1 second from the start",
    spanPastEnd: "The start is past the current end of the file",
    stale: "File changed; the time may be off",
  },
};
