import type { CopyShape } from "./shape.ts";

export const zh = {
  title: "终端",
  open: "打开终端",
  newSession: "新建",
  newTab: "新建终端",
  reattach: (name: string) => `接回 · ${name}`,
  close: "关闭这条",
  end: "结束会话",
  endConfirm: "结束后里面跑着的进程会一起停。",
  stop: "停止",
  empty: "还没有终端会话。",
  emptyHint: "新建一条，在这台机器上跑你自己的命令。",
  needsWorkspace: "先在设置里选择工作区目录。",
  unavailable: "终端不可用：原生助手没有就位。",
  exited: "已结束",
  exitedWith: "已结束 · 退出码 {code}",
  interrupted: "已中断",
  dropped: "输出过快，已丢弃 {bytes} 字节",
  survivesWindow: "关窗不停；退出后再开，回到原来的位置",
  keys: "控制键",
  find: "在终端里查找",
  findPrevious: "上一个",
  findNext: "下一个",
  findClose: "关闭查找",
  findNone: "没有结果",
  findMany: "超过 {count} 处",
  sessions: "切换终端",
  more: "更多",
  clear: "清屏",
  fontSize: "字号",
  fontSmaller: "缩小字号",
  fontBigger: "放大字号",
  paste: "粘贴",
  ctrl: "Ctrl：作用于下一个键",
  showKeyboard: "弹出键盘",
  hideKeyboard: "收起键盘",
};

export const en: CopyShape<typeof zh> = {
  title: "Terminal",
  open: "Open terminal",
  newSession: "New",
  newTab: "New terminal",
  reattach: (name: string) => `Reattach · ${name}`,
  close: "Close this one",
  end: "End session",
  endConfirm: "Ending it stops whatever is running inside.",
  stop: "Stop",
  empty: "No terminal sessions yet.",
  emptyHint: "Open one and run your own commands on this machine.",
  needsWorkspace: "Choose a workspace folder in settings first.",
  unavailable: "Terminals are unavailable: the native helper is not in place.",
  exited: "Finished",
  exitedWith: "Finished · exit {code}",
  interrupted: "Interrupted",
  dropped: "Output outran the reader; {bytes} bytes dropped",
  survivesWindow: "Keeps running when the window closes; Quit and reopen puts it back where it was",
  keys: "Control keys",
  find: "Find in terminal",
  findPrevious: "Previous",
  findNext: "Next",
  findClose: "Close find",
  findNone: "No results",
  findMany: "More than {count}",
  sessions: "Switch terminal",
  more: "More",
  clear: "Clear",
  fontSize: "Text size",
  fontSmaller: "Smaller text",
  fontBigger: "Larger text",
  paste: "Paste",
  ctrl: "Ctrl for the next key",
  showKeyboard: "Show keyboard",
  hideKeyboard: "Hide keyboard",
};
