import type { CopyShape } from "./shape.ts";

export const zh = {
  zoomIn: "放大",
  zoomOut: "缩小",
  zoomFit: "适应画面",
  zoomReset: "还原到 100%",
  minimapShow: "显示小地图",
  minimapHide: "收起小地图",
  minimapHint: "小地图：按下或拖动，画面就移到那里",
  title: "这件事",
  topAction: "经过",
  none: "还没有可以看的事。",
  loading: "正在读取…",
  failed: "读不出来。",
  retry: "重试",
  open: "进行中",
  closed: "已结束",
  filter: "只看还在进行的，和交出了产物的",
  filterShort: "只看进行中和有产物的",
  passed: (count: number) => `${count} 人旁观`,
  silent: "这一轮没发言",
  decision: { answer: "回答", approve: "放行", reject: "退回", rework: "转回返工" },
  asked: (question: string) => `问：${question}`,
  roundFold: "收起这一段",
  roundUnfold: "展开这一段",
  roundCards: (count: number) => `${count} 张卡`,
  roundFiles: (count: number) => `${count} 个文件`,
  wokenBy: (name: string) => `由${name}的上一轮叫醒`,
  sessionGroup: (name: string) => `群 · ${name}`,
  sessionDirect: (name: string) => `与${name}的私聊`,
  sessionUnknown: "另一个会话",
  waitingApproval: "在等批准",
  waitingAsk: "在等回答",
  jump: "跳到这一轮",
  outputClose: "收起",
  resize: "调整窗口大小",
  status: {
    running: "进行中",
    waiting_approval: "在等批准",
    waiting_ask: "在等回答",
    completed: "完成",
    redirected: "改道",
    interrupted: "中断",
    stopped: "停下"
  }
};

export const en: CopyShape<typeof zh> = {
  zoomIn: "Zoom in",
  zoomOut: "Zoom out",
  zoomFit: "Fit to view",
  zoomReset: "Reset to 100%",
  minimapShow: "Show minimap",
  minimapHide: "Hide minimap",
  minimapHint: "Minimap: press or drag to move the view there",
  title: "This job",
  topAction: "Trace",
  none: "Nothing to show yet.",
  loading: "Loading…",
  failed: "Couldn’t load this.",
  retry: "Retry",
  open: "In progress",
  closed: "Closed",
  filter: "Only what’s still going, and what handed a file over",
  filterShort: "Going or with files",
  passed: (count: number) => `${count} watched`,
  silent: "Said nothing this turn",
  decision: { answer: "Answered", approve: "Approved", reject: "Sent back", rework: "Back to rework" },
  asked: (question: string) => `Asked: ${question}`,
  roundFold: "Fold this round",
  roundUnfold: "Unfold this round",
  roundCards: (count: number) => (count === 1 ? "1 card" : `${count} cards`),
  roundFiles: (count: number) => (count === 1 ? "1 file" : `${count} files`),
  wokenBy: (name: string) => `Woken by ${name}`,
  sessionGroup: (name: string) => `Group · ${name}`,
  sessionDirect: (name: string) => `Direct with ${name}`,
  sessionUnknown: "Another conversation",
  waitingApproval: "Waiting for approval",
  waitingAsk: "Waiting for an answer",
  jump: "Jump to this turn",
  outputClose: "Put away",
  resize: "Resize window",
  status: {
    running: "In progress",
    waiting_approval: "Waiting for approval",
    waiting_ask: "Waiting for an answer",
    completed: "Done",
    redirected: "Redirected",
    interrupted: "Interrupted",
    stopped: "Stopped"
  }
};
