import type { CopyShape } from "./shape.ts";

/** Every agent's usage in one place (ADR 0080): the floating widget, its panel and the phone's page. */
export const zh = {
  title: "用量",
  /** The Tools menu's entry: a tab on the workbench, the page on a phone. */
  open: "用量",
  widget: "用量挂件",
  show: "查看全部用量",
  hide: "隐藏用量挂件",
  showWidget: "显示用量挂件",
  close: "关闭用量",
  back: "返回",
  left: (percent: string) => `剩${percent}`,
  hours: (count: number) => `${count} 小时`,
  days: (count: number) => `${count} 天`,
  minutes: (count: number) => `${count} 分钟`,
  hoursShort: (count: number) => `${count}h`,
  daysShort: (count: number) => `${count}d`,
  minutesShort: (count: number) => `${count}m`,
  window: "额度",
  model: (name: string, span: string) => `${name} · ${span}`,
  resetsIn: (wait: string) => `${wait}后重置`,
  resetsAt: (when: string) => `${when} 重置`,
  resetsSoon: "即将重置",
  hoursMinutes: (hours: number, minutes: number) => (hours > 0 ? `${hours} 小时 ${minutes} 分` : `${minutes} 分钟`),
  today: (turns: string, tokens: string) => `今天 ${turns} 轮 · ${tokens} token`,
  todayOnly: "只有本应用今天的记录",
  todayOnlyHint: "这些 Agent 不报套餐额度，这里只列本应用今天记下的轮数和 token。",
  credits: (amount: string) => `余额 ${amount}`,
  checkedAt: (time: string) => `${time} 查的`,
  stale: (time: string) => `这次没查到，显示的是 ${time} 的数据`,
  refresh: "刷新",
  refreshing: "刷新中…",
  signedOut: "未登录",
  failed: "没查到用量",
  noPlan: "按 token 计费，没有套餐额度",
  missing: "没找到这个程序",
  own: "默认账号",
  empty: "还没有连接上的本机 Agent：在 设置 › Agent 里装好、登录后，它的用量就出现在这里。",
  more: (count: number) => `还有 ${count} 个账号`
};

export const en: CopyShape<typeof zh> = {
  title: "Usage",
  open: "Usage",
  widget: "Usage widget",
  show: "Show all usage",
  hide: "Hide the usage widget",
  showWidget: "Show the usage widget",
  close: "Close usage",
  back: "Back",
  left: (percent: string) => `${percent} left`,
  hours: (count: number) => `${count}-hour`,
  days: (count: number) => `${count}-day`,
  minutes: (count: number) => `${count}-minute`,
  hoursShort: (count: number) => `${count}h`,
  daysShort: (count: number) => `${count}d`,
  minutesShort: (count: number) => `${count}m`,
  window: "Limit",
  model: (name: string, span: string) => `${name} · ${span}`,
  resetsIn: (wait: string) => `Resets in ${wait}`,
  resetsAt: (when: string) => `Resets ${when}`,
  resetsSoon: "Resets shortly",
  hoursMinutes: (hours: number, minutes: number) => (hours > 0 ? `${hours} h ${minutes} min` : `${minutes} min`),
  today: (turns: string, tokens: string) => `Today ${turns} turns · ${tokens} tokens`,
  todayOnly: "Today's records here only",
  todayOnlyHint: "These agents report no plan limits; this lists the turns and tokens this app recorded today.",
  credits: (amount: string) => `${amount} credits`,
  checkedAt: (time: string) => `Checked ${time}`,
  stale: (time: string) => `Could not check this time; showing what it said at ${time}`,
  refresh: "Refresh",
  refreshing: "Refreshing…",
  signedOut: "Not signed in",
  failed: "Could not read the usage",
  noPlan: "Billed per token: no plan limits",
  missing: "Not found on this computer",
  own: "Default account",
  empty: "No local agent is connected yet: once one is installed and signed in (Settings › Agents), its usage shows here.",
  more: (count: number) => `${count} more accounts`
};
