// Every on-screen line, per language. Bot names follow the app's convention: plain role names.
export const STR = {
  zh: {
    cold: '测试通过。',
    coldSub: '这一轮跑过的命令：0',
    request: '做一个统计字数的命令行小工具，带测试，写好启动说明。',
    placeholder: '发消息，@ 可点名某个 Bot',
    group: '小工具组',
    groupSub: '3 个 Bot',
    arch: '架构师', dev: '开发', wri: '写手',
    archL: '架', devL: '开', wriL: '写', youL: '你',
    lead: '负责人',
    duty: { arch: '拆任务，定结构', dev: '写代码，跑测试', wri: '写文档' },
    thinking: '思考中',
    today: '今天',
    h: {
      team: '交给一组 <em>Bot</em>',
      spec: '验收，由<em>你</em>来定',
      back: '没依据的「通过」，<em>退回一次</em>',
      ask: '越出工作区，<em>先问你</em>',
      checks: '验收，应用在本机<em>自己跑</em>',
      chase: '停在半路，<em>应用去追</em>'
    },
    running: '进行中', done: '已完成', todo: '待做', passed: '已通过', fin: '完成',
    planSub0: '小工具组 · 架构师正在拆任务',
    planSub1: '小工具组 · 3 个任务',
    lastNow: '上次变化 刚刚',
    lastAgo: n => `上次变化 ${n} 分钟前`,
    lastWri: '上次变化 刚刚（写手 正在做）',
    tickets: '任务', ticketCount: '3 未完成 · 共 3',
    t1: '定参数和结构', t2: '实现 wc.py 和测试', t3: '写启动说明',
    willDo: n => `${n}来做`, doing: n => `${n}在做`,
    ball: n => `球在 ${n} 手里`,
    segSpec: '要点', segTickets: '任务',
    reqTitle: '你的要求', r1: '带测试', r2: '写好启动说明', youSaid: '你说的',
    checks: '检查', addCheck: '+ 检查', youAdded: '你加的',
    sum: (p, n) => `${p}/${n} 通过`,
    st: { fail: '没过', pass: '通过', run: '跑着' },
    cYou: '做一个统计字数的命令行小工具，带测试，写好启动说明。',
    cArch: '拆成 3 个任务。@开发 写 wc.py 和测试，@写手 写 README。',
    cDev1: '写 wc.py 和 test_wc.py。',
    cWri1: 'README 先列了提纲。',
    cDev2: '跑 pytest：1 failed，修好空文件，12 passed。',
    cDev3: '装到 ~/.local/bin/wc（已允许）。',
    cWri2: 'README 写好了：安装、用法、示例。',
    reason1: '拆任务，思考 中', reason2: '写代码，思考 高', reason3: '写文档，思考 低',
    cmds: n => `跑过 ${n} 条命令`,
    group2: '群 · 小工具组',
    draftLabel: '正要发出',
    claimA: ' 写完了，', claimB: '测试通过', claimC: '。',
    counter: '这一轮跑过的命令：0',
    appNote: '退回一次',
    appNoteText: '说了测试通过，这一轮一条命令都没跑。先跑一遍，或写明未验证。',
    runCmds: '跑命令',
    fixNote: '# 修 wc.py：空文件该返回 0',
    needApproval: '等你批准',
    wantsOutside: '要写工作区外',
    allowOnce: '允许一次', always: 'Always allow', deny: '拒绝', allowed: '已允许',
    recall: n => `叫回 ${n}`,
    recalled: '叫回',
    word: 'Deskfolk',
    category: '开源的本机多 Bot 协作应用',
    tagline: '交给一组 Bot，盯到交付。',
    cta: '下载 Alpha',
    url: 'github.com/Blackman99/deskfolk',
    fine: 'macOS · Windows 预览版 · MIT 开源 · 用你自己的模型端点',
    finer: '画面为示意，按真实功能重绘'
  },
  en: {
    cold: 'Tests pass.',
    coldSub: 'Commands run this turn: 0',
    request: 'Build a word-count CLI with tests and a how-to-run guide.',
    placeholder: 'Message, @ to call a Bot',
    group: 'Tool crew',
    groupSub: '3 Bots',
    arch: 'Architect', dev: 'Builder', wri: 'Writer',
    archL: 'A', devL: 'B', wriL: 'W', youL: 'You',
    lead: 'Lead',
    duty: { arch: 'Splits the work', dev: 'Writes code, runs tests', wri: 'Writes the docs' },
    thinking: 'Thinking',
    today: 'Today',
    h: {
      team: 'Hand it to a team of <em>Bots</em>',
      spec: '<em>You</em> set the done-when',
      back: 'An unbacked “pass” <em>goes back once</em>',
      ask: 'Outside the workspace? <em>It asks</em>',
      checks: 'The app runs the checks <em>itself</em>',
      chase: 'Stalled halfway? <em>It chases</em>'
    },
    running: 'In progress', done: 'Done', todo: 'To do', passed: 'Passed', fin: 'Done',
    planSub0: 'Tool crew · Architect is splitting it',
    planSub1: 'Tool crew · 3 tickets',
    lastNow: 'Last change just now',
    lastAgo: n => `Last change ${n} min ago`,
    lastWri: 'Last change just now (Writer working)',
    tickets: 'Tickets', ticketCount: '3 open · 3 total',
    t1: 'Options and layout', t2: 'wc.py and its tests', t3: 'How-to-run guide',
    willDo: n => `${n} to do`, doing: n => `${n} on it`,
    ball: n => `Ball’s with ${n}`,
    segSpec: 'Spec', segTickets: 'Tickets',
    reqTitle: 'Your requirements', r1: 'With tests', r2: 'A how-to-run guide', youSaid: 'You said',
    checks: 'Checks', addCheck: '+ Check', youAdded: 'You added',
    sum: (p, n) => `${p}/${n} pass`,
    st: { fail: 'Failed', pass: 'Passed', run: 'Running' },
    cYou: 'Build a word-count CLI with tests and a how-to-run guide.',
    cArch: 'Three tickets. @Builder: wc.py and tests. @Writer: the README.',
    cDev1: 'Writing wc.py and test_wc.py.',
    cWri1: 'Outlined the README first.',
    cDev2: 'Ran pytest: 1 failed, fixed empty files, 12 passed.',
    cDev3: 'Installed to ~/.local/bin/wc (allowed).',
    cWri2: 'README done: install, usage, examples.',
    reason1: 'splitting work, medium', reason2: 'writing code, high', reason3: 'writing docs, low',
    cmds: n => `${n} commands run`,
    group2: 'Group · Tool crew',
    draftLabel: 'about to send',
    claimA: ' is done, ', claimB: 'tests pass', claimC: '.',
    counter: 'Commands run this turn: 0',
    appNote: 'Sent back once',
    appNoteText: 'You said tests pass, but ran no command this turn. Run them, or say it’s unverified.',
    runCmds: 'running commands',
    fixNote: '# fix wc.py: an empty file counts 0',
    needApproval: 'Needs your approval',
    wantsOutside: 'wants to write outside the workspace',
    allowOnce: 'Allow once', always: 'Always allow', deny: 'Deny', allowed: 'Allowed',
    recall: n => `Called back ${n}`,
    recalled: 'Called back',
    word: 'Deskfolk',
    category: 'An open-source app for a team of Bots, local on your Mac',
    tagline: 'Hand it to Bots that see it through.',
    cta: 'Download the alpha',
    url: 'github.com/Blackman99/deskfolk',
    fine: 'macOS · Windows preview · MIT · Bring your own model endpoint',
    finer: 'Illustrative re-creation of real features'
  }
};
